In [18]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from tqdm import tqdm

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

## Load motions from calico tabs

In [19]:
urls = """
https://hwsrr2025.calicotab.com/_/
https://usudc2025.calicotab.com/_/
https://wudc2025.calicotab.com/open/
https://paudc2024.calicotab.com/paudcK24/
https://edudrift.calicotab.com/abp2024/
https://neadc2024.calicotab.com/neadc2024/
https://eudc2024.calicotab.com/_/
https://naudc2024.calicotab.com/naudc2024/ 
https://wudc2024.calicotab.com/wudc/
https://edudrift.calicotab.com/neadc2023/
https://usudc2023.calicotab.com/usudc2023/
https://midp.calicotab.com/mabp2023/
https://eudc2023.calicotab.com/_/
https://naudc2023.calicotab.com/naudc2023/
https://hwsrr2023.calicotab.com/hwsrr2023/
https://wudc2023.calicotab.com/wudc/
https://paudc2022.calicotab.com/PAUDC2022/ 
https://edudriftbackup.calicotab.com/abp2022/
https://usudc2022.calicotab.com/usudc2022/
http://neadc2022.calicotab.com/2022/
https://eudc2022.calicotab.com/eudc2022/
http://wudc2022.calicotab.com/wudc/
https://naudc2021.calicotab.com/_/tab/team/
http://neadc.calicotab.com/neadc/
https://awdc2021.herokuapp.com/sydneyAWDC/
https://abp2021.calicotab.com/abp2021/
https://mace.calicotab.com/sanudc2021/
https://mace.calicotab.com/paudc2021/
https://eudc2021.calicotab.com/eudc2021/
https://wudckorea.calicotab.com/2021/
https://naudc2020.herokuapp.com/naudc2020/s
https://rrtabs.herokuapp.com/paudc2020/
https://awdc2020.herokuapp.com/awdc/results/round/11/
https://abp2020.calicotab.com/abp2020/
https://eudc2020.calicotab.com/eudc2020/
https://wudc2020.calicotab.com/wudc2020/
https://usudc2020.calicotab.com/usudc2020/
https://wudc2018.calicotab.com/wudc2018/
https://wudc2014.calicotab.com/wudc2014/
https://edudrift.calicotab.com/uadc2025/
https://uadc2024.au-tab.app/uadc2024/
http://malaysiauadc2022.calicotab.com/malaysiauadc2022/ 
https://bduadc2020.calicotab.com/uadc2020/
https://edudrift.calicotab.com/australs2025/
https://edudrift.calicotab.com/australs2024/
https://krabiaustrals2023.calicotab.com/australs2023/
https://australs2022.calicotab.com/australs2022/
https://australs2021.calicotab.com/_/
https://australs2020.calicotab.com/australs2020/
http://easters2025.calicotab.com/easters2025/
http://easters2024.calicotab.com/easters2024/?fbclid=IwAR0sUz8N7MtT4z_oaK1AT0ADfBs6xaN0pI8OKc7UcIcEyIzl9q3KfI8czRc_aem_AXCb6j-ifosiNs7_5os8Toueas-lu4DEPfiNtzMYdm97tPYCG9X3Z_hVbLv9gxf6fv9cCQf6odNf6HRdEJvCfJhY
http://easters2023.calicotab.com/easters2023/motions/
https://easters2022.calicotab.com/easters2022/
https://onlineeasters2021.calicotab.com/onlineeasters2021/
https://wsdc2024.calicotab.com/wsdc2024/
"""

# https://docs.google.com/spreadsheets/d/1ryOKiMPPW7tP-lsvkR8xM6u1r4JmrSkj4UMitseckKM/pub?gid=0#
# http://tabbycat.idebate.net/
# https://tinyurl.com/tab
# https://docs.google.com/spreadsheets/u/0/d/1lralzhC-MUcXZsEOQ4i6b_Ep0nLzbU4b_kd1aIxgb1M/htmlview#
# https://docs.google.com/spreadsheets/d/1oBOCHbLLJAtekaVPP0tZldolpZjFY5-x1eoU-CDGRJU/edit?fbclid=IwAR0m9Y3hFxq0N7HUrQVws8htQRMvSLN-3iyP-GT0vy-brYZJr8mJsDSxXoI#gid=892844460

# https://cmude2024.calicotab.com/open/
# https://cmude2023.calicotab.com/cmude2023/
# https://cmude2022.calicotab.com/cmude2022/
# https://cmude2021.calicotab.com/cmudeecuador2021/
# https://cmudemadrid2020.calicotab.com/cmude2020/
# https://cmude2019.calicotab.com/cmude2019/
# https://cmude2018.calicotab.com/

In [20]:
calico_tabs = set()

for url in urls.split('\n'): 
    if 'calicotab' not in url:
        continue

    australs_pattern = re.compile(r'https?:\/\/(\w+)\.calicotab\.com\/(\w+)\/')
    match = re.match(australs_pattern, url)

    if match is None:
        print(f'[WARN] Could not parse url: {url}')
        continue

    subdomain = match.group(1)
    slug = match.group(2)

    calico_tabs.add((subdomain, slug))

    # print(subdomain, slug)

calico_tabs = list(calico_tabs)

In [21]:
calico_tabs[:5]

[('wudc2024', 'wudc'),
 ('mace', 'paudc2021'),
 ('wudckorea', '2021'),
 ('paudc2022', 'PAUDC2022'),
 ('abp2020', 'abp2020')]

In [ ]:
allowed_sides = ["og", "oo", "cg", "co"]


async def retrieve_results(pairings_url, session):
    results = {}

    async with session.get(pairings_url) as pairings_response:
        pairings = await pairings_response.json()
        results["n"] = len(pairings)

        for pairing in pairings:
            try:
                ballots_url = pairing["_links"]["ballots"]
                ballots = None
                async with session.get(ballots_url) as ballots_response:
                    ballots = await ballots_response.json()

                if (
                    "detail" in ballots
                    and ballots["detail"]
                    == "Authentication credentials were not provided."
                ):
                    print(
                        f"[WARN] Behind auth for URL {pairings_url}. Skipping extracting ballots..."
                    )

                    # TODO: streamline by stopping to check ballots completely for tournaments if behind auth wall
                    return {}

                #FIXME: deal with motion used in multiple rounds
                assert len(ballots) == 1, "Expected 1 ballot for pairing URL: " + pairings_url
                sheets = ballots[0]["result"]["sheets"]

                if len(sheets) > 1:
                    print(
                        f"[WARN] Multiple sheets at URL: {ballots_url}. Using only the first sheet." #FIXME:
                    )

                teams = sheets[0]["teams"]

                if teams[0]["side"] not in allowed_sides:
                    print(
                        f'[WARN] First team in sheet is not a valid BP position: {ballots_url}. Skipping extracting ballots...'
                    )

                    return {}

                for i, team in enumerate(teams):
                    side = team["side"]
                    assert side in allowed_sides

                    points = team["points"]
                    win = team["win"] 

                    assert (
                        points is not None or win is not None
                    ), f"Points and wins are both None for side: {side}"

                    if points is not None:
                        prev_sum = results.get("sum_" + side, 0)
                        results["sum_" + side] = prev_sum + points
                    
                        # sum up the points for all pairs of teams
                        # needed for balance calculation
                        for team2 in teams[i:]:
                            side2 = team2['side']

                            key = "sum_" + side + "_" + side2
                            prev_sum_sum = results.get(key, 0)
                            results[key] = prev_sum_sum + team2['points'] * points

                    if win is True:
                        key = side + "_wins"
                        prev_wins = results.get(key, 0)
                        results[key] = prev_wins + 1
                    
                    if team["score"] is not None:
                        key = "speaks"
                        prev_speaks = results.get(key, 0)
                        results[key] = prev_speaks + team["score"]

            except Exception as e:
                print("[ERROR] Failed to fetch ballots for pairing URL: ", pairings_url)
                print(f"Error: {e}")
    
    return results

In [23]:
supported_sides = ["og", "oo", "cg", "co"]

async def are_ballots_accessible(session, main_url):
    round_1_pairings_url = main_url + "/rounds/1/pairings"
    async with session.get(round_1_pairings_url) as round_1_pairings_response:
        round_1_pairings = await round_1_pairings_response.json()
        first_pairing = round_1_pairings[0]

        ballot_url = first_pairing["_links"]["ballots"]
        async with session.get(ballot_url) as ballot_response:
            ballots = await ballot_response.json()

            if (
                "detail" in ballots
                and ballots["detail"]
                == "Authentication credentials were not provided."
            ):
                # TODO: streamline by stopping to check ballots completely for tournaments if behind auth wall
                return False
            
            sheet = ballots[0]['result']['sheets'][0]

            for team in sheet['teams']:
                if team['side'] not in supported_sides:
                    return False
    
    return True

In [24]:
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await are_ballots_accessible(session, 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_')
    assert response == True
    response = await are_ballots_accessible(session, 'https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24')
    assert response == False
    response = await are_ballots_accessible(session, 'https://australs2021.calicotab.com/api/v1/tournaments/_')
    assert response == False

In [ ]:
import asyncio 

async def retrieve_motions(subdomain, slug, session):
    rows = []

    tab_url = f"https://{subdomain}.calicotab.com/{slug}"
    
    main_url = f"https://{subdomain}.calicotab.com/api/v1/tournaments/{slug}"
    motions_url = f"{main_url}/motions"

    tournament_name = None
    tournament_short_name = None
    async with session.get(main_url) as response:
        motion_json = await response.json()
        tournament_name = motion_json['name']
        tournament_short_name = motion_json['short_name']

    is_ballotable = await are_ballots_accessible(session, main_url)

    if not is_ballotable:
        print(f'[WARN] Ballots not accessible or not supported for URL: {main_url}')

    results = {}

    async with session.get(motions_url) as response:
        try: 
            assert response.status == 200, f"Failed to fetch {motions_url}: {response.status}"
        except: 
            print(f'[WARN] Failed to fetch API for url: {motions_url}')
            return []

        try: 
            motions = await response.json()
            for motion in motions:
                if len(motion['rounds']) <= 0: #skip unused (test) motions
                    print(f'[WARN] Skipping motion: {motion["text"]} from URL: {motions_url} because it has no rounds.')
                    continue

                rounds_parsed = {}

                rounds = motion['rounds']
                for i,round in enumerate(rounds): 
                    round_url = round['round']

                    async with session.get(round_url) as round_response:
                        round_json = await round_response.json()

                        try: 
                            rounds_parsed[f'round_{i+1}'] = round_json['name']
                            rounds_parsed[f'stage_{i+1}'] = round_json['stage']
                        except KeyError as e: 
                            print(f'[WARN] Skipping motion: {motion["text"]} from URL: {motions_url} because of no corresponding round exists.') #this can happen if tournament/round was deleted
                            continue

                        pairings_url = round_json['_links']['pairing']

                        if is_ballotable:
                            results = await retrieve_results(pairings_url, session)

                row = {
                    'Motion': motion['text'],
                    'Info Slide': motion['info_slide_plain'],
                    'Tournament': tournament_name,
                    'short_name': tournament_short_name,
                    'tab_url': tab_url,
                    **results,
                    **rounds_parsed,
                }

                rows.append(row)

        except Exception as e:
            print(f'[ERROR] Failed to fetch motions for URL: {motions_url}')
            print(f'Error: {e.with_traceback()}')
            return rows

    return rows

In [26]:
#check
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await retrieve_motions('hwsrr2025', '_', session)
print(response)

[{'Motion': 'This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 12, 'sum_og_og': 36, 'sum_og_oo': 9, 'sum_og_cg': 12, 'sum_og_co': 15, 'speaks': 2579.0, 'sum_oo': 3, 'sum_oo_oo': 5, 'sum_oo_cg': 0, 'sum_oo_co': 4, 'sum_cg': 4, 'sum_cg_cg': 8, 'sum_cg_co': 4, 'sum_co': 5, 'sum_co_co': 7, 'round_1': 'Round 1-A', 'stage_1': 'P', 'round_2': 'Round 1-B', 'stage_2': 'P'}, {'Motion': 'This house regrets the Indian Premier League.', 'Info Slide': 'The Indian Premier League (IPL) is a domestic cricket league in India. Since\nits inception in 2007, it has grown to become the largest cricket league in\nthe world, attracting sponsorship that exceeds that of most national teams.\n\nTraditionally, cricket competition has been dominated by international events\nand national teams touring other countries, and has involved games lasting\neither five days or one day. The IPL popularized large-scale domestic cricket\nleagues, and is played in a shorter, three-hour format of cricket called\nTwenty20 (T20). Teams are allowed up to 4 international (non-Indian) players\nin their teams. Additionally, the IPL usually lasts 3-4 months, taking up a\nsignificant portion of the annual cricket calendar.', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 2, 'sum_og_og': 2, 'sum_og_oo': 5, 'sum_og_cg': 0, 'sum_og_co': 5, 'speaks': 2574.0, 'sum_oo': 9, 'sum_oo_oo': 23, 'sum_oo_cg': 5, 'sum_oo_co': 21, 'sum_cg': 3, 'sum_cg_cg': 5, 'sum_cg_co': 8, 'sum_co': 10, 'sum_co_co': 26, 'round_1': 'Round 2-A', 'stage_1': 'P', 'round_2': 'Round 2-B', 'stage_2': 'P'}, {'Motion': 'This house believes that breaking up large meat companies is in the interests of animal welfare.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 6, 'sum_og_og': 10, 'sum_og_oo': 9, 'sum_og_cg': 8, 'sum_og_co': 9, 'speaks': 2544.0, 'sum_oo': 7, 'sum_oo_oo': 15, 'sum_oo_cg': 9, 'sum_oo_co': 9, 'sum_cg': 5, 'sum_cg_cg': 13, 'sum_cg_co': 0, 'sum_co': 6, 'sum_co_co': 18, 'round_1': 'Round 3-A', 'stage_1': 'P', 'round_2': 'Round 3-B', 'stage_2': 'P'}, {'Motion': 'This house prefers a world where genius only develops after adulthood (so that there are no child prodigies).', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 8, 'sum_og_og': 22, 'sum_og_oo': 12, 'sum_og_cg': 6, 'sum_og_co': 8, 'speaks': 2592.0, 'sum_oo': 7, 'sum_oo_oo': 17, 'sum_oo_cg': 6, 'sum_oo_co': 7, 'sum_cg': 5, 'sum_cg_cg': 13, 'sum_cg_co': 5, 'sum_co': 4, 'sum_co_co': 4, 'round_1': 'Round 4-A', 'stage_1': 'P', 'round_2': 'Round 4-B', 'stage_2': 'P'}, {'Motion': 'This house believes that East African national governments should prioritize investments in agriculture (e.g., irrigation, R&D, and inputs like fertilizer) over accelerating industrialization (e.g., building infrastructure, export promotion).', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 12, 'sum_og_og': 36, 'sum_og_oo': 9, 'sum_og_cg': 9, 'sum_og_co': 18, 'speaks': 2585.0, 'sum_oo': 3, 'sum_oo_oo': 3, 'sum_oo_cg': 2, 'sum_oo_co': 4, 'sum_cg': 3, 'sum_cg_cg': 5, 'sum_cg_co': 2, 'sum_co': 6, 'sum_co_co': 12, 'round_1': 'Round 5-A', 'stage_1': 'P', 'round_2': 'Round 5-B', 'stage_2': 'P'}, {'Motion': 'Assuming a peaceful and democratic transition, this house supports the United States of America being separated into several, more politically-homogeneous, sovereign states.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 1, 'cg_wins': 1, 'round_1': 'Grand Final', 'stage_1': 'E'}]

In [28]:
import aiohttp

rows = []

async with aiohttp.ClientSession() as session:
    batch_n = 20
    n = len(calico_tabs)

    print(f"Starting data fetching for {n} tournaments.")

    for i in tqdm(range(0, len(calico_tabs), batch_n)): 
        responses = await asyncio.gather(*(retrieve_motions(subdomain, slug, session) for subdomain, slug in list(reversed(calico_tabs))[i:i+batch_n]))
        batch = [m for row in responses for m in row] #flatten
        rows.extend(batch)

Starting data fetching for 50 tournaments.

  0%|          | 0/3 [00:00<?, ?it/s]

[WARN] Ballots not accessible or not supported for URL: https://easters2023.calicotab.com/api/v1/tournaments/easters2023
[WARN] Ballots not accessible or not supported for URL: https://bduadc2020.calicotab.com/api/v1/tournaments/uadc2020
[WARN] Ballots not accessible or not supported for URL: https://australs2022.calicotab.com/api/v1/tournaments/australs2022
[WARN] Ballots not accessible or not supported for URL: https://onlineeasters2021.calicotab.com/api/v1/tournaments/onlineeasters2021
[WARN] Ballots not accessible or not supported for URL: https://wsdc2024.calicotab.com/api/v1/tournaments/wsdc2024
[WARN] Ballots not accessible or not supported for URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024
[WARN] Ballots not accessible or not supported for URL: https://malaysiauadc2022.calicotab.com/api/v1/tournaments/malaysiauadc2022
[WARN] Ballots not accessible or not supported for URL: https://usudc2020.calicotab.com/api/v1/tournaments/usudc2020
[WARN] Skipping motion: QWERTY from URL: https://wudc2022.calicotab.com/api/v1/tournaments/wudc/motions because it has no rounds.
[WARN] Ballots not accessible or not supported for URL: https://naudc2021.calicotab.com/api/v1/tournaments/_
[WARN] Skipping motion: That renters of public housing should be allowed to purchase that housing at a discounted rate. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: That, in cities facing housing crises, we would remove all heritage protections in building codes. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: That, in states with a low fertility rate, we prefer policies with a familising effect rather than a de-familising effect. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: This House would abolish laws against price-gouging. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This House would abolish laws against price-gouging. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This house, as the Democratic Party in the United States, would swing at every pitch rather than pick battles against the Republican Party from URL: https://usudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Skipping motion: THO the practice of vote buying. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: THO the practice of vote buying. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This House believes that governments should set up a department dedicated to producing and submitting ‘Sokal papers’ to academic journals, removing academics that admit Sokal papers and shutting down faculties that systemically admit ‘Sokal papers’. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This House believes that YouTube should never demonetise a video. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House would allow foreign legal actions against military organisations in a domestic court (e.g. a Mexican citizen suing a USA military organisation in a USA court for an act committed in Mexico). from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House regrets the narrative that everything happens for a reason. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House believes that disability activist groups should support a narrative of people with different abilities rather than disabilities (e.g. no longer investing resources into researching a cure to deafness, and instead actively encouraging society to adapt with people who are deaf by learning sign language, making closed captions mandatory etc.) from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House believes that the Australian Government should redirect money from foster care programs to adoption programs (e.g. lifting restrictions on adoption, promoting adoption, etc.). from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House supports the emergence of Chinese led/backed/created multilateral institutions like the AIIB, Shanghai Cooperative, and the NDB. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House would ban the development and use of human augmentation technology (e.g bionic limbs, implanted chips) for non-restorative purposes. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.

 33%|███▎      | 1/3 [03:22<06:45, 202.73s/it]

[WARN] Ballots not accessible or not supported for URL: https://edudrift.calicotab.com/api/v1/tournaments/uadc2025
[WARN] Ballots not accessible or not supported for URL: https://eudc2020.calicotab.com/api/v1/tournaments/eudc2020
[WARN] Ballots not accessible or not supported for URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2025
[WARN] Ballots not accessible or not supported for URL: https://easters2025.calicotab.com/api/v1/tournaments/easters2025
[WARN] Ballots not accessible or not supported for URL: https://eudc2021.calicotab.com/api/v1/tournaments/eudc2021
[WARN] Ballots not accessible or not supported for URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024
[WARN] Ballots not accessible or not supported for URL: https://abp2021.calicotab.com/api/v1/tournaments/abp2021
[WARN] Ballots not accessible or not supported for URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022
[WARN] Ballots not accessible or not supported for URL: https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.

 67%|██████▋   | 2/3 [06:38<03:18, 198.90s/it]

[WARN] Ballots not accessible or not supported for URL: https://mace.calicotab.com/api/v1/tournaments/paudc2021
[WARN] Ballots not accessible or not supported for URL: https://krabiaustrals2023.calicotab.com/api/v1/tournaments/australs2023
[WARN] Ballots not accessible or not supported for URL: https://abp2020.calicotab.com/api/v1/tournaments/abp2020
[WARN] Ballots not accessible or not supported for URL: https://australs2020.calicotab.com/api/v1/tournaments/australs2020
[WARN] Ballots not accessible or not supported for URL: https://australs2021.calicotab.com/api/v1/tournaments/_
[WARN] Ballots not accessible or not supported for URL: https://wudckorea.calicotab.com/api/v1/tournaments/2021
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.

100%|██████████| 3/3 [09:24<00:00, 188.18s/it]

In [33]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(rows)
df

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2
0,That the South Korean government should redire...,Koryo-in (고려인) are Korean diasporas residing i...,Jakarta Australasian Intervarsity Debate Champ...,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,That we oppose Australia's 501 policy.,Australia's 501 policy refers to section 501 o...,Jakarta Australasian Intervarsity Debate Champ...,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,That we oppose countries adopting ‘pull-back’ ...,Irregular migrants are those who enter another...,Jakarta Australasian Intervarsity Debate Champ...,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,That we regret self-denial in religion (e.g. c...,,Jakarta Australasian Intervarsity Debate Champ...,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"That, in multireligious states, schools should...","In ‘integrated religious education’, all stude...",Jakarta Australasian Intervarsity Debate Champ...,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1073,This House would ban defensive measures agains...,Defensive measures against hostile take overs ...,Vietnam World Universities Debating Championsh...,https://wudc2024.calicotab.com/wudc,ESL Semifinals,E,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,NaN,NaN
1074,This House would ban vulture funds from suing ...,A vulture fund is fund that invests in soverei...,Vietnam World Universities Debating Championsh...,https://wudc2024.calicotab.com/wudc,Semifinals,E,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN
1075,This House believes that post-revolutionary st...,,Vietnam World Universities Debating Championsh...,https://wudc2024.calicotab.com/wudc,EFL Finals,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1076,This House welcomes the end of work,,Vietnam World Universities Debating Championsh...,https://wudc2024.calicotab.com/wudc,ESL Finals,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1077,This House opposes the norm to prefer the natu...,,Vietnam World Universities Debating Championsh...,https://wudc2024.calicotab.com/wudc,Grand Final,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

## Scraping from Tabbycat 

DEPRECATED!! Only works for WSDC.

In [ ]:
# calico_tabs = [
#     ('nsdc25', 'NordicSDC2025'),
#     ('eurosdc25', 'eurosdc-25'),
#     # ('esdc', 'esdc2025'),
#     ('argument', 'eco2025'),
#     ('argument', 'ECO2024'),
#     ('nordics2023', 'nordics2023')
# ]

In [ ]:
def parse_motion(div): 
    """
    Given a motion top-level div, parse out the relevant details.
    """
    round = div.find('span', class_="badge").get_text(strip=True)
    motion = div.find('h4').find(string=True, recursive=False).strip()

    info_slide = div.find(string=re.compile("View Info Slide"))
    info_slide_text = None

    if info_slide is not None:
        info_slide_text = info_slide.find_next('div', class_='modal-body').get_text(strip=True)

    # regex match the wins for prop and opp
    text = div.get_text()

    re_prop = re.compile(r"(\d+) (Prop|Gov) win")
    re_opp = re.compile(r"(\d+) Opp win")

    prop_wins = re.findall(re_prop, text)[0][0]
    opp_wins = re.findall(re_opp, text)[0][0]

    balance = div.find(string=re.compile('balance')).get_text(strip=True)

    return motion, round, info_slide_text, prop_wins, opp_wins, balance

In [35]:
data = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    "Prop wins": [],
    "Opp wins": [],
    "Balance": [],
}

for subdomain, slug in calico_tabs:
    calico_url = f"https://{subdomain}.calicotab.com/{slug}"

    motions_suburl = f"motions/statistics"
    motions_url = f"{calico_url}/{motions_suburl}"

    response = requests.get(motions_url) 
    try: 
        assert response.status_code == 200, f"Failed to fetch {motions_url}: {response.status_code}"
    except: 
        continue

    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    try:
        motion_divs = soup.find_all('div', class_="list-group mt-3")
        print(f"Found {len(motion_divs)} motions from {slug}.")

        for start in tqdm(range(len(motion_divs))):
            div = motion_divs[start]
            motion, round, info_slide_text, prop_wins, opp_wins, balance = parse_motion(div)
            

            data["Motion"].append(motion)
            data["Round"].append(round)
            data["Info Slide"].append(info_slide_text)
            data["Prop wins"].append(int(prop_wins))
            data["Opp wins"].append(int(opp_wins))
            data["Balance"].append(balance)
            data["Tournament"].append(slug)
    except: 
        print(f'[WARN] could not parse motions for url: {calico_url}')

Found 11 motions from _.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2025.calicotab.com/_

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2025.calicotab.com/_

Found 12 motions from paudcK24.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2024.calicotab.com/paudcK24

Found 12 motions from abp2024.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/abp2024

Found 11 motions from neadc2024.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2024.calicotab.com/neadc2024

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2024.calicotab.com/_

Found 14 motions from naudc2024.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2024.calicotab.com/naudc2024

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2024.calicotab.com/wudc

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 13 motions from usudc2023.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2023.calicotab.com/usudc2023

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 12 motions from mabp2023.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://midp.calicotab.com/mabp2023

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2023.calicotab.com/_

Found 11 motions from hwsrr2023.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2023.calicotab.com/hwsrr2023

Found 17 motions from wudc.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2023.calicotab.com/wudc

Found 13 motions from PAUDC2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2022.calicotab.com/PAUDC2022

Found 12 motions from abp2022.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudriftbackup.calicotab.com/abp2022

Found 13 motions from usudc2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2022.calicotab.com/usudc2022

Found 15 motions from 2022.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2022.calicotab.com/2022

Found 14 motions from eudc2022.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2022.calicotab.com/eudc2022

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2022.calicotab.com/wudc

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2021.calicotab.com/_

Found 13 motions from neadc.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc.calicotab.com/neadc

Found 17 motions from abp2021.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2021.calicotab.com/abp2021

Found 8 motions from sanudc2021.

  0%|          | 0/8 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/sanudc2021

Found 13 motions from paudc2021.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/paudc2021

Found 14 motions from eudc2021.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2021.calicotab.com/eudc2021

Found 19 motions from 2021.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudckorea.calicotab.com/2021

Found 13 motions from abp2020.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2020.calicotab.com/abp2020

Found 16 motions from eudc2020.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2020.calicotab.com/eudc2020

Found 19 motions from wudc2020.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2020.calicotab.com/wudc2020

Found 14 motions from usudc2020.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2020.calicotab.com/usudc2020

Found 19 motions from wudc2018.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2018.calicotab.com/wudc2018

Found 19 motions from wudc2014.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2014.calicotab.com/wudc2014

KeyboardInterrupt:

In [37]:
df1 = pd.DataFrame(data)
df1.tail()

Empty DataFrame
Columns: [Tournament, Motion, Round, Info Slide, Prop wins, Opp wins, Balance]
Index: []

## Parse WSDC motions from .txt on GitHub
https://github.com/tokyodebate/motions/blob/main/International/WSDC.txt

In [56]:
import requests

url = 'https://raw.githubusercontent.com/tokyodebate/motions/refs/heads/main/International/WSDC.txt'

response = requests.get(url)
wsdc_motions_raw = response.text

In [57]:
def count_tabs(line: str):
    """
    Count the number of tabs in a line.
    """
    return line.count('\t')

In [58]:
data2 = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    # "Prop wins": [],
    # "Opp wins": [],
    # "Balance": [],
}

def parse_wsdc_motions():
    lines = wsdc_motions_raw.split('\n')
    lines = [line.strip('\n') for line in lines]
    lines = lines[1:] # Skip the header

    tournament = None
    round = None

    for i in range(len(lines)):
        curr = lines[i]

        if count_tabs(curr) == 1: 
            tournament = curr.strip()
        elif count_tabs(curr) == 2:
            round = curr.strip()
        elif count_tabs(curr) == 3:
            next_line = lines[i+1] if i+1 < len(lines) else None
            info_text = next_line.strip() if next_line and count_tabs(next_line) == 4 else None

            motion = curr.strip()   
            data2["Motion"].append(motion)
            data2["Round"].append(round)
            data2["Info Slide"].append(info_text)
            data2["Tournament"].append(tournament)

        else:
            continue

parse_wsdc_motions()

In [59]:
df2 = pd.DataFrame(data2)
df2.value_counts('Tournament')

Tournament
Netherlands WSDC 2022                                                           21
WSDC Mexico 2020                                                                20
24th World Schools Debating Championships 2012, South Africa                    13
21st World Schools Debating Championships 2009 in Athens, Greece                13
Vietnam WSDC 2023                                                               13
30th World Schools Debating Championships 2018, Croatia and Slovenia            13
29th World Schools Debating Championships 2017, Indonesia                       13
28th World Schools Debating Championships 2016, Germany                         13
27th World Schools Debating Championships 2015, Singapore                       13
WSDC Thailand 2019                                                              13
16th World Schools Debating Championships 2004 in Stuttgart, Germany            13
15th World Schools Debating Championships 2003 in Lima, Peru                    13
19th World Schools Debating Championships 2007 in Seoul, South Korea            13
17th World Schools Debating Championships 2005 in Calgary, Canada               13
18th World Schools Debating Championships 2006 in Cardiff, Wales                12
13th World Schools Debating Championships 2001 in Johannesburg, South Africa    12
14th World Schools Debating Championships 2002 in Singapore                     12
20th World Schools Debating Championships 2008 in Washington DC, USA            12
25th World Schools Debating Championships 2013, Turkey                          12
11th World Schools Debating Championships 1999 in London, England               12
23rd World Schools Debating Championships 2011, Dundee                          12
22nd World Schools Debating Championships 2010, Doha                            12
26th World Schools Debating Championships 2014, Thailand                        11
WSDC Macau Online 2021                                                          11
6th World Schools Debating Championships 1994 in New Zealand                     9
9th World Schools Debating Championships 1997 in Bermuda                         5
10th World Schools Debating Championships 1998 in Jerusalem, Israel              5
12th World Schools Debating Championships 2000 in Pittsburgh, PA, USA            4
Name: count, dtype: int64

In [60]:
df = pd.concat([df, df2], ignore_index=True)

,Motion,Info Slide,Tournament,Round
0,This house prefers that progressive journalist...,,hwsrr2025:_,NaN
1,This house regrets the Indian Premier League.,The Indian Premier League (IPL) is a domestic ...,hwsrr2025:_,NaN
2,This house believes that breaking up large mea...,,hwsrr2025:_,NaN
3,This house prefers a world where genius only d...,,hwsrr2025:_,NaN
4,This house believes that East African national...,,hwsrr2025:_,NaN

## Store data

In [34]:
import os

data_dir = 'raw'

os.makedirs(data_dir, exist_ok=True)
df.to_csv(os.path.join(data_dir, 'motions_bp.csv'))