In [4]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from tqdm import tqdm

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

## Load motions from calico tabs

In [9]:
urls = """
https://hwsrr2025.calicotab.com/_/
https://usudc2025.calicotab.com/_/
https://wudc2025.calicotab.com/open/
https://paudc2024.calicotab.com/paudcK24/
https://edudrift.calicotab.com/abp2024/
https://neadc2024.calicotab.com/neadc2024/
https://eudc2024.calicotab.com/_/
https://naudc2024.calicotab.com/naudc2024/ 
https://wudc2024.calicotab.com/wudc/
https://edudrift.calicotab.com/neadc2023/
https://usudc2023.calicotab.com/usudc2023/
https://midp.calicotab.com/mabp2023/
https://eudc2023.calicotab.com/_/
https://naudc2023.calicotab.com/naudc2023/
https://hwsrr2023.calicotab.com/hwsrr2023/
https://wudc2023.calicotab.com/wudc/
https://paudc2022.calicotab.com/PAUDC2022/ 
https://edudriftbackup.calicotab.com/abp2022/
https://usudc2022.calicotab.com/usudc2022/
http://neadc2022.calicotab.com/2022/
https://eudc2022.calicotab.com/eudc2022/
http://wudc2022.calicotab.com/wudc/
https://naudc2021.calicotab.com/_/tab/team/
http://neadc.calicotab.com/neadc/
https://awdc2021.herokuapp.com/sydneyAWDC/
https://abp2021.calicotab.com/abp2021/
https://mace.calicotab.com/sanudc2021/
https://mace.calicotab.com/paudc2021/
https://eudc2021.calicotab.com/eudc2021/
https://wudckorea.calicotab.com/2021/
https://naudc2020.herokuapp.com/naudc2020/s
https://rrtabs.herokuapp.com/paudc2020/
https://awdc2020.herokuapp.com/awdc/results/round/11/
https://abp2020.calicotab.com/abp2020/
https://eudc2020.calicotab.com/eudc2020/
https://wudc2020.calicotab.com/wudc2020/
https://usudc2020.calicotab.com/usudc2020/
https://wudc2018.calicotab.com/wudc2018/
https://wudc2014.calicotab.com/wudc2014/
https://edudrift.calicotab.com/uadc2025/
https://uadc2024.au-tab.app/uadc2024/
http://malaysiauadc2022.calicotab.com/malaysiauadc2022/ 
https://bduadc2020.calicotab.com/uadc2020/
https://edudrift.calicotab.com/australs2025/
https://edudrift.calicotab.com/australs2024/
https://krabiaustrals2023.calicotab.com/australs2023/
https://australs2022.calicotab.com/australs2022/
https://australs2021.calicotab.com/_/
https://australs2020.calicotab.com/australs2020/
http://easters2025.calicotab.com/easters2025/
http://easters2024.calicotab.com/easters2024/?fbclid=IwAR0sUz8N7MtT4z_oaK1AT0ADfBs6xaN0pI8OKc7UcIcEyIzl9q3KfI8czRc_aem_AXCb6j-ifosiNs7_5os8Toueas-lu4DEPfiNtzMYdm97tPYCG9X3Z_hVbLv9gxf6fv9cCQf6odNf6HRdEJvCfJhY
http://easters2023.calicotab.com/easters2023/motions/
https://easters2022.calicotab.com/easters2022/
https://onlineeasters2021.calicotab.com/onlineeasters2021/
https://wsdc2024.calicotab.com/wsdc2024/
"""

# https://docs.google.com/spreadsheets/d/1ryOKiMPPW7tP-lsvkR8xM6u1r4JmrSkj4UMitseckKM/pub?gid=0#
# http://tabbycat.idebate.net/
# https://tinyurl.com/tab
# https://docs.google.com/spreadsheets/u/0/d/1lralzhC-MUcXZsEOQ4i6b_Ep0nLzbU4b_kd1aIxgb1M/htmlview#
# https://docs.google.com/spreadsheets/d/1oBOCHbLLJAtekaVPP0tZldolpZjFY5-x1eoU-CDGRJU/edit?fbclid=IwAR0m9Y3hFxq0N7HUrQVws8htQRMvSLN-3iyP-GT0vy-brYZJr8mJsDSxXoI#gid=892844460

# https://cmude2024.calicotab.com/open/
# https://cmude2023.calicotab.com/cmude2023/
# https://cmude2022.calicotab.com/cmude2022/
# https://cmude2021.calicotab.com/cmudeecuador2021/
# https://cmudemadrid2020.calicotab.com/cmude2020/
# https://cmude2019.calicotab.com/cmude2019/
# https://cmude2018.calicotab.com/

In [31]:
calico_tabs = set()

for url in urls.split('\n'): 
    if 'calicotab' not in url:
        continue

    australs_pattern = re.compile(r'https?:\/\/(\w+)\.calicotab\.com\/(\w+)\/')
    match = re.match(australs_pattern, url)

    if match is None:
        print(f'[WARN] Could not parse url: {url}')
        continue

    subdomain = match.group(1)
    slug = match.group(2)

    calico_tabs.add((subdomain, slug))

    # print(subdomain, slug)

calico_tabs = list(calico_tabs)

In [32]:
calico_tabs[:5]

[('australs2021', '_'),
 ('edudrift', 'australs2025'),
 ('edudrift', 'australs2024'),
 ('eudc2022', 'eudc2022'),
 ('edudrift', 'abp2024')]

In [12]:
allowed_sides = ["og", "oo", "cg", "co"]

NULL_RESULTS = {
    "sum_og": None,
    "sum_oo": None,
    "sum_cg": None,
    "sum_co": None,

    "sum_og_og": None,
    "sum_oo_oo": None,
    "sum_cg_cg": None,
    "sum_co_co": None,

    "sum_og_oo": None,
    "sum_og_cg": None,
    "sum_og_co": None,

    "sum_oo_cg": None,
    "sum_oo_co": None,

    "sum_cg_co": None,

    "og_wins": None,
    "oo_wins": None,
    "cg_wins": None,
    "co_wins": None,

    "n": 0
}

async def retrieve_results(pairings_url, session):
    # FIXME: is this shallow updating?
    # set to default
    results = NULL_RESULTS.copy()
    for key in NULL_RESULTS.keys():
        results[key] = 0

    async with session.get(pairings_url) as pairings_response:
        pairings = await pairings_response.json()
        results["n"] = len(pairings)

        for pairing in pairings:
            try:
                ballots_url = pairing["_links"]["ballots"]
                ballots = None
                async with session.get(ballots_url) as ballots_response:
                    ballots = await ballots_response.json()

                if (
                    "detail" in ballots
                    and ballots["detail"]
                    == "Authentication credentials were not provided."
                ):
                    print(
                        f"[WARN] Behind auth for URL {pairings_url}. Skipping extracting ballots..."
                    )

                    # TODO: streamline by stopping to check ballots completely for tournaments if behind auth wall
                    return NULL_RESULTS

                assert len(ballots) == 1
                sheets = ballots[0]["result"]["sheets"]

                if len(sheets) > 1:
                    print(
                        f"[WARN] Multiple sheets at URL: {ballots_url}. Using only the first sheet."
                    )

                teams = sheets[0]["teams"]

                if teams[0]["side"] not in allowed_sides:
                    print(
                        f'[WARN] First team in sheet is not a valid BP position: {ballots_url}. Skipping extracting ballots...'
                    )

                    return NULL_RESULTS

                for i, team in enumerate(teams):
                    side = team["side"]
                    assert side in allowed_sides

                    points = team["points"]
                    win = team["win"]

                    assert (
                        points is not None or win is not None
                    ), f"Points and wins are both None for side: {side}"

                    if points is not None:
                        results["sum_" + side] += points
                    
                        for team2 in teams[i:]:
                            side2 = team2['side']
                            results["sum_" + side + "_" + side2] += team2['points'] * points

                    if win is True:
                        results[side + "_wins"] += 1

            except Exception as e:
                print("[ERROR] Failed to fetch ballots for pairing URL: ", pairings_url)
                print(f"Error: {e}")
    
    return results

In [21]:
supported_sides = ["og", "oo", "cg", "co"]

async def are_ballots_accessible(session, main_url):
    round_1_pairings_url = main_url + "/rounds/1/pairings"
    async with session.get(round_1_pairings_url) as round_1_pairings_response:
        round_1_pairings = await round_1_pairings_response.json()
        first_pairing = round_1_pairings[0]

        ballot_url = first_pairing["_links"]["ballots"]
        async with session.get(ballot_url) as ballot_response:
            ballots = await ballot_response.json()

            if (
                "detail" in ballots
                and ballots["detail"]
                == "Authentication credentials were not provided."
            ):
                # TODO: streamline by stopping to check ballots completely for tournaments if behind auth wall
                return False
            
            sheet = ballots[0]['result']['sheets'][0]

            for team in sheet['teams']:
                if team['side'] not in supported_sides:
                    return False
    
    return True

In [25]:
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await are_ballots_accessible(session, 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_')
    assert response == True
    response = await are_ballots_accessible(session, 'https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24')
    assert response == False
    response = await are_ballots_accessible(session, 'https://australs2021.calicotab.com/api/v1/tournaments/_')
    assert response == False

In [35]:
import asyncio 

async def retrieve_motions(subdomain, slug, session):
    rows = []
    
    main_url = f"https://{subdomain}.calicotab.com/api/v1/tournaments/{slug}"
    motions_url = f"{main_url}/motions"

    is_ballotable = await are_ballots_accessible(session, main_url)

    if is_ballotable:
        print(f'[WARN] Ballots not accessible or not supported for URL: {main_url}')

    results = NULL_RESULTS

    async with session.get(motions_url) as response:
        try: 
            assert response.status == 200, f"Failed to fetch {motions_url}: {response.status}"
        except: 
            print(f'[WARN] Failed to fetch API for url: {motions_url}')
            return []

        try: 
            motions = await response.json()
            for motion in motions:
                if len(motion['rounds']) <= 0: #skip unused (test) motions
                    print(f'[WARN] Skipping motion: {motion["text"]} from URL: {motions_url} because it has no rounds.')
                    continue

                rounds_parsed = {}

                rounds = motion['rounds']
                for i,round in enumerate(rounds): 
                    round_url = round['round']

                    async with session.get(round_url) as round_response:
                        round_json = await round_response.json()

                        try: 
                            rounds_parsed[f'round_{i+1}'] = round_json['name']
                            rounds_parsed[f'stage_{i+1}'] = round_json['stage']
                        except KeyError as e: 
                            print(f'[WARN] Skipping motion: {motion["text"]} from URL: {motions_url} because of no corresponding round exists.') #this can happen if tournament/round was deleted
                            continue

                        pairings_url = round_json['_links']['pairing']

                        if is_ballotable:
                            results = await retrieve_results(pairings_url, session)

                row = {
                    'Motion': motion['text'],
                    'Info Slide': motion['info_slide_plain'],
                    'Tournament': subdomain + ':' + slug,
                    **results,
                    **rounds_parsed,
                }

                rows.append(row)

        except Exception as e:
            print(f'[ERROR] Failed to fetch motions for URL: {motions_url}')
            print(f'Error: {e.with_traceback()}')
            return rows

    return rows

In [36]:
#check
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await retrieve_motions('hwsrr2025', '_', session)
print(response)

[WARN] Ballots not accessible or not supported for URL: https://hwsrr2025.calicotab.com/api/v1/tournaments/_
[{'Motion': 'This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms.', 'Info Slide': '', 'Tournament': 'hwsrr2025:_', 'sum_og': 12, 'sum_oo': 3, 'sum_cg': 4, 'sum_co': 5, 'sum_og_og': 36, 'sum_oo_oo': 5, 'sum_cg_cg': 8, 'sum_co_co': 7, 'sum_og_oo': 9, 'sum_og_cg': 12, 'sum_og_co': 15, 'sum_oo_cg': 0, 'sum_oo_co': 4, 'sum_cg_co': 4, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 0, 'co_wins': 0, 'n': 4, 'round_1': 'Round 1-A', 'stage_1': 'P', 'round_2': 'Round 1-B', 'stage_2': 'P'}, {'Motion': 'This house regrets the Indian Premier League.', 'Info Slide': 'The Indian Premier League (IPL) is a domestic cricket league in India. Since\nits inception in 2007, it has grown to become the largest cricket league in\nthe world, attracting sponsorship that exceeds that of most national teams.\n\nTraditionally, cricket competition has been dominated by international events\nand national teams touring other countries, and has involved games lasting\neither five days or one day. The IPL popularized large-scale domestic cricket\nleagues, and is played in a shorter, three-hour format of cricket called\nTwenty20 (T20). Teams are allowed up to 4 international (non-Indian) players\nin their teams. Additionally, the IPL usually lasts 3-4 months, taking up a\nsignificant portion of the annual cricket calendar.', 'Tournament': 'hwsrr2025:_', 'sum_og': 2, 'sum_oo': 9, 'sum_cg': 3, 'sum_co': 10, 'sum_og_og': 2, 'sum_oo_oo': 23, 'sum_cg_cg': 5, 'sum_co_co': 26, 'sum_og_oo': 5, 'sum_og_cg': 0, 'sum_og_co': 5, 'sum_oo_cg': 5, 'sum_oo_co': 21, 'sum_cg_co': 8, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 0, 'co_wins': 0, 'n': 4, 'round_1': 'Round 2-A', 'stage_1': 'P', 'round_2': 'Round 2-B', 'stage_2': 'P'}, {'Motion': 'This house believes that breaking up large meat companies is in the interests of animal welfare.', 'Info Slide': '', 'Tournament': 'hwsrr2025:_', 'sum_og': 6, 'sum_oo': 7, 'sum_cg': 5, 'sum_co': 6, 'sum_og_og': 10, 'sum_oo_oo': 15, 'sum_cg_cg': 13, 'sum_co_co': 18, 'sum_og_oo': 9, 'sum_og_cg': 8, 'sum_og_co': 9, 'sum_oo_cg': 9, 'sum_oo_co': 9, 'sum_cg_co': 0, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 0, 'co_wins': 0, 'n': 4, 'round_1': 'Round 3-A', 'stage_1': 'P', 'round_2': 'Round 3-B', 'stage_2': 'P'}, {'Motion': 'This house prefers a world where genius only develops after adulthood (so that there are no child prodigies).', 'Info Slide': '', 'Tournament': 'hwsrr2025:_', 'sum_og': 8, 'sum_oo': 7, 'sum_cg': 5, 'sum_co': 4, 'sum_og_og': 22, 'sum_oo_oo': 17, 'sum_cg_cg': 13, 'sum_co_co': 4, 'sum_og_oo': 12, 'sum_og_cg': 6, 'sum_og_co': 8, 'sum_oo_cg': 6, 'sum_oo_co': 7, 'sum_cg_co': 5, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 0, 'co_wins': 0, 'n': 4, 'round_1': 'Round 4-A', 'stage_1': 'P', 'round_2': 'Round 4-B', 'stage_2': 'P'}, {'Motion': 'This house believes that East African national governments should prioritize investments in agriculture (e.g., irrigation, R&D, and inputs like fertilizer) over accelerating industrialization (e.g., building infrastructure, export promotion).', 'Info Slide': '', 'Tournament': 'hwsrr2025:_', 'sum_og': 12, 'sum_oo': 3, 'sum_cg': 3, 'sum_co': 6, 'sum_og_og': 36, 'sum_oo_oo': 3, 'sum_cg_cg': 5, 'sum_co_co': 12, 'sum_og_oo': 9, 'sum_og_cg': 9, 'sum_og_co': 18, 'sum_oo_cg': 2, 'sum_oo_co': 4, 'sum_cg_co': 2, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 0, 'co_wins': 0, 'n': 4, 'round_1': 'Round 5-A', 'stage_1': 'P', 'round_2': 'Round 5-B', 'stage_2': 'P'}, {'Motion': 'Assuming a peaceful and democratic transition, this house supports the United States of America being separated into several, more politically-homogeneous, sovereign states.', 'Info Slide': '', 'Tournament': 'hwsrr2025:_', 'sum_og': 0, 'sum_oo': 0, 'sum_cg': 0, 'sum_co': 0, 'sum_og_og': 0, 'sum_oo_oo': 0, 'sum_cg_cg': 0, 'sum_co_co': 0, 'sum_og_oo': 0, 'sum_og_cg': 0, 'sum_og_co': 0, 'sum_oo_cg': 0, 'sum_oo_co': 0, 'sum_cg_co': 0, 'og_wins': 0, 'oo_wins': 0, 'cg_wins': 1, 'co_wins': 0, 'n': 1, 'round_1': 'Grand Final', 'stage_1': 'E'}]

In [37]:
import aiohttp

rows = []

async with aiohttp.ClientSession() as session:
    batch_n = 10
    n = len(calico_tabs)

    print(f"Starting data fetching for {n} tournaments.")

    for i in tqdm(range(0, len(calico_tabs), batch_n)): 
        responses = await asyncio.gather(*(retrieve_motions(subdomain, slug, session) for subdomain, slug in list(reversed(calico_tabs))[i:i+batch_n]))
        batch = [m for row in responses for m in row] #flatten
        rows.extend(batch)

Starting data fetching for 50 tournaments.

  0%|          | 0/5 [00:00<?, ?it/s]

[WARN] Ballots not accessible or not supported for URL: https://midp.calicotab.com/api/v1/tournaments/mabp2023
[WARN] Ballots not accessible or not supported for URL: https://edudrift.calicotab.com/api/v1/tournaments/neadc2023
[WARN] Ballots not accessible or not supported for URL: https://usudc2022.calicotab.com/api/v1/tournaments/usudc2022
[WARN] Ballots not accessible or not supported for URL: https://neadc2024.calicotab.com/api/v1/tournaments/neadc2024
[WARN] Ballots not accessible or not supported for URL: https://eudc2024.calicotab.com/api/v1/tournaments/_
[WARN] Ballots not accessible or not supported for URL: https://naudc2023.calicotab.com/api/v1/tournaments/naudc2023
[WARN] Ballots not accessible or not supported for URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[WARN] Skipping motion: This House believes that YouTube should never demonetise a video. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House would allow foreign legal actions against military organisations in a domestic court (e.g. a Mexican citizen suing a USA military organisation in a USA court for an act committed in Mexico). from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House regrets the narrative that everything happens for a reason. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House believes that disability activist groups should support a narrative of people with different abilities rather than disabilities (e.g. no longer investing resources into researching a cure to deafness, and instead actively encouraging society to adapt with people who are deaf by learning sign language, making closed captions mandatory etc.) from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House believes that the Australian Government should redirect money from foster care programs to adoption programs (e.g. lifting restrictions on adoption, promoting adoption, etc.). from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Skipping motion: This House supports the emergence of Chinese led/backed/created multilateral institutions like the AIIB, Shanghai Cooperative, and the NDB. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.

 20%|██        | 1/5 [02:46<11:05, 166.39s/it]

[WARN] Skipping motion: This House would ban the development and use of human augmentation technology (e.g bionic limbs, implanted chips) for non-restorative purposes. from URL: https://wudc2018.calicotab.com/api/v1/tournaments/wudc2018/motions because of no corresponding round exists.
[WARN] Ballots not accessible or not supported for URL: https://mace.calicotab.com/api/v1/tournaments/sanudc2021
[WARN] Ballots not accessible or not supported for URL: https://usudc2025.calicotab.com/api/v1/tournaments/_
[WARN] Ballots not accessible or not supported for URL: https://usudc2023.calicotab.com/api/v1/tournaments/usudc2023
[WARN] Ballots not accessible or not supported for URL: https://wudc2025.calicotab.com/api/v1/tournaments/open
[WARN] Ballots not accessible or not supported for URL: https://naudc2024.calicotab.com/api/v1/tournaments/naudc2024
[WARN] Ballots not accessible or not supported for URL: https://wudc2022.calicotab.com/api/v1/tournaments/wudc
[WARN] Skipping motion: QWERTY from URL: https://wudc2022.calicotab.com/api/v1/tournaments/wudc/motions because it has no rounds.
[WARN] Ballots not accessible or not supported for URL: https://wudc2014.calicotab.com/api/v1/tournaments/wudc2014
[WARN] Skipping motion: This house, as the Democratic Party in the United States, would swing at every pitch rather than pick battles against the Republican Party from URL: https://usudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.

 40%|████      | 2/5 [06:00<09:07, 182.60s/it]

[WARN] Ballots not accessible or not supported for URL: https://hwsrr2023.calicotab.com/api/v1/tournaments/hwsrr2023
[WARN] Ballots not accessible or not supported for URL: https://paudc2022.calicotab.com/api/v1/tournaments/PAUDC2022
[WARN] Ballots not accessible or not supported for URL: https://wudc2023.calicotab.com/api/v1/tournaments/wudc

 60%|██████    | 3/5 [08:17<05:23, 161.87s/it]

[WARN] Ballots not accessible or not supported for URL: https://hwsrr2025.calicotab.com/api/v1/tournaments/_
[WARN] Ballots not accessible or not supported for URL: https://edudriftbackup.calicotab.com/api/v1/tournaments/abp2022
[WARN] Ballots not accessible or not supported for URL: https://neadc.calicotab.com/api/v1/tournaments/neadc
[WARN] Ballots not accessible or not supported for URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022
[WARN] Ballots not accessible or not supported for URL: https://wudc2024.calicotab.com/api/v1/tournaments/wudc
[WARN] Ballots not accessible or not supported for URL: https://wudc2020.calicotab.com/api/v1/tournaments/wudc2020
[WARN] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[WARN] Skipping motion: This House would abolish laws against price-gouging. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This House would abolish laws against price-gouging. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: THO the practice of vote buying. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: THO the practice of vote buying. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.
[WARN] Skipping motion: This House believes that governments should set up a department dedicated to producing and submitting ‘Sokal papers’ to academic journals, removing academics that admit Sokal papers and shutting down faculties that systemically admit ‘Sokal papers’. from URL: https://neadc2022.calicotab.com/api/v1/tournaments/2022/motions because it has no rounds.

 80%|████████  | 4/5 [11:22<02:51, 171.18s/it]

[WARN] Ballots not accessible or not supported for URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024
[WARN] Ballots not accessible or not supported for URL: https://eudc2022.calicotab.com/api/v1/tournaments/eudc2022
[WARN] Ballots not accessible or not supported for URL: https://eudc2023.calicotab.com/api/v1/tournaments/_
[WARN] Skipping motion: That renters of public housing should be allowed to purchase that housing at a discounted rate. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: That, in cities facing housing crises, we would remove all heritage protections in building codes. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: That, in states with a low fertility rate, we prefer policies with a familising effect rather than a de-familising effect. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[WARN] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.

100%|██████████| 5/5 [12:48<00:00, 153.71s/it]

In [39]:
df = pd.DataFrame(rows)
df

,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,...,sum_cg_co,og_wins,oo_wins,cg_wins,co_wins,n,round_1,stage_1,round_2,stage_2
0,THBT it is in the interest of resource-rich na...,,eudc2024:_,90.0,69.0,64.0,53.0,224.0,153.0,142.0,...,60.0,0.0,0.0,0.0,0.0,46,Round 5,P,NaN,NaN
1,THO the depiction of tragedies through comedy ...,,eudc2024:_,61.0,100.0,36.0,79.0,119.0,260.0,68.0,...,43.0,0.0,0.0,0.0,0.0,46,Round 1,P,NaN,NaN
2,THBT devolution has strengthened the Scottish ...,Devolution was the process of providing a regi...,eudc2024:_,87.0,79.0,50.0,60.0,207.0,187.0,106.0,...,44.0,0.0,0.0,0.0,0.0,46,Round 2,P,NaN,NaN
3,THBT left wing criticism of liberal NGOs for f...,"Recently, there has been a rise in left-wing c...",eudc2024:_,97.0,70.0,60.0,49.0,245.0,156.0,132.0,...,35.0,0.0,0.0,0.0,0.0,46,Round 6,P,NaN,NaN
4,THBT Donald Trump winning the 2024 US Presiden...,,eudc2024:_,77.0,94.0,56.0,49.0,185.0,236.0,122.0,...,41.0,0.0,0.0,0.0,0.0,46,Round 8,P,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1073,B: That we prefer mandatory community service ...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,ESL Finals,E,NaN,NaN
1074,C: That people who have suffered acute amnesia...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,ESL Finals,E,NaN,NaN
1075,"A: That, as a person who emigrated from a poor...",,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,Grand Final,E,NaN,NaN
1076,"B: That, in countries with a history of ethnic...",,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,Grand Final,E,NaN,NaN
1077,C: That we should oppose the promotion and mar...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,Grand Final,E,NaN,NaN

## Scraping from Tabbycat 

DEPRECATED!! Only works for WSDC.

In [33]:
# calico_tabs = [
#     ('nsdc25', 'NordicSDC2025'),
#     ('eurosdc25', 'eurosdc-25'),
#     # ('esdc', 'esdc2025'),
#     ('argument', 'eco2025'),
#     ('argument', 'ECO2024'),
#     ('nordics2023', 'nordics2023')
# ]

In [34]:
def parse_motion(div): 
    """
    Given a motion top-level div, parse out the relevant details.
    """
    round = div.find('span', class_="badge").get_text(strip=True)
    motion = div.find('h4').find(string=True, recursive=False).strip()

    info_slide = div.find(string=re.compile("View Info Slide"))
    info_slide_text = None

    if info_slide is not None:
        info_slide_text = info_slide.find_next('div', class_='modal-body').get_text(strip=True)

    # regex match the wins for prop and opp
    text = div.get_text()

    re_prop = re.compile(r"(\d+) (Prop|Gov) win")
    re_opp = re.compile(r"(\d+) Opp win")

    prop_wins = re.findall(re_prop, text)[0][0]
    opp_wins = re.findall(re_opp, text)[0][0]

    balance = div.find(string=re.compile('balance')).get_text(strip=True)

    return motion, round, info_slide_text, prop_wins, opp_wins, balance

In [35]:
data = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    "Prop wins": [],
    "Opp wins": [],
    "Balance": [],
}

for subdomain, slug in calico_tabs:
    calico_url = f"https://{subdomain}.calicotab.com/{slug}"

    motions_suburl = f"motions/statistics"
    motions_url = f"{calico_url}/{motions_suburl}"

    response = requests.get(motions_url) 
    try: 
        assert response.status_code == 200, f"Failed to fetch {motions_url}: {response.status_code}"
    except: 
        continue

    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    try:
        motion_divs = soup.find_all('div', class_="list-group mt-3")
        print(f"Found {len(motion_divs)} motions from {slug}.")

        for start in tqdm(range(len(motion_divs))):
            div = motion_divs[start]
            motion, round, info_slide_text, prop_wins, opp_wins, balance = parse_motion(div)
            

            data["Motion"].append(motion)
            data["Round"].append(round)
            data["Info Slide"].append(info_slide_text)
            data["Prop wins"].append(int(prop_wins))
            data["Opp wins"].append(int(opp_wins))
            data["Balance"].append(balance)
            data["Tournament"].append(slug)
    except: 
        print(f'[WARN] could not parse motions for url: {calico_url}')

Found 11 motions from _.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2025.calicotab.com/_

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2025.calicotab.com/_

Found 12 motions from paudcK24.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2024.calicotab.com/paudcK24

Found 12 motions from abp2024.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/abp2024

Found 11 motions from neadc2024.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2024.calicotab.com/neadc2024

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2024.calicotab.com/_

Found 14 motions from naudc2024.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2024.calicotab.com/naudc2024

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2024.calicotab.com/wudc

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 13 motions from usudc2023.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2023.calicotab.com/usudc2023

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 12 motions from mabp2023.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://midp.calicotab.com/mabp2023

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2023.calicotab.com/_

Found 11 motions from hwsrr2023.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2023.calicotab.com/hwsrr2023

Found 17 motions from wudc.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2023.calicotab.com/wudc

Found 13 motions from PAUDC2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2022.calicotab.com/PAUDC2022

Found 12 motions from abp2022.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudriftbackup.calicotab.com/abp2022

Found 13 motions from usudc2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2022.calicotab.com/usudc2022

Found 15 motions from 2022.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2022.calicotab.com/2022

Found 14 motions from eudc2022.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2022.calicotab.com/eudc2022

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2022.calicotab.com/wudc

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2021.calicotab.com/_

Found 13 motions from neadc.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc.calicotab.com/neadc

Found 17 motions from abp2021.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2021.calicotab.com/abp2021

Found 8 motions from sanudc2021.

  0%|          | 0/8 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/sanudc2021

Found 13 motions from paudc2021.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/paudc2021

Found 14 motions from eudc2021.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2021.calicotab.com/eudc2021

Found 19 motions from 2021.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudckorea.calicotab.com/2021

Found 13 motions from abp2020.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2020.calicotab.com/abp2020

Found 16 motions from eudc2020.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2020.calicotab.com/eudc2020

Found 19 motions from wudc2020.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2020.calicotab.com/wudc2020

Found 14 motions from usudc2020.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2020.calicotab.com/usudc2020

Found 19 motions from wudc2018.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2018.calicotab.com/wudc2018

Found 19 motions from wudc2014.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2014.calicotab.com/wudc2014

KeyboardInterrupt:

In [37]:
df1 = pd.DataFrame(data)
df1.tail()

Empty DataFrame
Columns: [Tournament, Motion, Round, Info Slide, Prop wins, Opp wins, Balance]
Index: []

## Parse WSDC motions from .txt on GitHub
https://github.com/tokyodebate/motions/blob/main/International/WSDC.txt

In [56]:
import requests

url = 'https://raw.githubusercontent.com/tokyodebate/motions/refs/heads/main/International/WSDC.txt'

response = requests.get(url)
wsdc_motions_raw = response.text

In [57]:
def count_tabs(line: str):
    """
    Count the number of tabs in a line.
    """
    return line.count('\t')

In [58]:
data2 = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    # "Prop wins": [],
    # "Opp wins": [],
    # "Balance": [],
}

def parse_wsdc_motions():
    lines = wsdc_motions_raw.split('\n')
    lines = [line.strip('\n') for line in lines]
    lines = lines[1:] # Skip the header

    tournament = None
    round = None

    for i in range(len(lines)):
        curr = lines[i]

        if count_tabs(curr) == 1: 
            tournament = curr.strip()
        elif count_tabs(curr) == 2:
            round = curr.strip()
        elif count_tabs(curr) == 3:
            next_line = lines[i+1] if i+1 < len(lines) else None
            info_text = next_line.strip() if next_line and count_tabs(next_line) == 4 else None

            motion = curr.strip()   
            data2["Motion"].append(motion)
            data2["Round"].append(round)
            data2["Info Slide"].append(info_text)
            data2["Tournament"].append(tournament)

        else:
            continue

parse_wsdc_motions()

In [59]:
df2 = pd.DataFrame(data2)
df2.value_counts('Tournament')

Tournament
Netherlands WSDC 2022                                                           21
WSDC Mexico 2020                                                                20
24th World Schools Debating Championships 2012, South Africa                    13
21st World Schools Debating Championships 2009 in Athens, Greece                13
Vietnam WSDC 2023                                                               13
30th World Schools Debating Championships 2018, Croatia and Slovenia            13
29th World Schools Debating Championships 2017, Indonesia                       13
28th World Schools Debating Championships 2016, Germany                         13
27th World Schools Debating Championships 2015, Singapore                       13
WSDC Thailand 2019                                                              13
16th World Schools Debating Championships 2004 in Stuttgart, Germany            13
15th World Schools Debating Championships 2003 in Lima, Peru                    13
19th World Schools Debating Championships 2007 in Seoul, South Korea            13
17th World Schools Debating Championships 2005 in Calgary, Canada               13
18th World Schools Debating Championships 2006 in Cardiff, Wales                12
13th World Schools Debating Championships 2001 in Johannesburg, South Africa    12
14th World Schools Debating Championships 2002 in Singapore                     12
20th World Schools Debating Championships 2008 in Washington DC, USA            12
25th World Schools Debating Championships 2013, Turkey                          12
11th World Schools Debating Championships 1999 in London, England               12
23rd World Schools Debating Championships 2011, Dundee                          12
22nd World Schools Debating Championships 2010, Doha                            12
26th World Schools Debating Championships 2014, Thailand                        11
WSDC Macau Online 2021                                                          11
6th World Schools Debating Championships 1994 in New Zealand                     9
9th World Schools Debating Championships 1997 in Bermuda                         5
10th World Schools Debating Championships 1998 in Jerusalem, Israel              5
12th World Schools Debating Championships 2000 in Pittsburgh, PA, USA            4
Name: count, dtype: int64

In [60]:
df = pd.concat([df, df2], ignore_index=True)

,Motion,Info Slide,Tournament,Round
0,This house prefers that progressive journalist...,,hwsrr2025:_,NaN
1,This house regrets the Indian Premier League.,The Indian Premier League (IPL) is a domestic ...,hwsrr2025:_,NaN
2,This house believes that breaking up large mea...,,hwsrr2025:_,NaN
3,This house prefers a world where genius only d...,,hwsrr2025:_,NaN
4,This house believes that East African national...,,hwsrr2025:_,NaN

## Data polishing

In [40]:
df['Motion'] = df['Motion'].astype("string")

### Duplicates

In [41]:
# check for duplicates on motion and round 
# motions can be duplicated (if same is used in two different rounds)
duplicates = df[df.duplicated(subset=['Motion'], keep=False)]

if len(duplicates) > 0:
    raise ValueError(f"Found {len(duplicates)} duplicates in the data. Please check the data for inconsistencies.")

ValueError: Found 36 duplicates in the data. Please check the data for inconsistencies.

### Tournament year

In [42]:
def get_year(tournament: str):
    pattern = re.compile(r'\d{4}')
    match = pattern.search(tournament)

    if tournament == 'eurosdc-25':
        return 2025

    if match:
        return int(match.group(0))
    else:
        return None

df['Year'] = df['Tournament'].apply(get_year)
df.value_counts('Year')

Year
2022.0    207
2024.0    173
2020.0    170
2021.0    165
2023.0    161
2025.0    144
2018.0     26
2014.0     19
Name: count, dtype: int64

### Motion types

In [43]:
full_to_abbr = {
    'BT': "believes",
    'B': "believes",
    "S": "supports",
    "O": "opposes",
    "W": "would",
    "P": "prefers",
    "R": "regrets",
}

all_types = set(full_to_abbr.values()) # *most types (this is used to fix up actor motions)
all_types

{'believes', 'opposes', 'prefers', 'regrets', 'supports', 'would'}

In [44]:
def fix_motions(motion: str):
    australs_pattern = re.compile(r'(A|B|C)\W ') #australs bs that adds A, B, C motion types

    if match := re.match(australs_pattern, motion): 
        motion = motion[match.span()[1]:]
    
    # this fixes actor motions without commas
    # e.g. "This House as the environmental movement would support the use of extremist tactics"
    # https://regex101.com/r/XB1k1w/1
    actor_pattern = re.compile(r'(?:This (h|H)ouse?|TH)(?P<actor> as( \w+)+)' + f" ({'|'.join(all_types)})")
    if match := re.match(actor_pattern, motion):
        actor = match.group('actor')
        motion = motion.replace(actor, ',' + actor + ',')

    if motion.startswith('That'):
        motion = 'This House believes that' + motion[4:]
    
    return motion

df['Motion'] = df['Motion'].apply(fix_motions)

In [45]:
def extract_motion_header(motion: str): 
    # https://regex101.com/r/XB1k1w/1
    pattern = re.compile(r"(?:(T|t)his (h|H)ouse?|TH)[ ,]?(?:,.*?, )?(?P<type>\w+)\s?")

    match = re.search(pattern, motion)
    return match

In [46]:
def get_motion_type(motion: str): 
    match = extract_motion_header(motion)

    if match: 
        motion_type = match.group('type')
        all_caps = all(map(str.isupper, motion_type))

        if all_caps:
            return f'{full_to_abbr[motion_type]}'
        else: 
            return f'{motion_type.lower()}'
    else:
        print(f"Could not determine motion type for: {motion}")

df["Motion Type"] = df["Motion"].apply(get_motion_type)

Could not determine motion type for:  That we support memory laws
Could not determine motion type for:  That the US should attempt to aggressively contain China's capacity to build AI systems (e.g. by limiting China's ability to skill and retain computer scientists, attract US capital into Chinese AI companies, or access parts needed to build AI systems where the US has significant market share, such as semiconductors).
Could not determine motion type for: Assuming the technology exists, that it is immoral to create simulated high-fidelity alternate universes.
Could not determine motion type for: Assuming an initial agreement is possible, that it is the interest of DA to include EFF in its (DA's) coalition for the 2024 election. [coalition]
Could not determine motion type for:  That we regret the rise of retail investment.

## Vectorization
NB! This step requires access to a Google Cloud project with billing enabled. If desired, you can sign up for a $300 free trial that will be plenty to cover the costs of vectorization.

Alternatively, all vector space information is already included in the attached `motions.csv` file.

In [62]:
%pip install --upgrade -q google-genai vertexai dotenv

WARNING: google-cloud-aiplatform 1.71.1 does not provide the extra 'all'
Note: you may need to restart the kernel to use updated packages.

In [67]:
def clean_motion(motion: str):
    match = extract_motion_header(motion)

    if match is None:
        print(f'[WARN] No header found for motion: {motion}')
        return motion

    header_end = match.span()[1]
    chopped = motion[header_end:].lower()

    filler_words = ['that', 'the', 'it', 'is']

    flag = True
    while flag: 
        flag = False

        for w in filler_words: 
            if chopped.startswith(w): 
                chopped = chopped.replace(w, '')
                flag=True
    
    punctuations = ['.', ',' ';']
    for p in punctuations: 
        chopped = chopped.replace(p, '')
    return chopped

In [68]:
df['Motion (cleaned)'] = df['Motion'].map(clean_motion)
df.head()

[WARN] No header found for motion:  That we support memory laws
[WARN] No header found for motion:  That the US should attempt to aggressively contain China's capacity to build AI systems (e.g. by limiting China's ability to skill and retain computer scientists, attract US capital into Chinese AI companies, or access parts needed to build AI systems where the US has significant market share, such as semiconductors).
[WARN] No header found for motion: Assuming the technology exists, that it is immoral to create simulated high-fidelity alternate universes.
[WARN] No header found for motion: Assuming an initial agreement is possible, that it is the interest of DA to include EFF in its (DA's) coalition for the 2024 election. [coalition]
[WARN] No header found for motion:  That we regret the rise of retail investment.

,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,...,cg_wins,co_wins,n,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned)
0,THBT it is in the interest of resource-rich na...,,eudc2024:_,90.0,69.0,64.0,53.0,224.0,153.0,142.0,...,0.0,0.0,46,Round 5,P,NaN,NaN,2024.0,believes,is in the interest of resource-rich nations (...
1,THO the depiction of tragedies through comedy ...,,eudc2024:_,61.0,100.0,36.0,79.0,119.0,260.0,68.0,...,0.0,0.0,46,Round 1,P,NaN,NaN,2024.0,opposes,depiction of tragedies through comedy eg life...
2,THBT devolution has strengthened the Scottish ...,Devolution was the process of providing a regi...,eudc2024:_,87.0,79.0,50.0,60.0,207.0,187.0,106.0,...,0.0,0.0,46,Round 2,P,NaN,NaN,2024.0,believes,devolution has strengthened the scottish indep...
3,THBT left wing criticism of liberal NGOs for f...,"Recently, there has been a rise in left-wing c...",eudc2024:_,97.0,70.0,60.0,49.0,245.0,156.0,132.0,...,0.0,0.0,46,Round 6,P,NaN,NaN,2024.0,believes,left wing criticism of liberal ngos for failin...
4,THBT Donald Trump winning the 2024 US Presiden...,,eudc2024:_,77.0,94.0,56.0,49.0,185.0,236.0,122.0,...,0.0,0.0,46,Round 8,P,NaN,NaN,2024.0,believes,donald trump winning the 2024 us presidential ...

In [ ]:
import vertexai
import os

vertexai.init(project=os.environ['VERTEXAI_PROJECT_ID'])

In [134]:
from vertexai.language_models import TextEmbeddingModel
from typing import Optional

def embed(texts, output_dims: Optional[int] = None):
  model_id = 'text-embedding-005'
  # model_id = 'gemini-embedding-001'
  model = TextEmbeddingModel.from_pretrained(model_id)
  embeddings = model.get_embeddings(texts, output_dimensionality=output_dims)

  return embeddings

In [140]:
# vertexai allows a max of 250 input elements at once
chunk_size = 100

for start in tqdm(range(0, len(df), chunk_size)):
    end = start + chunk_size
    motion_strings = df['Motion (cleaned)'].values[start:end]

    embeddings = embed(list(motion_strings))
    df.loc[start:end-1, 'Embedding'] = embeddings #NB! pandas uses an inclusive end index (hence the end-1)

    # if start > 100:
    #     break

 18%|█▊        | 2/11 [00:42<03:12, 21.34s/it]

KeyboardInterrupt:

## Save data locally

In [149]:
pd.set_option('display.max_colwidth', None)
df.sample(5)[['Motion', 'Info Slide', 'Tournament', 'Year', 'round_1', 'Motion Type']]

,Motion,Info Slide,Tournament,Year,round_1,Motion Type
763,This House prefers the 5 City Model over prioritising growing Ho Chi Minh and Hanoi.,"The Vietnam 5 City Model is a strategic urban development initiative focusing on the development of five key cities by 2035: Hanoi, Ho Chi Minh City, Da Nang, Hai Phong, and Can Tho. Each city is developed based on its unique strengths: Hanoi for political and cultural significance, Ho Chi Minh City as the economic and industrial hub, Da Nang for tourism and services, Hai Phong for maritime trade, and Can Tho for agriculture.",wudc2024:wudc,2024.0,Round 7,prefers
972,This House believes that the Philippines should disallow split-ticket voting.,"Currently, the Philippines allows 'split-ticket' voting where the President\nand Vice President are elected separately, rather than together (such as in\nthe United States and Indonesia). Since the 1987 Constitution of the\nPhilippines, only two elections have resulted in the President and Vice\nPresidents being elected from the same political party: in 2004, President\nGloria Macapagal-Arroyo with running mate VP Noli De Castro, and in 2022,\nPresident Bongbong Marcos with running mate VP Sara Duterte. Traditionally,\nVice Presidents in the Philippines are appointed as secretaries of departments\n(e.g. Department of Social Welfare and Development, Education, and\nAgriculture) under the executive.",edudrift:australs2024,2024.0,Round 4,believes
416,"This House believes that we regret the prevalence of malevolent AI in popular culture (eg-Skynet in Terminator, Ultron in the Avengers, etc)",,australs2022:australs2022,2022.0,Open Grand Final,believes
645,This house believes that post-colonial nations should prioritise narratives of religion over quantitative outcomes when attempting to implement reconstruction policy.,,neadc:neadc,NaN,Round 3,believes
643,"Assuming feasibility, this house would pass all major legislation through direct referendum.",,neadc:neadc,NaN,Round 1,would

In [139]:
df.tail()

,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,...,co_wins,n,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
1073,This House believes that we prefer mandatory c...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,ESL Finals,E,NaN,NaN,2021.0,believes,we prefer mandatory community service to be t...,"[-0.01874217391014099, 0.020632775500416756, 0..."
1074,This House believes that people who have suffe...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,ESL Finals,E,NaN,NaN,2021.0,believes,people who have suffered acute amnesia should...,"[-0.06175243854522705, -0.0033194844145327806,..."
1075,"This House believes that, as a person who emig...",,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,Grand Final,E,NaN,NaN,2021.0,believes,", as a person who emigrated from a poor nation...","[-0.02416081912815571, 0.02197565697133541, 0...."
1076,"This House believes that, in countries with a ...",,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,Grand Final,E,NaN,NaN,2021.0,believes,", in countries with a history of ethnic tensio...","[-0.02346249297261238, -0.03430898115038872, 0..."
1077,This House believes that we should oppose the ...,,australs2021:_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,Grand Final,E,NaN,NaN,2021.0,believes,we should oppose the promotion and marketing ...,"[-0.029969092458486557, -0.04652056843042374, ..."

In [136]:
#TODO: maybe better to store each value in its own column? or just use a diff file format specifically for floats
from vertexai.language_models import TextEmbedding

df['Embedding'] = df['Embedding'].map(lambda e: e.values if isinstance(e, TextEmbedding) else None) #get only the numbers

In [137]:
import os

data_dir = 'raw'

os.makedirs(data_dir, exist_ok=True)
df.to_csv(os.path.join(data_dir, 'motions_bp.csv'))