In [18]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from tqdm import tqdm

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

## Load motions from calico tabs

In [ ]:
#source: https://docs.google.com/spreadsheets/d/167zz_2rI83PXN_oZkIG5fuvVuKxnVtuNL6v0F_8hKJE/edit?gid=0#gid=0

urls = """https://ashokapd.calicotab.com/ashokapd2025/
https://ado2025.calicotab.com/ado2025/
https://bitspilanipd.calicotab.com/niqash-22/
https://cbs.calicotab.com/cbspd23/
https://cbspd2025.calicotab.com/cbspd2025/
https://muntazar2024.calicotab.com/muntazar24/
https://cupd2025.calicotab.com/cupd25/
https://cvspd22.calicotab.com/cvspd24/
https://mukhtalif2023.calicotab.com/mukhtalif2023/
https://cvspd22.calicotab.com/cvspd23/
https://dope2024.calicotab.com/dope2024/
https://dope2025.calicotab.com/dope2025/
https://dilimanap2025.calicotab.com/dilimanap2025/
https://dtusummers2023.calicotab.com/dtusummers2023/
https://dtusummers2025.calicotab.com/dtusummers2025/
https://kmcpresentsftd.calicotab.com/ftd44/
https://gambit25.calicotab.com/gambit/
https://hpd.calicotab.com/hpd2024/
https://iitbhupd.calicotab.com/iitbhupd2025/
https://iitdebsoc.calicotab.com/debutant24/
https://iitpd2023.calicotab.com/iitpd2023/
https://iitpd2025.calicotab.com/iitpd2025/
https://axiom23.calicotab.com/axiom2024/
https://pratijja17.calicotab.com/pratijja/
https://kpp2025.calicotab.com/kamaligprepidc25/
https://kmcpresentsftd.calicotab.com/KMCpresentsFTD/
https://anvaya.calicotab.com/anvayaapd25/
https://mnmpd2023.calicotab.com/mnmpd2024/
https://nrmd.calicotab.com/nrmd2023/
https://nsmpd23.calicotab.com/nsmpd23/
https://nitdpd.calicotab.com/nitdpd24/
https://nlujpd2023.calicotab.com/nlujpd2023/
https://nujspd2024.calicotab.com/nujdpd2024/
https://uietpd.calicotab.com/UIETPD/
https://phdo2025.calicotab.com/phdo2025/
https://pidc24.calicotab.com/transformtradition/
https://hindu.calicotab.com/Premchand2025/
https://trivium2024.calicotab.com/trivium2024/
https://rahat2021.calicotab.com/rahat2024/
https://rmlpd12.calicotab.com/rmlpd12/
https://agahi.calicotab.com/agahix/
https://rmlpd2023.calicotab.com/rmlpd2023/
https://symcharcha2023.calicotab.com/symcharcha23/
https://speakup10.calicotab.com/speakup/
https://speakup13.calicotab.com/speakup13/
https://shivajienglishpd.calicotab.com/shivaji2025/
https://gambit23.calicotab.com/gambit23/
https://srcc.calicotab.com/srdf2022/
https://srcc.calicotab.com/srdf2023/
https://taydo2022.calicotab.com/tap2025/
https://bduadc2020.calicotab.com/uadc2020/
https://edudriftbackup.calicotab.com/uadc2021/
http://malaysiauadc2022.calicotab.com/malaysiauadc2022/
https://malaysiauadc2023.calicotab.com/uadc2023/
https://uadc2024.au-tab.app/uadc2024/
https://edudrift.calicotab.com/uadc2025/
https://sxc.calicotab.com/xdf2023/
https://yec2024debates.calicotab.com/yec2024debates/
https://13zdo.calicotab.com/13thzdo/
https://ikhtilafpd23.calicotab.com/ikhtilaf2025/
https://australs2015.calicotab.com/australs2015/
https://australs2016.calicotab.com/australs2016/
https://australs2019.calicotab.com/australs2019/
https://australs2020.calicotab.com/australs2020/
https://australs2021.calicotab.com/_/
http://australs2022.calicotab.com/australs2022/
https://krabiaustrals2023.calicotab.com/australs2023/
https://edudrift.calicotab.com/australs2024/
https://edudrift.calicotab.com/australs2025/
https://easters2022.calicotab.com/easters2022/
https://easters2023.calicotab.com/easters2023/
https://easters2024.calicotab.com/easters2024/
https://easters2025.calicotab.com/easters2025/
https://tabtastic.calicotab.com/popposting2021/
https://uqpreaustrals2025.calicotab.com/uqpa2025/
https://unswtabs2025.calicotab.com/preaustrals2025/
https://usutabs2025.calicotab.com/grandslam/
https://usutabs2025.calicotab.com/usuopen2025/
https://usutabs2025.calicotab.com/pa2025/
https://aberopen2023.calicotab.com/AberOpen2023/
https://abp2020.calicotab.com/abp2020/
https://abp2021.calicotab.com/abp2021/
https://edudriftbackup.calicotab.com/abp2022/
https://midp.calicotab.com/mabp2023/
https://edudrift.calicotab.com/abp2024/
https://speechforces.calicotab.com/ao21/
https://aoix.calicotab.com/ao2023/
https://speechforces.calicotab.com/AOX/
https://mace.calicotab.com/africaiv2022/
https://mace.calicotab.com/africairongiant/
https://mace1996.calicotab.com/topuniversities2022/
https://mace.calicotab.com/andl2021/
https://akudc24.calicotab.com/akudc24/
https://inspired.calicotab.com/Agonia2025/
https://anudc.calicotab.com/anudc2024/
https://amsterdamopen.calicotab.com/amsterdam2022/
https://amsterdamopen.calicotab.com/AmsterdamOpen2023/
https://ao2024.calicotab.com/AO24/
https://anu.calicotab.com/spring21/
https://anuspring2023.calicotab.com/anuspring2023/
https://anuwinter22.calicotab.com/anuwinter22/
https://midp.calicotab.com/aedc2021/
https://Midp.calicotab.com/apad2020/
https://aodcbp22.calicotab.com/aodcbp22/
https://aodcbp2023.calicotab.com/aodcbp23/
https://astanaopen2021.calicotab.com/ao2021/
https://astanaopen.calicotab.com/_/
https://ateneoiv2023.calicotab.com/aiv2023/
https://aivpreworlds2023.calicotab.com/aivpw2023/
https://athena2024.calicotab.com/athena24/
https://hdf.calicotab.com/academy2025/
https://aucklandiv24.calicotab.com/aucklandiv24/
https://australianbp2021.calicotab.com/_/
https://abpdc2023.calicotab.com/abpdc2023/
https://abpdc2024.calicotab.com/abpdc2024/
https://sserigadebating.calicotab.com/balticopen2023/
https://balticiv24.calicotab.com/balticiv24/
https://balticiv25.calicotab.com/balticiv25/
https://bates2021.calicotab.com/bates2021/
https://mace.calicotab.com/bso2021/
https://bdidf-bangladesh.calicotab.com/bdidfbangladesh/
https://bdidf.calicotab.com/bdidf/
https://bdidf-pacific.calicotab.com/regional/
https://bdidf-west.calicotab.com/west/
https://bido2025.calicotab.com/bido2025/
https://open-communication.calicotab.com/belgrade2022/
https://opencommunication.calicotab.com/belgradeopen2023/
https://open-communication-2024.calicotab.com/belgradeopen2024/
https://berkeleyiv2024.calicotab.com/berkeleyiv24/
https://berkeleyiv25.calicotab.com/UCBIV25/
https://berlinonlineiv2020.calicotab.com/bivonline2020/
https://berlinopen2023.calicotab.com/berlinopen2023/
https://bigboi.calicotab.com/bigboi1/
https://birminghamesl2020.netlify.app/2020/
https://bhamproam.calicotab.com/bhamproam25/
https://bitspilani.calicotab.com/bppd2021/
https://bitspilanipd.calicotab.com/bppd2022/
https://bppd2024.calicotab.com/bppd2024/
https://aberdebates23.calicotab.com/bogwall23/
https://bracgenders2021.calicotab.com/bracgenders2021/
https://bracu.calicotab.com/open2024/
https://brazilopen2025.calicotab.com/brazilopen2025/
https://bristolopen2023.calicotab.com/_/
https://bristolopen24.calicotab.com/bristolopen24/
https://bristol2025.calicotab.com/_/
https://bristolproam23.calicotab.com/_/
https://bo2023.calicotab.com/bo2023/
https://budapestopen2024.calicotab.com/budapest2024/
https://bulacaniv2023.calicotab.com/bliv2023/
https://cambridgeivfinal.calicotab.com/2022/
https://cambridgeiv2023.calicotab.com/_/
https://cambridge2024.calicotab.com/cambridgeiv2024/
https://cambridgemini2024.calicotab.com/camini2024/
https://viiicatarinense.calicotab.com/viiicatarinense/
https://bpchamps2022.calicotab.com/bpchamps22/
https://capitalismiv2024.calicotab.com/capitalismiv2024/
https://cardiff2024.calicotab.com/c24/
https://cardiff2025.calicotab.com/cardiffopen2025/
https://carletonbpchamps.calicotab.com/bpchamps2022/
https://cebuproam.calicotab.com/britishparliamentary/
https://nomad.calicotab.com/ca_iv/
https://champagneiv2023.calicotab.com/_/
https://champagneiv2024.calicotab.com/champagneiv2024/
https://spu.calicotab.com/champagneiv2025/
https://chancellors2021.calicotab.com/chancellors2021/
https://fantasy2021.netlify.app/2021/
https://cfo3.calicotab.com/CFO3/
https://ccpc.calicotab.com/ctgbp2024/
https://chicagoopen.calicotab.com/chicagoopen/
https://cbp2021.calicotab.com/chinabp2021/
https://nhsdlcbpopen2025.calicotab.com/dlcbp2025/
https://cudc2024.calicotab.com/_/
https://cida.calicotab.com/viv23/
https://cmdlp2021.calicotab.com/cmdlp2021/
https://cmude2018.calicotab.com/_/
https://cmude2019.calicotab.com/cmude2019/
https://cmudemadrid2020.calicotab.com/cmude2020/
https://cmudeecuador2021.calicotab.com/cmudeecuador2021/
https://cmude2022.calicotab.com/cmude2022/
https://cmude2023.calicotab.com/cmude2023/
https://cmude2024.calicotab.com/open/
https://cmude2025.calicotab.com/open/
https://colgateopen2021.calicotab.com/colgateopen2021/
https://colgate2023.calicotab.com/colgate2023/
https://colgateopen2024.calicotab.com/colgate2024/
https://thecudc2024.calicotab.com/_/
https://mace.calicotab.com/cuiv2021/
https://copenhagen2024.calicotab.com/copenhagen2024/
https://copenhagenopen25.calicotab.com/_/
https://cornelliv.calicotab.com/cornell2022/
https://novicenats2021.calicotab.com/novicenats2021/
https://novicenats2022.calicotab.com/novicenats2022/
https://eds.calicotab.com/cusidsrpa2024/
https://daicopen.calicotab.com/daicopen/
https://dmd2020.calicotab.com/derozio2020/
https://dialectica.calicotab.com/dialecticabpd2025/
https://vaagyudh2024.calicotab.com/dialectica2024/
https://dilimandebateopen.calicotab.com/ddo2022/
https://dilimandebateopen.calicotab.com/ddo23/
https://dilimanintervarsity.calicotab.com/2024/
https://dilimandebating.calicotab.com/dilimanpreabp23/
https://dkwieninvitational.calicotab.com/dkwienmini23/
https://jrktpd2024.calicotab.com/jrktpd2024/
https://doxbridge-1.calicotab.com/doxbridge/
https://doxbridge-2.calicotab.com/doxbridge2/
https://doxbridge-3.calicotab.com/doxbridge3/
https://doxbridge-four.calicotab.com/doxbridge4/
https://doxbridge-prewudc.calicotab.com/prewudc/
https://doxbridge-worlds.calicotab.com/east/
https://doxbridge-worlds.calicotab.com/unified/
https://doxbridge-worlds.calicotab.com/west/
https://drexelopen2023.calicotab.com/_/
https://drexel2024.calicotab.com/drexel2024/
https://drexelopen2025.calicotab.com/drexel25/
https://drexelprewudc2025.calicotab.com/_/
https://dsdc2021.calicotab.com/dsdc/
https://dsnpd2022.calicotab.com/dsnpd2022/
https://dtumonsoons2024.calicotab.com/dtumonsoons2024/
https://dtupd2021.calicotab.com/dtupd2021/
https://dtupd2023.calicotab.com/dtupd2023/
https://dtupd25.calicotab.com/dtupd2025/
https://dukeopen2022.calicotab.com/duke2022/
https://durhamiv2021.calicotab.com/iv/
https://durhamiv2023.calicotab.com/durhamiv2023/
https://durhamiv2024.calicotab.com/durhamiv2024/
https://earlsfort2023.calicotab.com/_/
https://earlsfort2024.calicotab.com/earslfort2024/
https://muhib.calicotab.com/EMO/
https://tabtastic.calicotab.com/econopen/
https://edcup23.calicotab.com/edcup23/
https://edicup2024.calicotab.com/EdCup2024/
https://ednn.calicotab.com/EdNN/
https://edidebates.calicotab.com/edopen23/
https://eindhovenopen2025.calicotab.com/EindhovenOpen2025/
https://enbp2024.calicotab.com/enbp2024/
https://erasmusnovice2023.calicotab.com/ErasmusNovice2023/
https://ero2023.calicotab.com/_/
https://ero2024.calicotab.com/ERO2024/
https://dialectica.calicotab.com/Eristic2024/
https://mace.calicotab.com/globaleslrr2021/
https://web.archive.org/web/20190815133014/https://athenseudc.herokuapp.com/athenseudc/tab/team/
https://eudc2020.calicotab.com/eudc2020/
https://eudc2021.calicotab.com/eudc2021/
https://eudc2022.calicotab.com/eudc2022/
https://eudc2023.calicotab.com/_/
https://eudc2024.calicotab.com/_/
https://eudc2025.calicotab.com/_/
https://tabtastic.calicotab.com/eudcchallenge2021/
https://zhmasud.calicotab.com/euphorianoviceopen/
https://exeinv2025.calicotab.com/ExeInv2025/
https://exeteropen2024.calicotab.com/exeteropen2024/
https://exeteropen2025.calicotab.com/exeteropen2025/
https://guindon2024.calicotab.com/guindon2024/
https://bigboi.calicotab.com/fhdoxbbo-bp/
https://guu2023.calicotab.com/ancients2023/
https://glasgowancients24.calicotab.com/_/
https://glasgowancients2025.calicotab.com/glasgowancients2025/
https://summercup2022.calicotab.com/_/
https://glasgowsummer2023.calicotab.com/_/
https://glasgowsummer2024.calicotab.com/_/
https://glasgowsummercup2025.calicotab.com/glasgowsummercup2025/
https://tabtastic.calicotab.com/groningen2021/
https://cuhkszedt00.calicotab.com/gdc2022/
https://gdc2023.calicotab.com/gdc2023/
https://gdc2025.calicotab.com/GDC2025/
https://habibpreworlds2022.calicotab.com/habibpreworlds2022/
https://habib2024.calicotab.com/HUDC2024/
https://hudc2021.calicotab.com/hudc2021/
https://hadzabe-prewudc.calicotab.com/prewudc22/
https://hansrajpd2024.calicotab.com/hansrajpd2024/
https://hhiv2020.calicotab.com/hhiv2020/
https://hhiv2021.calicotab.com/HHIV2021/
https://hhiv2022.calicotab.com/hhiv2022/
https://hhiv2023.calicotab.com/hhiv2023/
https://hhiv2024.calicotab.com/_/
https://hbp22.calicotab.com/hbp2022/
https://mace1996.calicotab.com/heartsafire/
https://helsinkiopen2021.calicotab.com/helsinki2021/
https://hollatzdebates2021.calicotab.com/hollatz2021/
https://hkdc2023.calicotab.com/hkdc2023/
https://hkdc2024.calicotab.com/HKDC-2024/
https://hkdo2024.calicotab.com/hkdo2024/
https://hugill2020.calicotab.com/hugill2020/
https://dnn.calicotab.com/hrd2021/
https://hsda2024.calicotab.com/hsda2024/
https://hwsiv2021.calicotab.com/iv/
https://hwsrr2023.calicotab.com/hwsrr2023/
https://hwsrr2024.calicotab.com/hwsrr2024/
https://hwsrr2025.calicotab.com/_/
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2014.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2015.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2016.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2017.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2018.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2019.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2020.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2021.pdf
https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2022.pdf
https://hypotheticalopen.calicotab.com/_/
https://hypotheticalopen.calicotab.com/2/
https://iimapd25.calicotab.com/iimapd25/
https://13iitdebate.calicotab.com/13-IITB-Debate/
https://iitbombaydebate2022.calicotab.com/iitbombaydebate2022/
https://15thiitbombaydebate.calicotab.com/15thiitbombaydebate2023/
https://16thiitbombaydebate.calicotab.com/16thiitb/
https://18thiitbombaydebate.calicotab.com/18thiitb/
https://iitroorkee.calicotab.com/iitrpd2025/
https://iitbgrandprix.calicotab.com/iitb2024/
https://iitmpd.calicotab.com/iitmpd24/
https://iiuminterschooldebatingchampionship2023.calicotab.com/iiumopen2024/
https://ilnubpd2023.calicotab.com/2023/
https://ilnubpd2024.calicotab.com/ilnubpd/
https://ilnuroundrobin.calicotab.com/ilnurr2025/
https://iniv2022.calicotab.com/iniv2022/
https://mace1996.calicotab.com/expose4/
https://imperialinpersonopen2021.netlify.app/2021/
https://imperialiv2021.netlify.app/2021/
https://imperialiv2022.calicotab.com/_/
https://iv.imperialdebating.org/2023/
https://imperialiv24.calicotab.com/impiv24/
https://imperialiv25.calicotab.com/_/
https://imperialnovices2021.netlify.app/2021/
https://imperialnovices2022.calicotab.com/_/
https://imperialonlineopen2025.calicotab.com/imperialonlineopen2025/
https://imperialopen2021.netlify.app/2021/
https://imperialproam2021.netlify.app/2021/
https://imperialwinterproam2021.netlify.app/2021/
https://dialectica.calicotab.com/indiaabpfundraiser/
https://indiawudcfundraiser.calicotab.com/_/
https://ufd.calicotab.com/preabp25/
https://ufd.calicotab.com/ProAm24/
https://saveafather.calicotab.com/innertempleiv2021/
https://inneriv25.calicotab.com/InnerIV25/
https://debatnusantara2024.au-tab.app/ind2024/
https://intertext.calicotab.com/ipabp2023/
https://intertext.calicotab.com/ipado2023/
https://intertext.calicotab.com/ipa2024/
https://istanbulopen30international.calicotab.com/istanbulopen30/
https://tabserverofturkey.calicotab.com/ihuinternationalopen2025/
https://bhaavarth2024.calicotab.com/bhaavarthpd24/
https://johnshopkinsopen2022.calicotab.com/jhu2022/
https://jhuprewudc2023.calicotab.com/jhuprewudc2023/
https://mace.calicotab.com/jr22/
https://2001rean.calicotab.com/KO2024/
https://debatefoster.calicotab.com/KO2025/
https://kclopen2021.calicotab.com/kclopen2021/
https://kclopen2022.calicotab.com/kclopen/
https://kclopen2024.calicotab.com/kclopen2024/
https://kclopen25.calicotab.com/kclopen25/
https://kclopen2025.calicotab.com/kclpreeudc2025/
https://kclproam2020.calicotab.com/kclproam2020/
https://kclproam.calicotab.com/kclpa21/
https://kclproam2022.calicotab.com/kclpa2022/
https://kinnairdurduopen21.calicotab.com/kcdcenglish22/
https://kmcirongiant.calicotab.com/kmcirongiant/
https://knustopen2024.calicotab.com/_/
https://kumasi.calicotab.com/kdo24/
https://kyivopen2021.calicotab.com/kyiv/
https://lancasteriv.calicotab.com/lancaster25/
https://lantugi.calicotab.com/novicecup24/
https://dnn.calicotab.com/lawdebates/
https://leidenopen23.calicotab.com/leidenopen23/
https://leidenopen2024.calicotab.com/_/
https://lo2025.calicotab.com/lo2025/
https://linkbate-6-2022.calicotab.com/linkbate/
https://linkbate2024.calicotab.com/linkbate/
https://liverpool23.calicotab.com/Liverpool23/
https://liverpool25.calicotab.com/liverpool25/
https://tab.debate.si/lj-iv-22/
https://tab.debate.si/lj-iv-23/
https://loyoladebateopen2.calicotab.com/loyoladebateopen2/
https://lsetabs.calicotab.com/lseiv2022/
https://lsexiv.calicotab.com/lsexiv/
https://lseiv2024.calicotab.com/_/
https://lseopen2021.netlify.app/2021/
https://lseopen2022.calicotab.com/_/
https://lseopen2023.calicotab.com/_/
https://lseopen2024.calicotab.com/lsexopen2024/
https://lseopen2025.calicotab.com/_/
https://lubart2021.netlify.app/2021/
https://lums.calicotab.com/lumsiv21/
https://lums.calicotab.com/lumsiv25/
https://lums.calicotab.com/lumspreabp2024/
https://luzonintervarsity.calicotab.com/liv2021/
https://luzonintervarsity.calicotab.com/liv2022/
https://luzonintervarsity.calicotab.com/liv2023/
https://maastricht2025.calicotab.com/maastricht2025/
https://macaudebateopen2025.calicotab.com/macaudebateopen2025/
https://dnn.calicotab.com/ms2021/
https://dnn.calicotab.com/ms2024/
https://makdo.calicotab.com/makdo2023/
https://midp.calicotab.com/MBP2021/
https://midp.calicotab.com/malaysiabp2022/
https://midp.calicotab.com/malaysiabp2023/
https://wolce.calicotab.com/mnidc2020/
https://modo.calicotab.com/modo2025/
https://manchesteriv2021.netlify.app/2021/
https://manchesteriv2023.calicotab.com/manchesteriv/
https://manchesteriv2024.calicotab.com/Manchester2024/
https://manchesteriv25.calicotab.com/_/
https://mannov23.calicotab.com/_/
https://manzar2024.calicotab.com/manzar2024/
https://manzar2022.calicotab.com/manzar2022/
https://manzar2023.calicotab.com/manzar2023/
https://manzar.calicotab.com/Manzar/
https://mcgilliv2024.calicotab.com/iv/
https://mdu.calicotab.com/mcgilliv25/
https://macproams2021.calicotab.com/proams2022/
https://melbmini2020.calicotab.com/melbmini2020/
https://metaiv2021.calicotab.com/metaiv2021/
https://48thmpdc.calicotab.com/48thmpdc/
https://mad2024.calicotab.com/madprewudc2023/
https://moraytaintervarsity2024.calicotab.com/moriv2024/
https://mnbpd2025.calicotab.com/mnbpd2025/
https://nasparopen.calicotab.com/nasparopen2021/
https://naspar2023.calicotab.com/naspar2023/
https://nasparprewudc2023.calicotab.com/nasparprewudc2023/
https://nalsariv2021.calicotab.com/Nalsariv2021/
https://nalsariv2022.calicotab.com/nalsariv22/
https://nalsariv2023.calicotab.com/nalsariv2023/
https://sbinalsariv2024.calicotab.com/nalsariv2024/
https://naudc2021.calicotab.com/_/
https://naudc2023.calicotab.com/naudc2023/
https://naudc2024.calicotab.com/naudc2024/
https://naudc2025.calicotab.com/naudc2025/
https://neadc.calicotab.com/neadc/
https://neadc2022.calicotab.com/2022/
https://edudrift.calicotab.com/neadc2023/
https://neadc2024.calicotab.com/neadc2024/
https://ndsa.calicotab.com/ndo2021/
https://nsut.calicotab.com/nsmpd25/
https://newmanproam.calicotab.com/_/
https://nijmegen2023.calicotab.com/nijmegen2023/
https://xbpdnluo.calicotab.com/XNLUOBPD25/
https://norwichonline25.calicotab.com/norwichonline25/
https://nuspreworlds.calicotab.com/_/
https://odesa-esl.calicotab.com/odesa2021/
https://openbrasil2024.calicotab.com/openbrasil2024/
https://osakaiv2024.calicotab.com/_/
https://eds.calicotab.com/ottawaiv2025/
https://ottawa27wudc.calicotab.com/ottawaopen2025/
https://docs.google.com/spreadsheets/d/1-lpe7j1wAaGc2Zwd6B2BTCZIAmmYMSS0iufEWj8ZXDE/edit?gid=631217382#gid=631217382
https://oxfordiv2020.netlify.app/2020/
https://oxford2021.calicotab.com/oxfordiv2021/
https://oxfordiv2022.calicotab.com/_/
https://oxfordiv2023.calicotab.com/_/
https://oxiv2024.calicotab.com/_/
https://pakdebateforum.calicotab.com/open2025/
https://awdppakistanopen.calicotab.com/pakdo2021/
https://pdc2023.calicotab.com/_/
https://mace.calicotab.com/paudc2021/
https://paudc2022.calicotab.com/PAUDC2022/
https://nutifafapaudc.calicotab.com/paudc2023/
https://paudc2024.calicotab.com/paudcK24/
https://pearlpd.calicotab.com/pearlbpd2021/
https://pkuproam24.calicotab.com/pkuproam24/
https://pkuproam25.calicotab.com/_/
https://pennwsdc2024.calicotab.com/ppw2024/
https://ndcdiliman2022.calicotab.com/NDCDiliman2022/
https://pipers.calicotab.com/pipers/
https://pragueopen2024.calicotab.com/_/
https://prativaad.calicotab.com/prativaad25/
https://preeudcchallenge2024mini.calicotab.com/_/
https://ukrainedebates.calicotab.com/odesa2023/
https://ppiv2021.calicotab.com/ppiv2021/
https://princetoniv2021.calicotab.com/princetoniv2021/
https://princetoniv2023.calicotab.com/princeton23/
https://princetoniv2024.calicotab.com/princetoniv2024/
https://paqo2020.calicotab.com/proam/
https://tabtastic.calicotab.com/qmiv2021/
https://qto2021.netlify.app/2021/
https://pakdebateforum.calicotab.com/rdo2024/
https://pakdebateforum.calicotab.com/rdo2025/
https://ramaiah.calicotab.com/RRR21/
https://randompa5.calicotab.com/rpav/
https://rclpd2023.calicotab.com/rclpd2023/
https://rmlbpd23.calicotab.com/rmlbpd2023/
https://rotterdampreeudc.calicotab.com/rotterdampreeudc/
https://mace.calicotab.com/RPDA2021/
https://mace.calicotab.com/rpdainternals2022/
https://mace.calicotab.com/rpdapre-paudc2023/
https://rpmd2021.calicotab.com/rpmd21/
https://rvdt.calicotab.com/rvdt2021/
https://rvdt.calicotab.com/rvdt2023/
https://mace.calicotab.com/saudc2022/
https://stamesa23.calicotab.com/stamesa23/
https://smdo24.calicotab.com/stamesa24/
https://mace.calicotab.com/sanudc2021/
https://sbs.calicotab.com/sbsbpd22/
https://sbs.calicotab.com/sbsbpd23/
https://sbs.calicotab.com/sbsbpd24/
https://scottishmace.calicotab.com/Mace2022/
https://mace2024.calicotab.com/mace24/
https://mace2025.calicotab.com/mace2025/
https://suiv2022.calicotab.com/seattleiv2021/
https://suonlinemini23.calicotab.com/suonlinemini2023/
https://suiv24yodl.calicotab.com/suiv24yodl/
https://siv2025.calicotab.com/seriousiv2025/
https://severncup23.calicotab.com/severncup/
https://shahjiwana.calicotab.com/SIDC25/
https://sidc.calicotab.com/sidc/
https://sndo2023.calicotab.com/sndo2023/
https://sheffieldiv2020.netlify.app/2020/
https://sheffieldnovices23.calicotab.com/sheffieldnovices2023/
https://srcc.calicotab.com/shrirampreabp2021/
https://srcc.calicotab.com/shrirampreabp2022/
https://srbp2023.calicotab.com/srbp2023/
https://srbp2024.calicotab.com/srbp2024/
https://srbp25.calicotab.com/srbp25/
https://sido22.calicotab.com/sido22/
https://sido23.calicotab.com/sido2023/
https://sido2024.calicotab.com/sido/
https://sido2025.calicotab.com/sido2025/
https://smartdebates2020.calicotab.com/sdmini/
https://smartdebates2020.calicotab.com/sd2021/
https://socialismopen.calicotab.com/SocialismOpen/
https://sofiaonline2023.calicotab.com/_/
https://sofiaonline24.calicotab.com/_/
https://sofiaonlinept2.calicotab.com/soopt2/
https://sofiaopen2022.calicotab.com/sofia2022/
https://sofiaopen2024.calicotab.com/_/
https://sofiapreeudc.calicotab.com/_/
https://siiv2023.calicotab.com/siiv2023/
https://southamptonopen2022.calicotab.com/_/
https://southamptonopen2023.calicotab.com/_/
https://southampton2024.calicotab.com/_/
https://southamptonopen2025.calicotab.com/southamptonopen2025/
https://sotonproam24.calicotab.com/SotonProAm24/
https://sotonsillies25.calicotab.com/sotonsillies25/
https://splitopen2025.calicotab.com/split2025/
https://challengeopen.calicotab.com/springchallenge2025/
https://sgiv2025.calicotab.com/sgiv2025/
https://sserigaproamvii.calicotab.com/Pro-AmVIII/
https://sserigaiv23.calicotab.com/sseriv2023/
https://standrewsopen2025.calicotab.com/standrewsopen2025/
https://staspreeudc.calicotab.com/_/
https://standrewspreeudc2025.calicotab.com/_/
https://sdoofficial.calicotab.com/sdo2023/
https://structuralreasons.calicotab.com/structural/
https://structuralreasons2.calicotab.com/_/
https://ssudrcan.calicotab.com/SDRC2025/
https://mace.calicotab.com/fundraiser2024/
https://sunwaydebate.calicotab.com/sundo2022/
https://sunwaydebate.calicotab.com/sundo2023/
https://sunwaydebate.calicotab.com/sundo2024/
https://sunwaydebate.calicotab.com/sundo2025/
https://sunwaydebate.calicotab.com/spren2023/
https://surabaya-open2023.au-tab.app/so2023/
https://surpriseiv.calicotab.com/surprise22/
https://peoplespeak2024.calicotab.com/peoplespeak2024/
https://peoplespeak2025.calicotab.com/peoplespeak2025/
https://swaniv23.calicotab.com/swaniv23/
https://sydmini2022.calicotab.com/sydmini2022/
https://sydneymini2023.calicotab.com/sydneymini2023/
https://sydmini2024.calicotab.com/sydmini24/
https://zabiv.calicotab.com/zabiv2024/
https://autumnopen2023.calicotab.com/_/
https://springopen2023.calicotab.com/_/
https://summeropen2023.calicotab.com/_/
https://taftdebateopen2024.calicotab.com/tdo2024/
https://technion2023.calicotab.com/_/
https://thecallout2022.calicotab.com/_/
https://mace.calicotab.com/tco2021/
https://thedelhidebate2024.calicotab.com/delhidebate2024/
https://gsdctab.calicotab.com/TGSO2025/
https://rvdt.calicotab.com/rvdt2022/
https://wolce.calicotab.com/twd2020/
https://tabtastic.calicotab.com/theologyopen2021/
https://tilburgopen2024.calicotab.com/TilburgOpen2024/
https://tokyoiv2023.calicotab.com/tokyoiv2023/
https://tabtastic.calicotab.com/trinityiv2021/
https://trinity2022.calicotab.com/iv/
https://trinity2023.calicotab.com/iv/
https://trinity2024.calicotab.com/iv/
https://trinityiv2025.calicotab.com/trinityiv2025/
https://trinityopen2021.calicotab.com/_/
https://trinityopen2023.calicotab.com/trinityopen2023/
https://trinityopen2025.calicotab.com/trinityopen2025/
https://uspopen2024.calicotab.com/open2024/
https://uqonlineopen2025.calicotab.com/uqonlineopen2025/
https://usciv2025.calicotab.com/_/
https://ucriv2024.calicotab.com/ucriv2024/
https://petermaguireiv.calicotab.com/petermaguireiv2022/
https://pmiv23.calicotab.com/_/
https://petermaguire2025.calicotab.com/petermaguire2025/
https://ucl.calicotab.com/iv2021/
https://ucliv2023.calicotab.com/_/
https://ucliv24.calicotab.com/ucliv2024/
https://uclpresidents2021.calicotab.com/_/
https://uclpcup24.calicotab.com/pcup2024/
https://uclwinterproam.calicotab.com/_/
https://uclproam2025.calicotab.com/uclproam2025/
https://uclproam23.calicotab.com/proam2024/
https://ucladebateunion.calicotab.com/uclaiv2023/
https://uclaiv2024.calicotab.com/uclaiv2024/
https://uhuruworlds2023.calicotab.com/uhuru2023/
https://uhuruworlds2024.calicotab.com/uhuruworlds2024/
https://uhuru2025.calicotab.com/_/
https://uhuru-worlds.calicotab.com/loxodonta/
https://uhuruworlds2022.calicotab.com/loxuhuruworlds2022/
https://uhuru-worlds.calicotab.com/uw2021outrounds/
https://uhuruworlds2022.calicotab.com/uhuruworlds2022outrounds/
https://uhuru-worlds.calicotab.com/panthera/
https://uhuruworlds2022.calicotab.com/pan_uhuruworlds2022/
https://tahsinraian.calicotab.com/ulab/
https://untitledpreeudc.calicotab.com/2023/
https://untitledpreglasgow.calicotab.com/2024/
https://usciv2021.calicotab.com/usciv2021/
https://usc.calicotab.com/usciv22/
https://usudc2020.calicotab.com/usudc2020/
https://usudc2022.calicotab.com/usudc2022/
https://usudc2023.calicotab.com/usudc2023/
https://usudc2025.calicotab.com/_/
https://maradebates.calicotab.com/maraiv2024/
https://utsiv2021.calicotab.com/uts-iv-2021/
https://utrecht23.calicotab.com/utrecht2023/
https://utrechtopen2025.calicotab.com/_/
https://vandy2024.calicotab.com/vandy2024/
https://upesbpd24.calicotab.com/upesbpd24/
https://viv22.calicotab.com/viv2022/
https://viv2023.calicotab.com/_/
https://viennaiv24.calicotab.com/viv24/
https://viennaiv2025.calicotab.com/ViennaIV2025/
https://viennapreeudc2024.calicotab.com/_/
https://viennaprewudc.calicotab.com/_/
https://viennaprewudc2024.calicotab.com/prewudcvoo2024/
https://vivaatam2024.calicotab.com/vivaatam2024/
https://vivaatam.calicotab.com/vivaatam25/
https://7th-vitark.calicotab.com/vitark2022/
https://vitdt23.calicotab.com/vitdt2023/
https://warwickiv2022.calicotab.com/warwickiv2022/
https://warwickopen2024.calicotab.com/warwickopen2024/
https://warwickopen.calicotab.com/warwickopen/
https://warwick2025.calicotab.com/_/
https://cudcwaterloo.calicotab.com/cudc2024/
https://waterlooiv.calicotab.com/waterlooiv2025/
https://rrwaudc.calicotab.com/waudc2024/
https://westerniv.calicotab.com/westerniv2022/
https://western2023.calicotab.com/western2023/
https://westerniv2024.calicotab.com/western2024/
https://2022westernstates.calicotab.com/2022WesternStates/
https://debatesymposium.calicotab.com/winterdebatesymposium2025/
https://wolce.calicotab.com/novice22/
https://wpa2020.calicotab.com/preabp/
https://wolce.calicotab.com/pro-ams2021/
https://midp.calicotab.com/wdo2021/
https://midp.calicotab.com/wdo2022/
https://wudc2014.calicotab.com/wudc2014/
https://wudc2015.calicotab.com/_/
https://web.archive.org/web/20201002235840/https://www.tabbie.org/thessaloniki-wudc-2016/#speaker-tab
https://docs.google.com/spreadsheets/d/1mhNLrH-ZfEozNLfGie6_sW_BdVexayYX/edit?gid=1845854710#gid=1845854710
https://wudc2018.calicotab.com/wudc2018/
https://docs.google.com/spreadsheets/d/1RaAzZEhjby_IBj8pZxCbXzDuq6Qi4dda/edit?gid=1354848172#gid=1354848172
https://wudc2020.calicotab.com/wudc2020/
https://wudckorea.calicotab.com/2021/
https://wudc2022.calicotab.com/wudc/
https://wudc2023.calicotab.com/wudc/
https://wudc2024.calicotab.com/wudc/
https://wudc2025.calicotab.com/open/
https://yaleiv2021.netlify.app/2021/
https://yaleiv2022.calicotab.com/_/
https://yaleiv2023.calicotab.com/yaleiv2023/
https://yaleiv2024.calicotab.com/_/
https://yaleivfall21.calicotab.com/_/
https://midp.calicotab.com/yodo2021/
https://tab.debate.si/zagreb-open-24/
https://zgopen2025.calicotab.com/zgopen2025/
https://zagrebpreeudc2024.calicotab.com/zagrebpreeudc24/
https://zagrebpreeudc2025.calicotab.com/_/
https://zagrebprewudc.calicotab.com/_/
https://zagreb2024.calicotab.com/zagreb2024/
https://ndc2024.calicotab.com/hermosa/
https://mace.calicotab.com/easters2022/
https://mace.calicotab.com/zodleliminations2021/
https://zurichopen2024.calicotab.com/_/
https://popcultureiii.calicotab.com/popcultureiii/
https://northams2021.calicotab.com/northams2021/
https://norams2023.calicotab.com/norams2023/
https://norams2024.calicotab.com/norams2024/
https://northams2025.calicotab.com/_/
https://bitsqed2023.calicotab.com/qed23/
https://pedxingdebate.calicotab.com/px16debate/
https://nashdc2024.calicotab.com/nashdc2024/
https://psdc2024homecoming.calicotab.com/psdc2024/
https://asdc2025.calicotab.com/asdc2025/
https://harvardanz2024.calicotab.com/HarvardANZ2024/
https://cabp2025.calicotab.com/cabp_na/
https://camschoolsfinals22.calicotab.com/finalsday/
https://cambridgeschools2024.calicotab.com/_/
https://cambridgeschools2025.calicotab.com/cambridgeschools2025/
https://durhamschools23.calicotab.com/schools2023/
https://ebpworldcup.calicotab.com/EBPWoldCup/
https://hhsummer.calicotab.com/hhsummer/
https://hhsummer24.calicotab.com/hhsummer2024/
https://icyd2022.calicotab.com/finalsday/
https://cambridgeschools2025.calicotab.com/icyd2025/
https://iiumdebates.calicotab.com/IIUMIDC25/
https://imperialjuniors2025.calicotab.com/imperialjuniors2025/
https://lsedebate.calicotab.com/lsesrs/
https://manchesterschools23.calicotab.com/manchesterschools23/
https://oxfordschoolsfinals2022.calicotab.com/oxfordschoolsfinals2022/
https://oxschools2023.calicotab.com/oxschools2023/
https://oxschools2024.calicotab.com/_/
https://oxfordschools2025.calicotab.com/2025/
https://oxschoolssg2025.calicotab.com/oxschoolssg2025/
https://seedtournaments.calicotab.com/ottawaclassic2024/
https://xsdc2024.calicotab.com/xsdc2024/
https://angkorwsdc.calicotab.com/angkorwsdc/
https://aodcjunior2024.calicotab.com/aodc/
https://debateland.calicotab.com/asiajwsdc24/
https://mwsdes.calicotab.com/apwsdc2021/
https://mwsdes.calicotab.com/apwsdc2022/
https://mwsdes.calicotab.com/apwsdc2023/
https://mwsdes.calicotab.com/apwsdc2024/
https://midp.calicotab.com/awsdo2022/
https://midp.calicotab.com/awsdo2023/
https://midp.calicotab.com/awsdo2024/
https://aodc2022.calicotab.com/aodc2022/
https://aodc2023.calicotab.com/aodcwsdc/
https://aodc2024.calicotab.com/aodcwsdc/
https://aodc2025.calicotab.com/aodc2025/
https://austriawsdc2025.calicotab.com/_/
https://159.223.65.214:8000/awsdc2023/
https://awsdc2025.calicotab.com/AWSDC2025/
https://fndo24.calicotab.com/24fndo/
https://tonade2024.calicotab.com/TONADE2024/
https://columbiawsdc2025.calicotab.com/columbiawsdc2025/
https://tab.wsdc.online/doxbridge/
https://doxbridge-wsdc2022.calicotab.com/doxwsdc/
https://dsp.calicotab.com/inaugural2024/
https://dsp2021-2024.calicotab.com/seniornationals2023/
https://argument.calicotab.com/ECO2024/
https://argument.calicotab.com/eco2025/
https://esdc2023.calicotab.com/esdc2023/
https://esdc.calicotab.com/esdc2025/
https://tab.debate.si/eursdc24/
https://eurosdc25.calicotab.com/eurosdc-25/
https://dnn.calicotab.com/eiwsdc2024/
https://dnn.calicotab.com/eiwsdc2025/
https://debateland.calicotab.com/gondwanawsdc/
https://gba2024.calicotab.com/gba/
https://wst.calicotab.com/harvardwst2025/
https://wst2024.calicotab.com/wst2024/
https://hkpds2022.calicotab.com/hkpds/
https://indopacific2023.calicotab.com/ipwsdc/
https://ufd.calicotab.com/ipwsdo24/
https://ufd.calicotab.com/wsdo2025/
https://iwsdc2023.calicotab.com/_/
https://intertext.calicotab.com/ipwsdc2023s/
https://intertext.calicotab.com/ipwsdc2024/
https://mwsdes.calicotab.com/miwsdc2024/
https://mwsdes.calicotab.com/miwsdc2025/
https://mwsdes.calicotab.com/mnswsdc2024/
https://pre-wsdc2025.calicotab.com/_/
https://nordics2023.calicotab.com/nordics2023/
https://nsdc25.calicotab.com/NordicSDC2025/
https://mwsdes.calicotab.com/nwsdc2025/
https://nzsdc2024.calicotab.com/nzsdc2024/
https://nzsdc2025.calicotab.com/nzsdc2025/
https://oldhamcup2024.calicotab.com/oldhamcup2024/
https://oldhamcup2025.calicotab.com/oldhamcup2025/
https://oldham2021.calicotab.com/oldhamAPAL/
https://oxwsdc2021.calicotab.com/oxwsdc2021/
https://oxfordwsdc2025.calicotab.com/2025/
https://pakdebateforum.calicotab.com/pakistanprewsdc2024/
https://pakdebateforum.calicotab.com/pakistanprewsdc2025/
https://debateland.calicotab.com/PangeaWSDC24/
https://papilloniv2024.calicotab.com/papillon2024/
https://papilloniv.calicotab.com/papilloniv/
https://pwsc2023.calicotab.com/_/
https://pariswsdc.calicotab.com/pariswsdc2024/
https://pariswsdc2025.calicotab.com/_/
https://upenn2021.calicotab.com/worlds/
https://pennwsdc2024.calicotab.com/pennwsdc2024/
https://upenndebate.calicotab.com/pennwsdc2025/
https://pennworldschools22.calicotab.com/2022/
https://psdctab2023.calicotab.com/psdc2023/
https://psdc2024.calicotab.com/psdc2024/
https://tab.debate.si/pds-22/
https://tab.debate.si/pds-23/
https://pds2024.calicotab.com/pds2024/
https://tab.debate.si/pds-2025/participants/list/
https://princetonwst.calicotab.com/princetonwst2024/
https://qduh.calicotab.com/QWSDC2024/
https://mwsdes.calicotab.com/rookiewsdc2025/
https://seasons.calicotab.com/spwsdc2025/
https://seasons.calicotab.com/swsdc2024/
https://sofiaprewsdc24.calicotab.com/sofiapre-wsdc/
https://sasdc.calicotab.com/sasdc/
https://sadebating.calicotab.com/sawsdc25/
https://sasdc25.calicotab.com/sasdc25/
https://standrewsprewsdc.calicotab.com/standrewsprewsdc/
https://taiwanwsdc2025.calicotab.com/2025/
https://scottishschoolsdebating.calicotab.com/thistlecup2023/
https://thistlecup2024.calicotab.com/thistlecup2024/
https://thistlecup2025.calicotab.com/thistlecup2025/
https://debatefoster.calicotab.com/toaschools3/
https://twsc.calicotab.com/_/
https://transpacificwsdc.calicotab.com/transpacificwsdc/
https://transpacificwsdc2024.calicotab.com/transpacificwsdc2024/
https://ubcwsdcsummer2024.calicotab.com/ubcwsdc2024/
https://vanprewsdc2025.calicotab.com/vancouverprewsdc2025/
https://vilniusopen2024.calicotab.com/vilnius2024/
https://westernwsdc.calicotab.com/westernwsdc2024/
https://westernhighschools.calicotab.com/westernwsdc2025/
https://tab.debate.si/who-2023/
https://hdd.debate.si/who_2024/
http://wsdc2018.com/results/
https://docs.google.com/spreadsheets/d/1iqG6Df0_-3PNKyAJ4ufZSxXio7LgmaOrItHuG8LejVc/edit?gid=0#gid=0
https://docs.google.com/spreadsheets/d/1oBOCHbLLJAtekaVPP0tZldolpZjFY5-x1eoU-CDGRJU/edit
https://paullau.wordpress.com/2022/08/20/wsdc-2022-results-round-up/
https://docs.google.com/spreadsheets/d/1lralzhC-MUcXZsEOQ4i6b_Ep0nLzbU4b_kd1aIxgb1M/edit
https://wsdc2024.calicotab.com/wsdc2024/
https://wsdc2025.calicotab.com/_/
https://mace.calicotab.com/zimbabwewsdc2025/"""

In [ ]:
calico_tabs = set()

for url in urls.split('\n'): 
    if 'calicotab' not in url:
        print(f'[WARN] Skipping non-calico tab: {url}') #FIXME: could still parse some of the self-hosted ones
        continue

    calico_pattern = re.compile(r'https?:\/\/([a-zA-Z0-9-_]+)\.calicotab\.com\/([a-zA-Z0-9-_]+)\/')
    match = re.match(calico_pattern, url)

    if match is None:
        print(f'[WARN] Could not parse url: {url}')
        continue

    subdomain = match.group(1)
    slug = match.group(2)

    calico_tabs.add((subdomain, slug))

calico_tabs = list(calico_tabs)

[WARN] Skipping non-calico tab: https://uadc2024.au-tab.app/uadc2024/
[WARN] Skipping non-calico tab: https://birminghamesl2020.netlify.app/2020/
[WARN] Skipping non-calico tab: https://fantasy2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://web.archive.org/web/20190815133014/https://athenseudc.herokuapp.com/athenseudc/tab/team/
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2014.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2015.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2016.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2017.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2018.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2019.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2020.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2021.pdf
[WARN] Skipping non-calico tab: https://people.hws.edu/barnes/hwsrr/images/tabs/RR-Tab-2022.pdf
[WARN] Skipping non-calico tab: https://imperialinpersonopen2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://imperialiv2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://iv.imperialdebating.org/2023/
[WARN] Skipping non-calico tab: https://imperialnovices2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://imperialopen2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://imperialproam2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://imperialwinterproam2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://debatnusantara2024.au-tab.app/ind2024/
[WARN] Skipping non-calico tab: https://tab.debate.si/lj-iv-22/
[WARN] Skipping non-calico tab: https://tab.debate.si/lj-iv-23/
[WARN] Skipping non-calico tab: https://lseopen2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://lubart2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://manchesteriv2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1-lpe7j1wAaGc2Zwd6B2BTCZIAmmYMSS0iufEWj8ZXDE/edit?gid=631217382#gid=631217382
[WARN] Skipping non-calico tab: https://oxfordiv2020.netlify.app/2020/
[WARN] Skipping non-calico tab: https://qto2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://sheffieldiv2020.netlify.app/2020/
[WARN] Skipping non-calico tab: https://surabaya-open2023.au-tab.app/so2023/
[WARN] Skipping non-calico tab: https://web.archive.org/web/20201002235840/https://www.tabbie.org/thessaloniki-wudc-2016/#speaker-tab
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1mhNLrH-ZfEozNLfGie6_sW_BdVexayYX/edit?gid=1845854710#gid=1845854710
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1RaAzZEhjby_IBj8pZxCbXzDuq6Qi4dda/edit?gid=1354848172#gid=1354848172
[WARN] Skipping non-calico tab: https://yaleiv2021.netlify.app/2021/
[WARN] Skipping non-calico tab: https://tab.debate.si/zagreb-open-24/
[WARN] Skipping non-calico tab: https://159.223.65.214:8000/awsdc2023/
[WARN] Skipping non-calico tab: https://tab.wsdc.online/doxbridge/
[WARN] Skipping non-calico tab: https://tab.debate.si/eursdc24/
[WARN] Skipping non-calico tab: https://tab.debate.si/pds-22/
[WARN] Skipping non-calico tab: https://tab.debate.si/pds-23/
[WARN] Skipping non-calico tab: https://tab.debate.si/pds-2025/participants/list/
[WARN] Skipping non-calico tab: https://tab.debate.si/who-2023/
[WARN] Skipping non-calico tab: https://hdd.debate.si/who_2024/
[WARN] Skipping non-calico tab: http://wsdc2018.com/results/
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1iqG6Df0_-3PNKyAJ4ufZSxXio7LgmaOrItHuG8LejVc/edit?gid=0#gid=0
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1oBOCHbLLJAtekaVPP0tZldolpZjFY5-x1eoU-CDGRJU/edit
[WARN] Skipping non-calico tab: https://paullau.wordpress.com/2022/08/20/wsdc-2022-results-round-up/
[WARN] Skipping non-calico tab: https://docs.google.com/spreadsheets/d/1lralzhC-MUcXZsEOQ4i6b_Ep0nLzbU4b_kd1aIxgb1M/edit

In [150]:
len(calico_tabs), calico_tabs[:5]

(766,
 [('cmude2019', 'cmude2019'),
  ('cambridgeiv2023', '_'),
  ('spu', 'champagneiv2025'),
  ('dkwieninvitational', 'dkwienmini23'),
  ('cmdlp2021', 'cmdlp2021')])

In [ ]:
allowed_sides = ["og", "oo", "cg", "co"] #for now, only supports BP ballots

async def retrieve_results(pairings_url: str, session):
    """
    Retrieves the results (including ballot and speaker scores, if available) from a given pairings URL, as defined by TabbyCat.
    """

    results = {}

    pairings = None
    try:
        async with session.get(pairings_url) as pairings_response:
            if pairings_response.status == 401:
                print(f'[WARN] Behind auth for URL {pairings_url}. Skipping extracting ballots...')
                return {}

            assert pairings_response.status == 200, f"Failed to fetch {pairings_url}: {pairings_response.status}"
            pairings = await pairings_response.json()
            results["n"] = len(pairings)
    except Exception as e:
        print(f'Failed to fetch pairings for URL: {pairings_url}, {e}')
        return {}

    for pairing in pairings:
        ballots_url = pairing["_links"]["ballots"]

        try:
            ballots = None

            async with session.get(ballots_url) as ballots_response:
                assert ballots_response.status == 200, f"Failed to fetch {ballots_url}: {ballots_response.status}"
                ballots = await ballots_response.json()

            if (
                "detail" in ballots
                and ballots["detail"]
                == "Authentication credentials were not provided."
            ):
                print(
                    f"[WARN] Behind auth for URL {pairings_url}. Skipping extracting ballots..."
                )

                raise Exception(f'Failed to fetch ballots for pairing URL due to authentication error (this should not happen, since we already checked before): {ballots_url}')

            #FIXME: deal with motion used in multiple rounds
            assert len(ballots) == 1, "Expected 1 ballot for pairing URL: " + ballots_url
            sheets = ballots[0]["result"]["sheets"]

            if len(sheets) > 1:
                print(
                    f"[WARN] Multiple sheets at URL: {ballots_url}. Using only the first sheet." #FIXME:
                )

            teams = sheets[0]["teams"]

            if teams[0]["side"] not in allowed_sides:
                print(
                    f'[WARN] First team in sheet is not a valid BP position: {ballots_url}. Skipping extracting ballots...'
                )

                return {}

            for i, team in enumerate(teams):
                side = team["side"]
                assert side in allowed_sides

                points = team["points"]
                win = team["win"] 

                assert (
                    points is not None or win is not None
                ), f"Points and wins are both None for side: {side}"

                if points is not None:
                    prev_sum = results.get("sum_" + side, 0)
                    results["sum_" + side] = prev_sum + points
                
                    # sum up the points for all pairs of teams
                    # needed for balance calculation
                    for team2 in teams[i:]:
                        side2 = team2['side']

                        key = "sum_" + side + "_" + side2
                        prev_sum_sum = results.get(key, 0)
                        results[key] = prev_sum_sum + team2['points'] * points

                if win is True:
                    key = side + "_wins"
                    prev_wins = results.get(key, 0)
                    results[key] = prev_wins + 1
                
                if team["score"] is not None: 
                    key = "speaks"
                    prev_speaks = results.get(key, 0)
                    results[key] = prev_speaks + team["score"]

        except Exception as e:
            print(f'[WARN] Failed to fetch ballot for URL: {ballots_url}, {e}')
            continue

    return results

In [ ]:
supported_sides = ["og", "oo", "cg", "co"]

async def are_ballots_accessible(session, main_url):
    """
        Run a preliminary check to see if ballots are accessible for a given tournament (or if e.g. behind auth).
    """

    #FIXME: should check for more than just round 1, since apparently one round can be authed and the other not...
    round_1_pairings_url = main_url + "/rounds/1/pairings"

    try: 
        async with session.get(round_1_pairings_url) as round_1_pairings_response:
            if round_1_pairings_response.status == 401:
                print(f'[INFO] Behind auth for URL {round_1_pairings_url}. Skipping extracting ballots...')
                return False

            assert round_1_pairings_response.status == 200, f"Failed to fetch {round_1_pairings_url}: {round_1_pairings_response.status}"
            round_1_pairings = await round_1_pairings_response.json()

        first_pairing = round_1_pairings[0]

        ballot_url = first_pairing["_links"]["ballots"]
        async with session.get(ballot_url) as ballot_response:
            if ballot_response.status == 401:
                print(f'[INFO] Behind auth for URL {ballot_url}. Skipping extracting ballots...')
                return False
            
            assert ballot_response.status == 200, f"Failed to fetch {ballot_url}: {ballot_response.status}"

            ballots = await ballot_response.json()

            if (
                "detail" in ballots
                and ballots["detail"]
                == "Authentication credentials were not provided."
            ):
                return False
            

            sheet = ballots[0]['result']['sheets'][0]

            for team in sheet['teams']:
                if team['side'] not in supported_sides:
                    print(f'[INFO] Skipping {main_url} because it has a side that is not supported: {team["side"]}')
                    return False #FIXME: when support for wsdc/australs is added
    except Exception as e:
        print(f'Failed to check if ballots are accessible for {round_1_pairings_url}: {e}. Defaulting to True to always try to fetch ballots.')
        return True

    return True

In [161]:
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await are_ballots_accessible(session, 'https://gba2024.calicotab.com/api/v1/tournaments/gba')
    assert response == False
    response = await are_ballots_accessible(session, 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_')
    assert response == True
    response = await are_ballots_accessible(session, 'https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24')
    assert response == False
    response = await are_ballots_accessible(session, 'https://australs2021.calicotab.com/api/v1/tournaments/_')
    assert response == False

{'teams': [{'side': 'aff', 'points': 1, 'win': True, 'score': 243.0, 'team': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/teams/186785', 'speeches': [{'ghost': False, 'score': 70.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655462'}, {'ghost': False, 'score': 69.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655461'}, {'ghost': False, 'score': 69.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655460'}, {'ghost': False, 'score': 35.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655462'}]}, {'side': 'neg', 'points': 0, 'win': False, 'score': 242.0, 'team': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/teams/186802', 'speeches': [{'ghost': False, 'score': 69.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655559'}, {'ghost': False, 'score': 69.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655556'}, {'ghost': False, 'score': 69.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655555'}, {'ghost': False, 'score': 35.0, 'speaker': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/speakers/655556'}]}], 'adjudicator': 'https://gba2024.calicotab.com/api/v1/tournaments/gba/adjudicators/655509'}
[INFO] Skipping https://gba2024.calicotab.com/api/v1/tournaments/gba because it has a side that is not supported: aff
{'teams': [{'side': 'og', 'points': 1, 'win': False, 'score': 158.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234650', 'speeches': [{'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816360'}, {'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816359'}]}, {'side': 'oo', 'points': 2, 'win': False, 'score': 159.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234659', 'speeches': [{'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816377'}, {'ghost': False, 'score': 80.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816378'}]}, {'side': 'cg', 'points': 3, 'win': False, 'score': 164.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234653', 'speeches': [{'ghost': False, 'score': 82.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816366'}, {'ghost': False, 'score': 82.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816365'}]}, {'side': 'co', 'points': 0, 'win': False, 'score': 156.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234647', 'speeches': [{'ghost': False, 'score': 78.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816353'}, {'ghost': False, 'score': 78.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816354'}]}], 'adjudicator': None}
[INFO] Behind auth for URL https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24/rounds/1/pairings/347107/ballots. Skipping extracting ballots...
{'teams': [{'side': 'aff', 'points': 0, 'win': False, 'score': 263.5, 'team': 'https://australs2021.calicotab.com/api/v1/tournaments/_/teams/63069', 'speeches': [{'ghost': False, 'score': 75.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217909'}, {'ghost': False, 'score': 76.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217941'}, {'ghost': False, 'score': 75.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217971'}, {'ghost': False, 'score': 37.5, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217941'}]}, {'side': 'neg', 'points': 1, 'win': True, 'score': 271.5, 'team': 'https://australs2021.calicotab.com/api/v1/tournaments/_/teams/63159', 'speeches': [{'ghost': False, 'score': 77.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217716'}, {'ghost': False, 'score': 78.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217968'}, {'ghost': False, 'score': 78.0, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217897'}, {'ghost': False, 'score': 38.5, 'speaker': 'https://australs2021.calicotab.com/api/v1/tournaments/_/speakers/217968'}]}], 'adjudicator': 'https://australs2021.calicotab.com/api/v1/tournaments/_/adjudicators/218051'}
[INFO] Skipping https://australs2021.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff

In [172]:
import asyncio 

async def retrieve_motions(subdomain, slug, session):
    rows = []

    tab_url = f"https://{subdomain}.calicotab.com/{slug}"
    
    main_url = f"https://{subdomain}.calicotab.com/api/v1/tournaments/{slug}"

    tournament_name = None
    tournament_short_name = None
    try: 
        async with session.get(main_url) as response:
            assert response.status == 200, f"Failed to fetch {main_url}: {response.status}"
            tournament_json = await response.json()

            if 'detail' in tournament_json and tournament_json['detail'] == 'No Tournament matches the given query.':
                raise Exception(f'No tournament matches the given query for URL: {main_url}')

            tournament_name = tournament_json['name']
            tournament_short_name = tournament_json['short_name']
    except Exception as e:
        print(f'[ERROR] Failed to fetch tournament root info for url: {main_url}')
        return []

    is_ballotable = await are_ballots_accessible(session, main_url)

    motions_url = f"{main_url}/motions"

    motions = None
    try: 
        async with session.get(motions_url) as response:
            assert response.status == 200, f"Failed to fetch motions for {motions_url}: {response.status}"
            motions = await response.json()
    except Exception as e:
        print(f'[ERROR] Failed to fetch motions for URL: {motions_url}, {e}')
        return []

    for motion in motions:
        if len(motion['rounds']) <= 0: #skip unused (test) motions
            print(f'[INFO] Skipping motion: {motion["text"]} from URL: {motions_url} because it has no rounds.')
            continue

        rounds_parsed = {} #for tracking multiple rounds for the same motion
        results = {}

        rounds = motion['rounds']
        for i,round in enumerate(rounds): 
            round_url = round['round']

            round_json = None
            try: 
                async with session.get(round_url) as round_response:
                    assert round_response.status == 200, f"Failed to fetch round for {round_url}: {round_response.status}"
                    round_json = await round_response.json()
            except Exception as e:
                print(f'[ERROR] Failed to fetch round for URL: {round_url}, {e}')
                continue

            rounds_parsed[f'round_{i+1}'] = round_json['name']
            rounds_parsed[f'stage_{i+1}'] = round_json['stage']

            pairings_url = round_json['_links']['pairing']

            if is_ballotable:
                results = await retrieve_results(pairings_url, session)

        row = {
            'Motion': motion['text'],
            'Info Slide': motion['info_slide_plain'],
            'Tournament': tournament_name,
            'short_name': tournament_short_name,
            'tab_url': tab_url,
            **results,
            **rounds_parsed,
        }

        rows.append(row)

    return rows

In [163]:
#check
import aiohttp

async with aiohttp.ClientSession() as session:
    response = await retrieve_motions('hwsrr2025', '_', session)
print(response)

{'teams': [{'side': 'og', 'points': 1, 'win': False, 'score': 158.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234650', 'speeches': [{'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816360'}, {'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816359'}]}, {'side': 'oo', 'points': 2, 'win': False, 'score': 159.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234659', 'speeches': [{'ghost': False, 'score': 79.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816377'}, {'ghost': False, 'score': 80.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816378'}]}, {'side': 'cg', 'points': 3, 'win': False, 'score': 164.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234653', 'speeches': [{'ghost': False, 'score': 82.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816366'}, {'ghost': False, 'score': 82.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816365'}]}, {'side': 'co', 'points': 0, 'win': False, 'score': 156.0, 'team': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/teams/234647', 'speeches': [{'ghost': False, 'score': 78.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816353'}, {'ghost': False, 'score': 78.0, 'speaker': 'https://hwsrr2025.calicotab.com/api/v1/tournaments/_/speakers/816354'}]}], 'adjudicator': None}
[{'Motion': 'This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 12, 'sum_og_og': 36, 'sum_og_oo': 9, 'sum_og_cg': 12, 'sum_og_co': 15, 'speaks': 2579.0, 'sum_oo': 3, 'sum_oo_oo': 5, 'sum_oo_cg': 0, 'sum_oo_co': 4, 'sum_cg': 4, 'sum_cg_cg': 8, 'sum_cg_co': 4, 'sum_co': 5, 'sum_co_co': 7, 'round_1': 'Round 1-A', 'stage_1': 'P', 'round_2': 'Round 1-B', 'stage_2': 'P'}, {'Motion': 'This house regrets the Indian Premier League.', 'Info Slide': 'The Indian Premier League (IPL) is a domestic cricket league in India. Since\nits inception in 2007, it has grown to become the largest cricket league in\nthe world, attracting sponsorship that exceeds that of most national teams.\n\nTraditionally, cricket competition has been dominated by international events\nand national teams touring other countries, and has involved games lasting\neither five days or one day. The IPL popularized large-scale domestic cricket\nleagues, and is played in a shorter, three-hour format of cricket called\nTwenty20 (T20). Teams are allowed up to 4 international (non-Indian) players\nin their teams. Additionally, the IPL usually lasts 3-4 months, taking up a\nsignificant portion of the annual cricket calendar.', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 2, 'sum_og_og': 2, 'sum_og_oo': 5, 'sum_og_cg': 0, 'sum_og_co': 5, 'speaks': 2574.0, 'sum_oo': 9, 'sum_oo_oo': 23, 'sum_oo_cg': 5, 'sum_oo_co': 21, 'sum_cg': 3, 'sum_cg_cg': 5, 'sum_cg_co': 8, 'sum_co': 10, 'sum_co_co': 26, 'round_1': 'Round 2-A', 'stage_1': 'P', 'round_2': 'Round 2-B', 'stage_2': 'P'}, {'Motion': 'This house believes that breaking up large meat companies is in the interests of animal welfare.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 6, 'sum_og_og': 10, 'sum_og_oo': 9, 'sum_og_cg': 8, 'sum_og_co': 9, 'speaks': 2544.0, 'sum_oo': 7, 'sum_oo_oo': 15, 'sum_oo_cg': 9, 'sum_oo_co': 9, 'sum_cg': 5, 'sum_cg_cg': 13, 'sum_cg_co': 0, 'sum_co': 6, 'sum_co_co': 18, 'round_1': 'Round 3-A', 'stage_1': 'P', 'round_2': 'Round 3-B', 'stage_2': 'P'}, {'Motion': 'This house prefers a world where genius only develops after adulthood (so that there are no child prodigies).', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 8, 'sum_og_og': 22, 'sum_og_oo': 12, 'sum_og_cg': 6, 'sum_og_co': 8, 'speaks': 2592.0, 'sum_oo': 7, 'sum_oo_oo': 17, 'sum_oo_cg': 6, 'sum_oo_co': 7, 'sum_cg': 5, 'sum_cg_cg': 13, 'sum_cg_co': 5, 'sum_co': 4, 'sum_co_co': 4, 'round_1': 'Round 4-A', 'stage_1': 'P', 'round_2': 'Round 4-B', 'stage_2': 'P'}, {'Motion': 'This house believes that East African national governments should prioritize investments in agriculture (e.g., irrigation, R&D, and inputs like fertilizer) over accelerating industrialization (e.g., building infrastructure, export promotion).', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 4, 'sum_og': 12, 'sum_og_og': 36, 'sum_og_oo': 9, 'sum_og_cg': 9, 'sum_og_co': 18, 'speaks': 2585.0, 'sum_oo': 3, 'sum_oo_oo': 3, 'sum_oo_cg': 2, 'sum_oo_co': 4, 'sum_cg': 3, 'sum_cg_cg': 5, 'sum_cg_co': 2, 'sum_co': 6, 'sum_co_co': 12, 'round_1': 'Round 5-A', 'stage_1': 'P', 'round_2': 'Round 5-B', 'stage_2': 'P'}, {'Motion': 'Assuming a peaceful and democratic transition, this house supports the United States of America being separated into several, more politically-homogeneous, sovereign states.', 'Info Slide': '', 'Tournament': 'HWS Round Robin 2025', 'short_name': 'HWS RR 2025', 'tab_url': 'https://hwsrr2025.calicotab.com/_', 'n': 1, 'cg_wins': 1, 'round_1': 'Grand Final', 'stage_1': 'E'}]

In [171]:
async with aiohttp.ClientSession() as session:
    response = await retrieve_motions('wudc2018', 'pw2019', session)
response

[ERROR] Failed to fetch tournament root info for url: https://wudc2018.calicotab.com/api/v1/tournaments/pw2019

[]

In [ ]:
import aiohttp

rows = []

# FIXME: takes a shit ton of time (45min), what could we optimize?
# - maybe always maintaining 100 connnections as opposed to batching statically
async with aiohttp.ClientSession() as session:
    batch_n = 100
    n = len(calico_tabs)

    print(f"Starting data fetching for {n} tournaments...")
    calico_tabs.reverse()

    for i in tqdm(range(0, len(calico_tabs), batch_n)): 
        futures = [retrieve_motions(subdomain, slug, session) for subdomain, slug in calico_tabs[i:i+batch_n]]
        responses = await asyncio.gather(*futures)
        batch = [m for row in responses for m in row] #flatten
        rows.extend(batch)

Starting data fetching for 766 tournaments...

  0%|          | 0/8 [00:00<?, ?it/s]

[ERROR] Failed to fetch tournament root info for url: https://nomad.calicotab.com/api/v1/tournaments/ca_iv
[ERROR] Failed to fetch tournament root info for url: https://trinityopen2021.calicotab.com/api/v1/tournaments/_
Failed to check if ballots are accessible for https://amsterdamopen.calicotab.com/api/v1/tournaments/amsterdam2022/rounds/1/pairings: list index out of range. Defaulting to True to always try to fetch ballots.
[INFO] Behind auth for URL https://hkdo2024.calicotab.com/api/v1/tournaments/hkdo2024/rounds/1/pairings/344241/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://cmude2019.calicotab.com/api/v1/tournaments/cmude2019/rounds/1/pairings/39478/ballots. Skipping extracting ballots...
Failed to check if ballots are accessible for https://cmdlp2021.calicotab.com/api/v1/tournaments/cmdlp2021/rounds/1/pairings: list index out of range. Defaulting to True to always try to fetch ballots.
[INFO] Behind auth for URL https://chancellors2021.calicotab.com/api/v1/tournaments/chancellors2021/rounds/1/pairings/100703/ballots. Skipping extracting ballots...
[INFO] Skipping https://edudrift.calicotab.com/api/v1/tournaments/uadc2025 because it has a side that is not supported: aff
[INFO] Skipping https://edudrift.calicotab.com/api/v1/tournaments/australs2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://usc.calicotab.com/api/v1/tournaments/usciv22/rounds/1/pairings/114850/ballots. Skipping extracting ballots...
[INFO] Skipping https://nsmpd23.calicotab.com/api/v1/tournaments/nsmpd23 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://hugill2020.calicotab.com/api/v1/tournaments/hugill2020/rounds/1/pairings/66948/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://argument.calicotab.com/api/v1/tournaments/eco2025/rounds/1/pairings/175307/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://nsdc25.calicotab.com/api/v1/tournaments/NordicSDC2025/rounds/1/pairings/381341/ballots. Skipping extracting ballots...
[INFO] Skipping https://edudrift.calicotab.com/api/v1/tournaments/australs2024 because it has a side that is not supported: aff
[INFO] Skipping https://psdc2024.calicotab.com/api/v1/tournaments/psdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://hwsiv2021.calicotab.com/api/v1/tournaments/iv/rounds/1/pairings/99017/ballots. Skipping extracting ballots...
[INFO] Skipping https://westernwsdc.calicotab.com/api/v1/tournaments/westernwsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://metaiv2021.calicotab.com/api/v1/tournaments/metaiv2021/rounds/1/pairings/58722/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://sofiaopen2022.calicotab.com/api/v1/tournaments/sofia2022/rounds/1/pairings/157848/ballots. Skipping extracting ballots...
[INFO] Skipping https://oldhamcup2025.calicotab.com/api/v1/tournaments/oldhamcup2025 because it has a side that is not supported: aff
[INFO] Skipping https://austriawsdc2025.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Skipping https://eurosdc25.calicotab.com/api/v1/tournaments/eurosdc-25 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://icyd2022.calicotab.com/api/v1/tournaments/finalsday/rounds/1/pairings/132172/ballots. Skipping extracting ballots...
[INFO] Skipping https://nashdc2024.calicotab.com/api/v1/tournaments/nashdc2024 because it has a side that is not supported: aff
[INFO] Skipping https://doxbridge-wsdc2022.calicotab.com/api/v1/tournaments/doxwsdc because it has a side that is not supported: aff
[INFO] Behind auth for URL https://doxbridge-worlds.calicotab.com/api/v1/tournaments/east/rounds/1/pairings/17443/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://hhsummer.calicotab.com/api/v1/tournaments/hhsummer/rounds/1/pairings/224387/ballots. Skipping extracting ballots...
[INFO] Skipping https://dnn.calicotab.com/api/v1/tournaments/eiwsdc2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://usudc2020.calicotab.com/api/v1/tournaments/usudc2020/rounds/1/pairings/16716/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://aoix.calicotab.com/api/v1/tournaments/ao2023/rounds/1/pairings/236244/ballots. Skipping extracting ballots...
[INFO] Skipping https://iitbhupd.calicotab.com/api/v1/tournaments/iitbhupd2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/africairongiant/rounds/1/pairings/85499/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://hhiv2021.calicotab.com/api/v1/tournaments/HHIV2021/rounds/1/pairings/99164/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://gdc2025.calicotab.com/api/v1/tournaments/GDC2025/rounds/1/pairings/447504/ballots. Skipping extracting ballots...
[INFO] Skipping https://princetonwst.calicotab.com/api/v1/tournaments/princetonwst2024 because it has a side that is not supported: aff
[INFO] Skipping https://debateland.calicotab.com/api/v1/tournaments/asiajwsdc24 because it has a side that is not supported: aff
[INFO] Skipping motion: ECCQ las megaciudades latinoamericanas (Buenos Aires, Rio de Janeiro, etc.) deberían reestructurarse hacia el 'urbanismo de los 15 minutos’. from URL: https://cmude2025.calicotab.com/api/v1/tournaments/open/motions because it has no rounds.
Failed to check if ballots are accessible for https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings: Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440417/ballots: 500. Defaulting to True to always try to fetch ballots.
[INFO] Skipping motion: Assuming feasibility, THBT State should reimburse victim's family for every death that occurs out of negligence e.g Road accidents due to poorly maintained roads, pregnant mothers dying due to shortage of staff and medical facilities in governmental health centres etc from URL: https://mace.calicotab.com/api/v1/tournaments/africairongiant/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64472/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64472/ballots
[INFO] Skipping motion: THO the portrayal of orgasm as the end- goal of sexual interactions from URL: https://kclopen2024.calicotab.com/api/v1/tournaments/kclopen2024/motions because it has no rounds.
[INFO] Skipping motion: TH, as a new media company, W choose to maintain editorial anonymity without consistent attribution of any particular writers (for example, the Economist); rather than allow individual writers having their own independent, recognisable voices (for example, the Atlantic) from URL: https://dnn.calicotab.com/api/v1/tournaments/eiwsdc2025/motions because it has no rounds.
[INFO] Skipping motion: TH, as a new media company, W choose to maintain editorial anonymity without consistent attribution of any particular writers (for example, the Economist); rather than allow individual writers having their own independent, recognisable voices (for example, the Atlantic) from URL: https://dnn.calicotab.com/api/v1/tournaments/eiwsdc2025/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64477/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64477/ballots
[INFO] Skipping motion: THR the norm that art should be difficult to understand from URL: https://hhsummer.calicotab.com/api/v1/tournaments/hhsummer/motions because it has no rounds.
[INFO] Skipping motion: THR the norm that art should be difficult to understand from URL: https://hhsummer.calicotab.com/api/v1/tournaments/hhsummer/motions because it has no rounds.
[INFO] Skipping motion: THR the norm that art should be difficult to understand from URL: https://hhsummer.calicotab.com/api/v1/tournaments/hhsummer/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64484/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64484/ballots
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64487/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/2/pairings/64487/ballots
[WARN] Failed to fetch ballot for URL: https://sofiaonline2023.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/211860/ballots, Failed to fetch https://sofiaonline2023.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/211860/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440417/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440417/ballots: 500
[INFO] Skipping motion: A zombie infection has broken out, THBT it is morally legitimate to kill uninfected humans to increase your own chances of survival. from URL: https://amsterdamopen.calicotab.com/api/v1/tournaments/amsterdam2022/motions because it has no rounds.
[INFO] Skipping motion: THR the increase in religious activity after the fall of communism in Eastern Europe from URL: https://amsterdamopen.calicotab.com/api/v1/tournaments/amsterdam2022/motions because it has no rounds.
[INFO] Skipping motion: This House, as a philantropic foundation whose sole aim is to do as much good as possible, would heavily prioritse funding long-termist projects from URL: https://amsterdamopen.calicotab.com/api/v1/tournaments/amsterdam2022/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64471/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64471/ballots
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64476/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64476/ballots
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440418/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440418/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64483/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64483/ballots
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64486/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/3/pairings/64486/ballots
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440419/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440419/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/7/pairings/64475/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/7/pairings/64475/ballots
[INFO] Skipping motion: THBT publicly funded healthcare should heavily prioritize funding diagnostics and disease detection over treatment from URL: https://cebuproam.calicotab.com/api/v1/tournaments/britishparliamentary/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440420/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440420/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/7/pairings/64479/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/7/pairings/64479/ballots
[WARN] Failed to fetch ballot for URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/8/pairings/64474/ballots, Expected 1 ballot for pairing URL: https://wolce.calicotab.com/api/v1/tournaments/twd2020/rounds/8/pairings/64474/ballots
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/1/pairings/15518/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/1/pairings/15518/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440421/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440421/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440422/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440422/ballots: 500
[INFO] Skipping motion: That renters of public housing should be allowed to purchase that housing at a discounted rate. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[INFO] Skipping motion: That, in cities facing housing crises, we would remove all heritage protections in building codes. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440423/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/1/pairings/440423/ballots: 500
[INFO] Skipping motion: That, in states with a low fertility rate, we prefer policies with a familising effect rather than a de-familising effect. from URL: https://edudrift.calicotab.com/api/v1/tournaments/australs2024/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/1/pairings/15536/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/1/pairings/15536/ballots: 500
[WARN] Behind auth for URL https://imperialjuniors2025.calicotab.com/api/v1/tournaments/imperialjuniors2025/rounds/3/pairings. Skipping extracting ballots...
[WARN] Behind auth for URL https://imperialjuniors2025.calicotab.com/api/v1/tournaments/imperialjuniors2025/rounds/4/pairings. Skipping extracting ballots...
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440424/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440424/ballots: 500
[WARN] Behind auth for URL https://imperialjuniors2025.calicotab.com/api/v1/tournaments/imperialjuniors2025/rounds/5/pairings. Skipping extracting ballots...
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440425/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440425/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15480/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15480/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440426/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440426/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440427/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440427/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15497/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15497/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440428/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440428/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15501/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15501/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440429/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440429/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440430/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/2/pairings/440430/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440431/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440431/ballots: 500
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15533/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/2/pairings/15533/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440432/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440432/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440433/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440433/ballots: 500
[WARN] Failed to fetch ballot for URL: https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440434/ballots, Failed to fetch https://petermaguire2025.calicotab.com/api/v1/tournaments/petermaguire2025/rounds/3/pairings/440434/ballots: 500
[INFO] Skipping motion: THBT the mother should mutilate her child from URL: https://kclopen2024.calicotab.com/api/v1/tournaments/kclopen2024/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/3/pairings/15492/ballots, Failed to fetch https://wpa2020.calicotab.com/api/v1/tournaments/preabp/rounds/3/pairings/15492/ballots: 500

 12%|█▎        | 1/8 [04:39<32:33, 279.02s/it]

[INFO] Skipping https://muntazar2024.calicotab.com/api/v1/tournaments/muntazar24 because it has a side that is not supported: aff
[INFO] Skipping https://pakdebateforum.calicotab.com/api/v1/tournaments/pakistanprewsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://hbp22.calicotab.com/api/v1/tournaments/hbp2022/rounds/1/pairings/32152/ballots. Skipping extracting ballots...
[INFO] Skipping https://intertext.calicotab.com/api/v1/tournaments/ipwsdc2024 because it has a side that is not supported: aff
[INFO] Skipping https://sofiaprewsdc24.calicotab.com/api/v1/tournaments/sofiapre-wsdc because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sndo2023.calicotab.com/api/v1/tournaments/sndo2023/rounds/1/pairings/255938/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://paudc2024.calicotab.com/api/v1/tournaments/paudcK24/rounds/1/pairings/347107/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://cambridgeschools2025.calicotab.com/api/v1/tournaments/cambridgeschools2025/rounds/1/pairings/440004/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://tabtastic.calicotab.com/api/v1/tournaments/groningen2021/rounds/1/pairings/49720/ballots. Skipping extracting ballots...
[INFO] Skipping https://transpacificwsdc2024.calicotab.com/api/v1/tournaments/transpacificwsdc2024 because it has a side that is not supported: aff
[INFO] Skipping https://debatefoster.calicotab.com/api/v1/tournaments/toaschools3 because it has a side that is not supported: aff
[INFO] Skipping https://pakdebateforum.calicotab.com/api/v1/tournaments/pakistanprewsdc2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://champagneiv2024.calicotab.com/api/v1/tournaments/champagneiv2024/rounds/1/pairings/296508/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://nzsdc2024.calicotab.com/api/v1/tournaments/nzsdc2024/rounds/1/pairings/302615/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://springopen2023.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/197099/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://astanaopen2021.calicotab.com/api/v1/tournaments/ao2021/rounds/1/pairings/39965/ballots. Skipping extracting ballots...
[INFO] Skipping https://nrmd.calicotab.com/api/v1/tournaments/nrmd2023 because it has a side that is not supported: aff
[INFO] Skipping https://shivajienglishpd.calicotab.com/api/v1/tournaments/shivaji2025 because it has a side that is not supported: aff
[INFO] Skipping https://speakup10.calicotab.com/api/v1/tournaments/speakup because it has a side that is not supported: aff
[INFO] Skipping https://bduadc2020.calicotab.com/api/v1/tournaments/uadc2020 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://suonlinemini23.calicotab.com/api/v1/tournaments/suonlinemini2023/rounds/1/pairings/251744/ballots. Skipping extracting ballots...
[INFO] Skipping https://pedxingdebate.calicotab.com/api/v1/tournaments/px16debate because it has a side that is not supported: aff
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/miwsdc2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://iniv2022.calicotab.com/api/v1/tournaments/iniv2022/rounds/1/pairings/111911/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://macproams2021.calicotab.com/api/v1/tournaments/proams2022/rounds/1/pairings/100295/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://tabtastic.calicotab.com/api/v1/tournaments/trinityiv2021/rounds/1/pairings/49448/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://saveafather.calicotab.com/api/v1/tournaments/innertempleiv2021/rounds/1/pairings/52937/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://maradebates.calicotab.com/api/v1/tournaments/maraiv2024/rounds/1/pairings/176847/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://hypotheticalopen.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/180639/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://aodc2023.calicotab.com/api/v1/tournaments/aodcwsdc/rounds/1/pairings/192961/ballots. Skipping extracting ballots...
[INFO] Skipping https://australs2020.calicotab.com/api/v1/tournaments/australs2020 because it has a side that is not supported: aff
[INFO] Skipping https://dsp2021-2024.calicotab.com/api/v1/tournaments/seniornationals2023 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://oldhamcup2024.calicotab.com/api/v1/tournaments/oldhamcup2024/rounds/1/pairings/289139/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/paudc2021/rounds/1/pairings/84816/ballots. Skipping extracting ballots...
[INFO] Skipping https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24 because it has a side that is not supported: aff
[INFO] Skipping https://iitpd2023.calicotab.com/api/v1/tournaments/iitpd2023 because it has a side that is not supported: aff
[INFO] Skipping https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://chicagoopen.calicotab.com/api/v1/tournaments/chicagoopen/rounds/1/pairings/137827/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://carletonbpchamps.calicotab.com/api/v1/tournaments/bpchamps2022/rounds/1/pairings/168197/ballots. Skipping extracting ballots...
[INFO] Skipping https://13zdo.calicotab.com/api/v1/tournaments/13thzdo because it has a side that is not supported: aff
[INFO] Skipping https://pariswsdc2025.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Behind auth for URL https://abp2021.calicotab.com/api/v1/tournaments/abp2021/rounds/1/pairings/99277/ballots. Skipping extracting ballots...
[INFO] Skipping motion: This house supports educational flexibility at schools from URL: https://pakdebateforum.calicotab.com/api/v1/tournaments/pakistanprewsdc2024/motions because it has no rounds.
[INFO] Skipping motion: This house supports educational flexibility at schools from URL: https://pakdebateforum.calicotab.com/api/v1/tournaments/pakistanprewsdc2024/motions because it has no rounds.
[INFO] Skipping motion: This House would require all world maps to be drawn using equal-area projections from URL: https://oldhamcup2024.calicotab.com/api/v1/tournaments/oldhamcup2024/motions because it has no rounds.
[INFO] Skipping motion: This house would disallow the state practice of naturalizing foreign athletes to serve on national sports teams. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: THS prominent sports clubs (like Manchester United) releasing their IPOs. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: THBT football clubs should be mandated to have half of their playing 11 to be comprised of homegrown players. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
Failed to check if ballots are accessible for https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings: Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436365/ballots: 500. Defaulting to True to always try to fetch ballots.
[INFO] Skipping motion: THS bonded scholarship programmes by developing countries. from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: This House, as a young person with the means, would choose to be a digital nomad rather than work in their home country from URL: https://shivajienglishpd.calicotab.com/api/v1/tournaments/shivaji2025/motions because it has no rounds.
[INFO] Skipping motion: THO the rise of manifestation culture from URL: https://shivajienglishpd.calicotab.com/api/v1/tournaments/shivaji2025/motions because it has no rounds.
[INFO] Skipping motion: THBT large scale public efforts should be made for classic books to be made more accessible from URL: https://shivajienglishpd.calicotab.com/api/v1/tournaments/shivaji2025/motions because it has no rounds.
[INFO] Skipping motion: THBT college graduates should prioritize being career generalists over career specialists. from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: THR the rise of homeschooling. from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: THS bonded scholarship
programmes by developing
countries from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: THBT college graduates should prioritize being career generalists over career specialist from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: THR the rise of homeschooling from URL: https://iitdebsoc.calicotab.com/api/v1/tournaments/debutant24/motions because it has no rounds.
[INFO] Skipping motion: THBT states should be held accountable before international courts for crimes committed by paramilitary groups. from URL: https://springopen2023.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: THBT states should be held accountable before international courts for crimes committed by paramilitary groups. from URL: https://springopen2023.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: THBT states should be held accountable before international courts for crimes committed by paramilitary groups. from URL: https://springopen2023.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://linkbate-6-2022.calicotab.com/api/v1/tournaments/linkbate/rounds/1/pairings/112534/ballots, Failed to fetch https://linkbate-6-2022.calicotab.com/api/v1/tournaments/linkbate/rounds/1/pairings/112534/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436365/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436365/ballots: 500
[INFO] Skipping motion: This house would violate the ceasefire and kill the leaders from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that the protections of international law conventions and treaties should not apply to combatants from terrorist organisations (e.g. prohibition on torture, prisoner of war status, guarantee of post-conflict release) from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that one man’s terrorist is another man’s freedom fighter. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house would violate the ceasefire and kill the leaders from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that the protections of international law conventions and treaties should not apply to combatants from terrorist organisations (e.g. prohibition on torture, prisoner of war status, guarantee of post-conflict release) from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that one man’s terrorist is another man’s freedom fighter. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house would violate the ceasefire and kill the leaders from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that the protections of international law conventions and treaties should not apply to combatants from terrorist organisations (e.g. prohibition on torture, prisoner of war status, guarantee of post-conflict release) from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[INFO] Skipping motion: This house believes that one man’s terrorist is another man’s freedom fighter. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd24/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436369/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436369/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436374/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436374/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436379/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436379/ballots: 500
[INFO] Skipping motion: THBT the American government should increase the gas tax and direct the revenue towards modernising and expanding public transport from URL: https://novicenats2022.calicotab.com/api/v1/tournaments/novicenats2022/motions because it has no rounds.
[INFO] Skipping motion: THBT the American government should increase the gas tax and direct the revenue towards modernising and expanding public transport from URL: https://novicenats2022.calicotab.com/api/v1/tournaments/novicenats2022/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436383/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436383/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436387/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436387/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436390/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436390/ballots: 500
[INFO] Skipping motion: THBT ASEAN should allow free movement of labour within the bloc. from URL: https://rclpd2023.calicotab.com/api/v1/tournaments/rclpd2023/motions because it has no rounds.
[INFO] Skipping motion: THBT ASEAN should allow free movement of labour within the bloc. from URL: https://rclpd2023.calicotab.com/api/v1/tournaments/rclpd2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436396/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436396/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436400/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436400/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436403/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436403/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436408/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436408/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436411/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436411/ballots: 500
[INFO] Skipping motion: This House would abolish timeouts in all team sports from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[INFO] Skipping motion: This House would make Esperanto mandatory in all schools in the world from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[INFO] Skipping motion: This House would require every citizen to watch a film produced in their country every year from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436416/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436416/ballots: 500
[INFO] Skipping motion: This House would not buy Apple from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436420/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436420/ballots: 500
[INFO] Skipping motion: This House would impose trade sanctions on countries that do not use the metric system from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[INFO] Skipping motion: This House regrets our reliance on the internet from URL: https://ucladebateunion.calicotab.com/api/v1/tournaments/uclaiv2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436424/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436424/ballots: 500
[INFO] Skipping motion: This house, as the Democratic Party in the United States, would swing at every pitch rather than pick battles against the Republican Party from URL: https://usudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436428/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436428/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436432/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436432/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436435/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436435/ballots: 500
[WARN] Failed to fetch ballot for URL: https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436440/ballots, Failed to fetch https://oxfordschools2025.calicotab.com/api/v1/tournaments/2025/rounds/1/pairings/436440/ballots: 500

 25%|██▌       | 2/8 [12:58<40:51, 408.58s/it]

[ERROR] Failed to fetch tournament root info for url: https://odesa-esl.calicotab.com/api/v1/tournaments/odesa2021
[ERROR] Failed to fetch tournament root info for url: https://australianbp2021.calicotab.com/api/v1/tournaments/_
[INFO] Behind auth for URL https://erasmusnovice2023.calicotab.com/api/v1/tournaments/ErasmusNovice2023/rounds/1/pairings/188306/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://doxbridge-1.calicotab.com/api/v1/tournaments/doxbridge/rounds/1/pairings/18972/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://cmudemadrid2020.calicotab.com/api/v1/tournaments/cmude2020/rounds/1/pairings/43658/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://doxbridge-worlds.calicotab.com/api/v1/tournaments/west/rounds/1/pairings/17621/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/cuiv2021/rounds/1/pairings/84014/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/RPDA2021/rounds/1/pairings/84225/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://aodc2022.calicotab.com/api/v1/tournaments/aodc2022/rounds/1/pairings/118779/ballots. Skipping extracting ballots...
[INFO] Skipping https://ufd.calicotab.com/api/v1/tournaments/wsdo2025 because it has a side that is not supported: aff
[INFO] Skipping https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://oxschools2024.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/286516/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://iiumdebates.calicotab.com/api/v1/tournaments/IIUMIDC25/rounds/1/pairings/422096/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://yec2024debates.calicotab.com/api/v1/tournaments/yec2024debates/rounds/1/pairings/309272/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://esdc.calicotab.com/api/v1/tournaments/esdc2025/rounds/1/pairings/438445/ballots. Skipping extracting ballots...
[INFO] Skipping https://edudriftbackup.calicotab.com/api/v1/tournaments/uadc2021 because it has a side that is not supported: aff
[INFO] Skipping https://wsdc2025.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Skipping https://ado2025.calicotab.com/api/v1/tournaments/ado2025 because it has a side that is not supported: aff
[INFO] Skipping https://cbspd2025.calicotab.com/api/v1/tournaments/cbspd2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sdoofficial.calicotab.com/api/v1/tournaments/sdo2023/rounds/1/pairings/247269/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://dnn.calicotab.com/api/v1/tournaments/hrd2021/rounds/1/pairings/94892/ballots. Skipping extracting ballots...
[INFO] Skipping https://australs2016.calicotab.com/api/v1/tournaments/australs2016 because it has a side that is not supported: aff
[INFO] Skipping https://papilloniv.calicotab.com/api/v1/tournaments/papilloniv because it has a side that is not supported: aff
[INFO] Skipping https://pwsc2023.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/apwsdc2021 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sido23.calicotab.com/api/v1/tournaments/sido2023/rounds/1/pairings/249914/ballots. Skipping extracting ballots...
[INFO] Skipping https://nordics2023.calicotab.com/api/v1/tournaments/nordics2023 because it has a side that is not supported: aff
[INFO] Skipping https://dsp.calicotab.com/api/v1/tournaments/inaugural2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://naudc2021.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/110403/ballots. Skipping extracting ballots...
[INFO] Skipping https://tonade2024.calicotab.com/api/v1/tournaments/TONADE2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://esdc2023.calicotab.com/api/v1/tournaments/esdc2023/rounds/1/pairings/181492/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://ao2024.calicotab.com/api/v1/tournaments/AO24/rounds/1/pairings/337579/ballots. Skipping extracting ballots...
[INFO] Skipping https://gambit25.calicotab.com/api/v1/tournaments/gambit because it has a side that is not supported: aff
[INFO] Behind auth for URL https://bitspilanipd.calicotab.com/api/v1/tournaments/bppd2022/rounds/1/pairings/126882/ballots. Skipping extracting ballots...
[INFO] Skipping https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://aodc2025.calicotab.com/api/v1/tournaments/aodc2025/rounds/1/pairings/242669/ballots. Skipping extracting ballots...
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/mnswsdc2024 because it has a side that is not supported: aff
[INFO] Skipping https://ikhtilafpd23.calicotab.com/api/v1/tournaments/ikhtilaf2025 because it has a side that is not supported: aff
[INFO] Skipping https://kpp2025.calicotab.com/api/v1/tournaments/kamaligprepidc25 because it has a side that is not supported: aff
[INFO] Skipping https://popcultureiii.calicotab.com/api/v1/tournaments/popcultureiii because it has a side that is not supported: aff
[INFO] Behind auth for URL https://2022westernstates.calicotab.com/api/v1/tournaments/2022WesternStates/rounds/1/pairings/126035/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://smartdebates2020.calicotab.com/api/v1/tournaments/sdmini/rounds/1/pairings/16084/ballots. Skipping extracting ballots...
[INFO] Skipping https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD because it has a side that is not supported: aff
[INFO] Skipping https://thistlecup2024.calicotab.com/api/v1/tournaments/thistlecup2024 because it has a side that is not supported: aff
[INFO] Skipping https://cupd2025.calicotab.com/api/v1/tournaments/cupd25 because it has a side that is not supported: aff
[INFO] Skipping https://australs2015.calicotab.com/api/v1/tournaments/australs2015 because it has a side that is not supported: aff
[INFO] Skipping https://nujspd2024.calicotab.com/api/v1/tournaments/nujdpd2024 because it has a side that is not supported: aff
Failed to check if ballots are accessible for https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings: Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439459/ballots: 500. Defaulting to True to always try to fetch ballots.
[INFO] Skipping motion: THW activate the Downsize-inator from URL: https://tilburgopen2024.calicotab.com/api/v1/tournaments/TilburgOpen2024/motions because it has no rounds.
[INFO] Skipping motion: THP a world where children are raised in The Spartan System of Education from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[INFO] Skipping motion: THBT the CCP should abolish the Gaokao from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[INFO] Skipping motion: THO the Rise of Micro-credentialism from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[ERROR] Failed to fetch motions for URL: https://sido22.calicotab.com/api/v1/tournaments/sido22/motions, Failed to fetch motions for https://sido22.calicotab.com/api/v1/tournaments/sido22/motions: 401
[INFO] Skipping motion: THS a widespread adoption of debt-for nature swaps in financially distressed
developing countries from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: Olive finance refers to instances of private financial
institutions funding renewable projects by companies
that are heavily polluting in other parts of their
operations i.e. companies that are gradually shifting
from brown to green. from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: I) A sustainablity-focused hedge fund pools investor money and
uses multiple strategies to maximize the environmental impact of
their investments while trying to provide high returns to investors
II) Short selling is the act of borrowing shares from others and
selling them in the market with a hope that they can be bought
cheaper later. It is a strategy that speculates on the decline of the
stock's price in order to make a profit. from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: THS a widespread adoption of debt-for nature swaps in financially distressed
developing countries from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: Olive finance refers to instances of private financial
institutions funding renewable projects by companies
that are heavily polluting in other parts of their
operations i.e. companies that are gradually shifting
from brown to green. from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: THO the aestheticization of deviant behaviour amongst teenagers in TV shows and movies. (e.g. 13 Reasons Why, Euphoria) from URL: https://papilloniv.calicotab.com/api/v1/tournaments/papilloniv/motions because it has no rounds.
[INFO] Skipping motion: THO the aestheticization of deviant behaviour amongst teenagers in TV shows and movies. (e.g. 13 Reasons Why, Euphoria) from URL: https://papilloniv.calicotab.com/api/v1/tournaments/papilloniv/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439459/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439459/ballots: 500
[INFO] Skipping motion: This House would allow ex-convicts to join the police force from URL: https://wsdc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://edcup23.calicotab.com/api/v1/tournaments/edcup23/rounds/1/pairings/241889/ballots, Failed to fetch https://edcup23.calicotab.com/api/v1/tournaments/edcup23/rounds/1/pairings/241889/ballots: 500
[INFO] Skipping motion: THW ban translocation of animals from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[INFO] Skipping motion: THBT environmental movements should refuse funding from companies that have engaged in the practice of greenwashing. from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[INFO] Skipping motion: THBT environmentalists should prioritise campaigning for nuclear energy over renewable energy from URL: https://cvspd22.calicotab.com/api/v1/tournaments/cvspd23/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439460/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439460/ballots: 500
[INFO] Skipping motion: This House supports the Second Wave of the Pink Tide from URL: https://wsdc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: In area recently impacted by a natural disaster, THW freeze all price increases until inhabitants are back to safety from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT developing countries should heavily tax remittances from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT freight equalisation policy has done more harm than good from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: In area recently impacted by a natural disaster, THW freeze all price increases until inhabitants are back to safety from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT developing countries should heavily tax remittances from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT freight equalisation policy has done more harm than good from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: In area recently impacted by a natural disaster, THW freeze all price increases until inhabitants are back to safety from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT developing countries should heavily tax remittances from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THBT freight equalisation policy has done more harm than good from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://edcup23.calicotab.com/api/v1/tournaments/edcup23/rounds/1/pairings/241891/ballots, Failed to fetch https://edcup23.calicotab.com/api/v1/tournaments/edcup23/rounds/1/pairings/241891/ballots: 500
[INFO] Skipping motion: I) A sustainablity-focused hedge fund pools investor money and
uses multiple strategies to maximize the environmental impact of
their investments while trying to provide high returns to investors
II) Short selling is the act of borrowing shares from others and
selling them in the market with a hope that they can be bought
cheaper later. It is a strategy that speculates on the decline of the
stock's price in order to make a profit. from URL: https://malaysiauadc2023.calicotab.com/api/v1/tournaments/uadc2023/motions because it has no rounds.
[INFO] Skipping motion: TH predicts that the Paris Agreement's 2°C goal will be met as of 2050 from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[INFO] Skipping motion: THR the decline of Tesla from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439461/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439461/ballots: 500
[INFO] Skipping motion: This house, as China, would shift from 'wolf-warrior diplomacy' to cooperative and collaborative rhetoric in pursuit of its maritime and territorial claims. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: THBT the Iranian intervention in Gaza conflict will do more harm than good for Hamas. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: TH (as EU) will ask USA to abandon Ukraine. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: This house, as China, would shift from 'wolf-warrior diplomacy' to cooperative and collaborative rhetoric in pursuit of its maritime and territorial claims. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: THBT the Iranian intervention in Gaza conflict will do more harm than good for Hamas. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: TH (as EU) will ask USA to abandon Ukraine. from URL: https://kmcpresentsftd.calicotab.com/api/v1/tournaments/KMCpresentsFTD/motions because it has no rounds.
[INFO] Skipping motion: This House supports the Second Wave of the Pink Tide from URL: https://wsdc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439462/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439462/ballots: 500
[INFO] Skipping motion: TH predicts that the Paris Agreement's 2°C goal will be met as of 2050 from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[INFO] Skipping motion: THR the decline of Tesla from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[INFO] Skipping motion: TH prefers a world where all environmental action pushed solely for carbon reductions rather than carbon offsets from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[INFO] Skipping motion: TH, as a prominent female political leader, when promoted in a "Glass Cliff" situation, will choose to accept the position from URL: https://gambit25.calicotab.com/api/v1/tournaments/gambit/motions because it has no rounds.
[INFO] Skipping motion: THS rise of pleasure marriages in
Indonesia from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THW date them anyway from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: THO the demonisation of extra marital relationships from URL: https://cupd2025.calicotab.com/api/v1/tournaments/cupd25/motions because it has no rounds.
[INFO] Skipping motion: TH prefers a world where all environmental action pushed solely for carbon reductions rather than carbon offsets from URL: https://ado2025.calicotab.com/api/v1/tournaments/ado2025/motions because it has no rounds.
[INFO] Skipping motion: TH as a popular leader of Dalit community would fight from the ticket of Independent Dalit Political Party as opposed to Regional or National Party from URL: https://gambit25.calicotab.com/api/v1/tournaments/gambit/motions because it has no rounds.
[INFO] Skipping motion: THBT that political opposition parties should focus their electoral campaigns on portraying the voting base of the incumbent party as reasonable and rational, rather than portraying them as being manipulated through undemocratic means (e.g. disinformation on social media, historical revisionism, paid troll farms, etc.) from URL: https://gambit25.calicotab.com/api/v1/tournaments/gambit/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439463/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439463/ballots: 500
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439464/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439464/ballots: 500
[WARN] Failed to fetch ballot for URL: https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439465/ballots, Failed to fetch https://copenhagenopen25.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/439465/ballots: 500
[INFO] Skipping motion: This house, as the Vatican, W end its agreement with the Chinese Communist Party (CCP) from URL: https://gambit25.calicotab.com/api/v1/tournaments/gambit/motions because it has no rounds.

 38%|███▊      | 3/8 [19:34<33:34, 402.86s/it]

[ERROR] Failed to fetch tournament root info for url: https://southampton2024.calicotab.com/api/v1/tournaments/_
[ERROR] Failed to fetch tournament root info for url: https://northams2021.calicotab.com/api/v1/tournaments/northams2021
[INFO] Behind auth for URL https://srbp2023.calicotab.com/api/v1/tournaments/srbp2023/rounds/1/pairings/236855/ballots. Skipping extracting ballots...
[INFO] Skipping https://pratijja17.calicotab.com/api/v1/tournaments/pratijja because it has a side that is not supported: aff
[INFO] Behind auth for URL https://speechforces.calicotab.com/api/v1/tournaments/ao21/rounds/1/pairings/57074/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://bates2021.calicotab.com/api/v1/tournaments/bates2021/rounds/1/pairings/74989/ballots. Skipping extracting ballots...
[INFO] Skipping https://agahi.calicotab.com/api/v1/tournaments/agahix because it has a side that is not supported: aff
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/rookiewsdc2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://twsc.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/281237/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://doxbridge-worlds.calicotab.com/api/v1/tournaments/unified/rounds/1/pairings/17893/ballots. Skipping extracting ballots...
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/nwsdc2025 because it has a side that is not supported: aff
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/apwsdc2022 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://midp.calicotab.com/api/v1/tournaments/awsdo2023/rounds/1/pairings/69029/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://awdppakistanopen.calicotab.com/api/v1/tournaments/pakdo2021/rounds/1/pairings/55308/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/africaiv2022/rounds/1/pairings/84981/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://bdidf-bangladesh.calicotab.com/api/v1/tournaments/bdidfbangladesh/rounds/1/pairings/22989/ballots. Skipping extracting ballots...
[INFO] Skipping https://vilniusopen2024.calicotab.com/api/v1/tournaments/vilnius2024 because it has a side that is not supported: aff
[INFO] Skipping https://dope2025.calicotab.com/api/v1/tournaments/dope2025 because it has a side that is not supported: aff
[INFO] Skipping https://sasdc25.calicotab.com/api/v1/tournaments/sasdc25 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sido2024.calicotab.com/api/v1/tournaments/sido/rounds/1/pairings/290344/ballots. Skipping extracting ballots...
[INFO] Skipping https://iitpd2025.calicotab.com/api/v1/tournaments/iitpd2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://manchesterschools23.calicotab.com/api/v1/tournaments/manchesterschools23/rounds/1/pairings/205485/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://uclpcup24.calicotab.com/api/v1/tournaments/pcup2024/rounds/1/pairings/328603/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://sidc.calicotab.com/api/v1/tournaments/sidc/rounds/1/pairings/132974/ballots. Skipping extracting ballots...
[INFO] Skipping https://rahat2021.calicotab.com/api/v1/tournaments/rahat2024 because it has a side that is not supported: aff
[INFO] Skipping https://angkorwsdc.calicotab.com/api/v1/tournaments/angkorwsdc because it has a side that is not supported: aff
[INFO] Skipping https://pre-wsdc2025.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Behind auth for URL https://oldham2021.calicotab.com/api/v1/tournaments/oldhamAPAL/rounds/1/pairings/93036/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://dukeopen2022.calicotab.com/api/v1/tournaments/duke2022/rounds/1/pairings/128916/ballots. Skipping extracting ballots...
[INFO] Skipping https://pennwsdc2024.calicotab.com/api/v1/tournaments/pennwsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://iitmpd.calicotab.com/api/v1/tournaments/iitmpd24/rounds/1/pairings/271459/ballots. Skipping extracting ballots...
[INFO] Skipping https://usutabs2025.calicotab.com/api/v1/tournaments/pa2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://dsnpd2022.calicotab.com/api/v1/tournaments/dsnpd2022/rounds/1/pairings/136359/ballots. Skipping extracting ballots...
[INFO] Skipping https://sadebating.calicotab.com/api/v1/tournaments/sawsdc25 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://uhuru-worlds.calicotab.com/api/v1/tournaments/loxodonta/rounds/1/pairings/16498/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://vandy2024.calicotab.com/api/v1/tournaments/vandy2024/rounds/1/pairings/274333/ballots. Skipping extracting ballots...
[INFO] Skipping https://phdo2025.calicotab.com/api/v1/tournaments/phdo2025 because it has a side that is not supported: aff
[INFO] Skipping https://dope2024.calicotab.com/api/v1/tournaments/dope2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://pariswsdc.calicotab.com/api/v1/tournaments/pariswsdc2024/rounds/1/pairings/293373/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://ukrainedebates.calicotab.com/api/v1/tournaments/odesa2023/rounds/1/pairings/189825/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://suiv2022.calicotab.com/api/v1/tournaments/seattleiv2021/rounds/1/pairings/103070/ballots. Skipping extracting ballots...
[INFO] Skipping https://gambit23.calicotab.com/api/v1/tournaments/gambit23 because it has a side that is not supported: aff
Failed to check if ballots are accessible for https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings: Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440456/ballots: 500. Defaulting to True to always try to fetch ballots.
[INFO] Skipping motion: EC prefiere un mundo donde las relaciones sociales se rijan predominantemente bajo la perspectiva del entendimiento, por sobre la perspectiva de la responsabilidad. from URL: https://cmude2024.calicotab.com/api/v1/tournaments/open/motions because it has no rounds.
[INFO] Skipping motion: THS GAMIFICATION OF
THE WORKPLACE. from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS THE
 DEVELOPMENT OF AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS GAMIFICATION OF
THE WORKPLACE. from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS THE
 DEVELOPMENT OF AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS GAMIFICATION OF
THE WORKPLACE. from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS THE
 DEVELOPMENT OF AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: Assuming the legality of moonlighting, THBT private companies should reduce remuneration for moonlighters from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS gamification of the workplace from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS the development of AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS GAMIFICATION OF
THE WORKPLACE. from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS THE
DEVELOPMENT OF AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS GAMIFICATION OF
THE WORKPLACE. from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[INFO] Skipping motion: THS THE
DEVELOPMENT OF AGI from URL: https://gambit23.calicotab.com/api/v1/tournaments/gambit23/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440456/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440456/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440457/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440457/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440458/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440458/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440459/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440459/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440460/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440460/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440461/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440461/ballots: 500
[INFO] Skipping motion: TH, as the feminist movement, would advocate for the mandatory military service for women in countries where it is mandatory for men (e.g. Armenia, Singapore, South Korea etc.) from URL: https://bracu.calicotab.com/api/v1/tournaments/open2024/motions because it has no rounds.
[INFO] Skipping motion: TH, as the animal advocacy movement, would prioritise legislative reforms (e.g., banning factory farming, providing subsidies for farmers to switch from animal to crop agriculture, taxing meat consumption) over directly lobbying corporations (e.g., getting pledges that companies will adopt better practices, capacity building, increasing funding for switching to better practices, ethical sourcing) from URL: https://rahat2021.calicotab.com/api/v1/tournaments/rahat2024/motions because it has no rounds.
[INFO] Skipping motion: THBT animal advocates should prioritise efforts to reduce wild animal suffering (e.g. vaccination programs, combating wildlife trafficking, advocating for responsible fishing practices that avoid by-catch) over farmed animal suffering from URL: https://rahat2021.calicotab.com/api/v1/tournaments/rahat2024/motions because it has no rounds.
[INFO] Skipping motion: TH, as an animal advocate, would aim to decrease meat consumption rather than increase the availability of close meat substitutes (e.g., convincing restaurants to sell plant-based meat, funding research into cell-based meat alternatives) from URL: https://rahat2021.calicotab.com/api/v1/tournaments/rahat2024/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440462/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440462/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440463/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440463/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440464/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440464/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440465/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440465/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440466/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440466/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440467/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440467/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440468/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440468/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440469/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440469/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440470/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440470/ballots: 500
[WARN] Behind auth for URL https://budapestopen2024.calicotab.com/api/v1/tournaments/budapest2024/rounds/6/pairings. Skipping extracting ballots...
[WARN] Failed to fetch ballot for URL: https://warwick2025.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/441010/ballots, Failed to fetch https://warwick2025.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/441010/ballots: 500
[WARN] Behind auth for URL https://budapestopen2024.calicotab.com/api/v1/tournaments/budapest2024/rounds/7/pairings. Skipping extracting ballots...
[INFO] Skipping motion: THO the rise of these trends. from URL: https://rmlbpd23.calicotab.com/api/v1/tournaments/rmlbpd2023/motions because it has no rounds.
[INFO] Skipping motion: THO the rise of these trends. from URL: https://rmlbpd23.calicotab.com/api/v1/tournaments/rmlbpd2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440471/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440471/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440472/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/1/pairings/440472/ballots: 500
[INFO] Skipping motion: In areas where the supply of primary and secondary school classroom teachers significantly exceeds demand (e.g., parts of Türkiye, Namibia, Hong Kong), this house believes that only those who are socially progressive relative to prevailing local norms should become classroom teachers from URL: https://drexelprewudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440473/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440473/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440474/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440474/ballots: 500
[INFO] Skipping motion: This house, as Patti Smith, supports ending her romantic relationship with Robert Mapplethorpe from URL: https://drexelprewudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: This house, as Patti Smith, supports ending her romantic relationship with Robert Mapplethorpe from URL: https://drexelprewudc2025.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440475/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440475/ballots: 500
[INFO] Skipping motion: THBT the Securities and Exchange Board of India (SEBI) should significantly tighten restrictions on derivatives trading (e.g. limiting the availability of derivatives, implementing position limits and price limits, increasing the minimum trading amount) from URL: https://pkuproam25.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: THBT the Securities and Exchange Board of India (SEBI) should significantly tighten restrictions on derivatives trading (e.g. limiting the availability of derivatives, implementing position limits and price limits, increasing the minimum trading amount) from URL: https://pkuproam25.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440476/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440476/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440477/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440477/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440478/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440478/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440479/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440479/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440480/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440480/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440481/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440481/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440482/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440482/ballots: 500
[WARN] Failed to fetch ballot for URL: https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440483/ballots, Failed to fetch https://shahjiwana.calicotab.com/api/v1/tournaments/SIDC25/rounds/2/pairings/440483/ballots: 500
[INFO] Skipping motion: This House believes that the Philippine government should abandon all attempts at building a self-sufficient domestic agricultural sector from URL: https://psdc2024homecoming.calicotab.com/api/v1/tournaments/psdc2024/motions because it has no rounds.

 50%|█████     | 4/8 [26:00<26:24, 396.21s/it]

[ERROR] Failed to fetch tournament root info for url: https://dnn.calicotab.com/api/v1/tournaments/lawdebates
Failed to check if ballots are accessible for https://mace.calicotab.com/api/v1/tournaments/bso2021/rounds/1/pairings: list index out of range. Defaulting to True to always try to fetch ballots.
[INFO] Behind auth for URL https://midp.calicotab.com/api/v1/tournaments/apad2020/rounds/1/pairings/70394/ballots. Skipping extracting ballots...
Failed to check if ballots are accessible for https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/1/pairings: Failed to fetch https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/1/pairings: 404. Defaulting to True to always try to fetch ballots.
[INFO] Behind auth for URL https://midp.calicotab.com/api/v1/tournaments/yodo2021/rounds/1/pairings/69832/ballots. Skipping extracting ballots...
[INFO] Skipping https://wsdc2024.calicotab.com/api/v1/tournaments/wsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://aodc2024.calicotab.com/api/v1/tournaments/aodcwsdc/rounds/1/pairings/281776/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://stamesa23.calicotab.com/api/v1/tournaments/stamesa23/rounds/1/pairings/207230/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://bido2025.calicotab.com/api/v1/tournaments/bido2025/rounds/1/pairings/381883/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://nitdpd.calicotab.com/api/v1/tournaments/nitdpd24/rounds/1/pairings/205211/ballots. Skipping extracting ballots...
[INFO] Skipping https://dtusummers2023.calicotab.com/api/v1/tournaments/dtusummers2023 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://exeinv2025.calicotab.com/api/v1/tournaments/ExeInv2025/rounds/1/pairings/243883/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://ucl.calicotab.com/api/v1/tournaments/iv2021/rounds/1/pairings/83465/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/andl2021/rounds/1/pairings/84259/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://srcc.calicotab.com/api/v1/tournaments/shrirampreabp2022/rounds/1/pairings/81022/ballots. Skipping extracting ballots...
[INFO] Skipping https://anvaya.calicotab.com/api/v1/tournaments/anvayaapd25 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://argument.calicotab.com/api/v1/tournaments/ECO2024/rounds/1/pairings/174292/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://nzsdc2025.calicotab.com/api/v1/tournaments/nzsdc2025/rounds/1/pairings/410679/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://srcc.calicotab.com/api/v1/tournaments/shrirampreabp2021/rounds/1/pairings/80860/ballots. Skipping extracting ballots...
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/apwsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://doxbridge-2.calicotab.com/api/v1/tournaments/doxbridge2/rounds/1/pairings/18789/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://tahsinraian.calicotab.com/api/v1/tournaments/ulab/rounds/1/pairings/14991/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://hhiv2022.calicotab.com/api/v1/tournaments/hhiv2022/rounds/1/pairings/155142/ballots. Skipping extracting ballots...
[INFO] Skipping https://debateland.calicotab.com/api/v1/tournaments/gondwanawsdc because it has a side that is not supported: aff
[INFO] Behind auth for URL https://wudckorea.calicotab.com/api/v1/tournaments/2021/rounds/1/pairings/10881/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://eudc2021.calicotab.com/api/v1/tournaments/eudc2021/rounds/1/pairings/23296/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://doxbridge-3.calicotab.com/api/v1/tournaments/doxbridge3/rounds/1/pairings/18566/ballots. Skipping extracting ballots...
[INFO] Skipping https://bitsqed2023.calicotab.com/api/v1/tournaments/qed23 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/zodleliminations2021/rounds/1/pairings/84197/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://tabtastic.calicotab.com/api/v1/tournaments/econopen/rounds/1/pairings/49624/ballots. Skipping extracting ballots...
[INFO] Skipping https://uietpd.calicotab.com/api/v1/tournaments/UIETPD because it has a side that is not supported: aff
[INFO] Skipping https://intertext.calicotab.com/api/v1/tournaments/ipwsdc2023s because it has a side that is not supported: aff
[INFO] Skipping https://sasdc.calicotab.com/api/v1/tournaments/sasdc because it has a side that is not supported: aff
[INFO] Behind auth for URL https://cambridgeschools2025.calicotab.com/api/v1/tournaments/icyd2025/rounds/1/pairings/440081/ballots. Skipping extracting ballots...
[INFO] Skipping https://easters2025.calicotab.com/api/v1/tournaments/easters2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://abp2020.calicotab.com/api/v1/tournaments/abp2020/rounds/1/pairings/66523/ballots. Skipping extracting ballots...
[INFO] Skipping https://qduh.calicotab.com/api/v1/tournaments/QWSDC2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://cardiff2024.calicotab.com/api/v1/tournaments/c24/rounds/1/pairings/284998/ballots. Skipping extracting ballots...
[INFO] Skipping https://mnmpd2023.calicotab.com/api/v1/tournaments/mnmpd2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://bristolproam23.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/258546/ballots. Skipping extracting ballots...
[INFO] Skipping motion: THW ban zoos from URL: https://hhiv2022.calicotab.com/api/v1/tournaments/hhiv2022/motions because it has no rounds.
[INFO] Skipping motion: এই সংসদ, সহ-শিক্ষা কার্যক্রমের অন্তর্ভুক্ত অনুষ্ঠানে রাজনৈতিক ব্যক্তিবর্গের অতিথিকরণের প্রবণতাকে নিরুৎসাহিত করবে। from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Skipping motion: এই সংসদ, অমর একুশে বইমেলা-কে আন্তর্জাতিকীকরণ করবে। from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Skipping motion: THBT former colonial powers should remove all restrictions on immigration for citizens of their former colonies from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Skipping motion: This house as an educated woman regrets the rise of microfinance Institutions from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Skipping motion: TH, as a child with newly discovered supernatural powers, would give up those powers in exchange for a normal life. from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Skipping motion: This House opposes the stigma against laziness (i.e hustle culture or overglorification of hard work) from URL: https://muhib.calicotab.com/api/v1/tournaments/EMO/motions because it has no rounds.
[INFO] Behind auth for URL https://sxc.calicotab.com/api/v1/tournaments/xdf2023/rounds/1/pairings/181045/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://upenn2021.calicotab.com/api/v1/tournaments/worlds/rounds/1/pairings/89764/ballots. Skipping extracting ballots...
[INFO] Skipping https://trivium2024.calicotab.com/api/v1/tournaments/trivium2024 because it has a side that is not supported: aff
[INFO] Skipping https://columbiawsdc2025.calicotab.com/api/v1/tournaments/columbiawsdc2025 because it has a side that is not supported: aff
[INFO] Skipping motion: TH as religious leaders should promise reward in the afterlife as opposed to promising material reward in this life, with both outcomes contingent on faithful practice from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THBT foreign-based NGOs operating in countries with fragile democracies should cease efforts to push for political change (e.g. democratization, lobby for policy changes, re-education of the population, etc.) and instead focus solely on the provision of essential services on the ground (e.g. food drives, vaccinations, building livable communities, etc.) from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THO rebound relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THBT hustle culture has done more harm than good for feminism from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THBT women in leadership should emphasise traditionally feminine traits (e.g., Jacinda Ardern and kindness) as opposed to traditionally masculine traits (e.g., Angela Merkel and strength, Sheryl Sandberg and leaning in). from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH as the feminist movement prefers legislative change over court battles for their rights from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH, as an NGO, would target investors rather than consumers when pressurising companies from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THW implement a gender rotation policy for lead public roles (e.g. Prime Minister; cabinet members) from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THW will allow prisoners of violent crimes to participate in experimental lifesaving drug trials for lesser punishment from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH, as the government of a developing country, would take active measures to limit the spread of American pop culture from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THR the popularization of dramatization of mental health issues in popular culture from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH regrets the prominence of pop culture celebrities in feminist discourse from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THW take a pill that permanently made one entirely contented with one's current life situation from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THP a world where humans can
 measure the amount of pleasure
 they'll experience in a relationship
 before entering it from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the
 stigmatisation of “neediness” in
 interpersonal relationships from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THW ban zoos from URL: https://ndcdiliman2022.calicotab.com/api/v1/tournaments/NDCDiliman2022/motions because it has no rounds.
Failed to check if ballots are accessible for https://iimapd25.calicotab.com/api/v1/tournaments/iimapd25/rounds/1/pairings: Failed to fetch https://iimapd25.calicotab.com/api/v1/tournaments/iimapd25/rounds/1/pairings/436820/ballots: 500. Defaulting to True to always try to fetch ballots.
[WARN] First team in sheet is not a valid BP position: https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/4/pairings/427190/ballots. Skipping extracting ballots...
[WARN] First team in sheet is not a valid BP position: https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/0/pairings/425811/ballots. Skipping extracting ballots...
[INFO] Skipping motion: THS the use of Artificial Intelligence in
Parliamentary Debating Tournaments at
the University level from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THW decide breaks based on total speaks
as opposed to team points from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: TH, as Maras Hilari, W date in the
debating circuit from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THS the use of Artificial Intelligence in
Parliamentary Debating Tournaments at
the University level from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THW decide breaks based on total speaks
as opposed to team points from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: TH, as Maras Hilari, W date in the
debating circuit from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THBT AI companies should be held liable
for the output generated by their Large
Language models (eg. ChatGPT, Claude
etc) from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THO the prioritisation of AGI safety over
ANI safety from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THS the use of genetic engineering as
depicted in “Oryx and Crake” from URL: https://uietpd.calicotab.com/api/v1/tournaments/UIETPD/motions because it has no rounds.
[INFO] Skipping motion: THS the US Democrats’ strategy of
 boosting far-right extremist
 candidates in Republican primaries from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: In a liberal democratic state, THW
 suspend elections in a period of
 economic crisis from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH regrets the prominence of pop
 culture celebrities in political
 discourse from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THS the US Democrats’ strategy of boosting far-right extremist candidates in Republican primaries from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: In a liberal democratic state, THW suspend elections in a period of economic crisis from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH regrets the prominence of pop culture celebrities in political discourse from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THS the US Democrats’ strategy of boosting far-right extremist candidates in Republican primaries from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: In a liberal democratic state, THW suspend elections in a period of economic crisis from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH regrets the prominence of pop culture celebrities in political discourse from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: THS the US Democrats’ strategy of boosting far-right extremist candidates in Republican primaries from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: In a liberal democratic state, THW suspend elections in a period of economic crisis from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[INFO] Skipping motion: TH regrets the prominence of pop culture celebrities in political discourse from URL: https://sxc.calicotab.com/api/v1/tournaments/xdf2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://iimapd25.calicotab.com/api/v1/tournaments/iimapd25/rounds/2/pairings/436831/ballots, Failed to fetch https://iimapd25.calicotab.com/api/v1/tournaments/iimapd25/rounds/2/pairings/436831/ballots: 500
[WARN] Failed to fetch ballot for URL: https://ppiv2021.calicotab.com/api/v1/tournaments/ppiv2021/rounds/1/pairings/21492/ballots, Failed to fetch https://ppiv2021.calicotab.com/api/v1/tournaments/ppiv2021/rounds/1/pairings/21492/ballots: 500
[WARN] First team in sheet is not a valid BP position: https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/0/pairings/425811/ballots. Skipping extracting ballots...
[WARN] Multiple sheets at URL: https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/2/pairings/425898/ballots. Using only the first sheet.
[WARN] First team in sheet is not a valid BP position: https://unswtabs2025.calicotab.com/api/v1/tournaments/preaustrals2025/rounds/2/pairings/425898/ballots. Skipping extracting ballots...
[INFO] Skipping motion: THW make Luigi Mangione's trial a

 62%|██████▎   | 5/8 [31:24<18:30, 370.07s/it]

[INFO] Skipping https://australs2019.calicotab.com/api/v1/tournaments/australs2019 because it has a side that is not supported: aff
[INFO] Skipping https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025 because it has a side that is not supported: aff
[INFO] Skipping https://asdc2025.calicotab.com/api/v1/tournaments/asdc2025 because it has a side that is not supported: aff
[INFO] Skipping https://iwsdc2023.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Skipping https://kmcpresentsftd.calicotab.com/api/v1/tournaments/ftd44 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sunwaydebate.calicotab.com/api/v1/tournaments/sundo2023/rounds/1/pairings/129791/ballots. Skipping extracting ballots...
[INFO] Skipping https://rmlpd12.calicotab.com/api/v1/tournaments/rmlpd12 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://norams2023.calicotab.com/api/v1/tournaments/norams2023/rounds/1/pairings/185389/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://tabtastic.calicotab.com/api/v1/tournaments/theologyopen2021/rounds/1/pairings/49695/ballots. Skipping extracting ballots...
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/apwsdc2023 because it has a side that is not supported: aff
[INFO] Skipping https://usutabs2025.calicotab.com/api/v1/tournaments/usuopen2025 because it has a side that is not supported: aff
[INFO] Skipping https://northams2025.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Skipping https://midp.calicotab.com/api/v1/tournaments/awsdo2022 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://papilloniv2024.calicotab.com/api/v1/tournaments/papillon2024/rounds/1/pairings/301616/ballots. Skipping extracting ballots...
[INFO] Skipping https://malaysiauadc2022.calicotab.com/api/v1/tournaments/malaysiauadc2022 because it has a side that is not supported: aff
[INFO] Skipping https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22 because it has a side that is not supported: aff
[INFO] Skipping https://westernhighschools.calicotab.com/api/v1/tournaments/westernwsdc2025 because it has a side that is not supported: aff
[INFO] Skipping https://australs2022.calicotab.com/api/v1/tournaments/australs2022 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/tco2021/rounds/1/pairings/84725/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://bpchamps2022.calicotab.com/api/v1/tournaments/bpchamps22/rounds/1/pairings/120797/ballots. Skipping extracting ballots...
[INFO] Skipping https://pds2024.calicotab.com/api/v1/tournaments/pds2024 because it has a side that is not supported: aff
[INFO] Skipping https://dtusummers2025.calicotab.com/api/v1/tournaments/dtusummers2025 because it has a side that is not supported: aff
[INFO] Skipping motion: dss from URL: https://luzonintervarsity.calicotab.com/api/v1/tournaments/liv2022/motions because it has no rounds.
[INFO] Behind auth for URL https://westerniv.calicotab.com/api/v1/tournaments/westerniv2022/rounds/1/pairings/155164/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://mace1996.calicotab.com/api/v1/tournaments/heartsafire/rounds/1/pairings/85093/ballots. Skipping extracting ballots...
[INFO] Skipping https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023 because it has a side that is not supported: aff
[INFO] Skipping https://nlujpd2023.calicotab.com/api/v1/tournaments/nlujpd2023 because it has a side that is not supported: aff
[INFO] Skipping https://usutabs2025.calicotab.com/api/v1/tournaments/grandslam because it has a side that is not supported: aff
[INFO] Behind auth for URL https://siiv2023.calicotab.com/api/v1/tournaments/siiv2023/rounds/1/pairings/241097/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://sheffieldnovices23.calicotab.com/api/v1/tournaments/sheffieldnovices2023/rounds/1/pairings/251197/ballots. Skipping extracting ballots...
[INFO] Skipping https://easters2022.calicotab.com/api/v1/tournaments/easters2022 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://mnbpd2025.calicotab.com/api/v1/tournaments/mnbpd2025/rounds/1/pairings/348781/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://kclproam2020.calicotab.com/api/v1/tournaments/kclproam2020/rounds/1/pairings/66799/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://bdidf.calicotab.com/api/v1/tournaments/bdidf/rounds/1/pairings/23010/ballots. Skipping extracting ballots...
[INFO] Skipping https://upenndebate.calicotab.com/api/v1/tournaments/pennwsdc2025 because it has a side that is not supported: aff
[INFO] Skipping https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025 because it has a side that is not supported: aff
[INFO] Skipping motion: This House regrets the removal of the gold standard from URL: https://capitalismiv2024.calicotab.com/api/v1/tournaments/capitalismiv2024/motions because it has no rounds.
[INFO] Skipping motion: Assuming the Colombian Government would support it, this House believes that drug chemists employed by Colombian cartels should unionise from URL: https://capitalismiv2024.calicotab.com/api/v1/tournaments/capitalismiv2024/motions because it has no rounds.
[INFO] Skipping motion: This House prefers a world where corporations do not have separate legal personality from URL: https://capitalismiv2024.calicotab.com/api/v1/tournaments/capitalismiv2024/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the societal pressure to move on from grief from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Supports the narrative that monetising sexuality is empowering for women from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the narrative that parents should prioritise the interests of their children over their own from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the societal pressure to move on from grief from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Supports the narrative that monetising sexuality is empowering for women from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the narrative that parents should prioritise the interests of their children over their own from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the societal pressure to move on from grief from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Supports the narrative that monetising sexuality is empowering for women from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes the narrative that parents should prioritise the interests of their children over their own from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[ERROR] Failed to fetch motions for URL: https://mace.calicotab.com/api/v1/tournaments/tco2021/motions, Failed to fetch motions for https://mace.calicotab.com/api/v1/tournaments/tco2021/motions: 401
[INFO] Skipping https://hindu.calicotab.com/api/v1/tournaments/Premchand2025 because it has a side that is not supported: aff
[INFO] Skipping motion: QWERTY from URL: https://wudc2022.calicotab.com/api/v1/tournaments/wudc/motions because it has no rounds.
[INFO] Skipping motion: THR the dominance of the ""evil west"" narrative in academic circles from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THW exempt academic disputes from defamation law. from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: Assuming the technology exists, THS the use of augmented eternity for people in highly influential positions (e.g: top academics, researchers, CEOs or politicians) from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THR the dominance of the "evil west" narrative in academic circles from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: Assuming the technology exists, THS the use of augmented eternity for people in highly influential positions (e.g: top academics, researchers, CEOs or big politicians) from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THW exempt academic disputes from defamation law. from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THBT the shift from long-cycle development into short-cycle development in technology and engineering has done more harm than good. from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THO the rise of "anti aging technology" firms from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THR the reinstatement of Sam Altman from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THBT the shift from long-cycle development into short-cycle development in technology and engineering has done more harm than good. from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THO the rise of "anti aging technology" firms from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THR the reinstatement of Sam Altman from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THR SEBI's decision to limit options contracts to weekly expiries from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THS the rise of microfinance in developing countries from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THW prohibit hedge funds from purchasing sovereign debt issued by countries nearing insolvency. from URL: https://ashokapd.calicotab.com/api/v1/tournaments/ashokapd2025/motions because it has no rounds.
[INFO] Skipping motion: THBT the co-option of indigenous and minority languages, art and culture for fantasy and sci-fi worldbuilding has done more harm than good. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THW disallow major production studios (e.g., Warner Bros, Netflix, Disney, Paramount) from producing 'true story' films unless they adhere to archival standards of truthfulness. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THBT media companies should be forced to provide a right to reply to op-eds. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THBT the co-option of indigenous and minority languages, art and culture for fantasy and sci-fi worldbuilding has done more harm than good. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THW disallow major production studios (e.g., Warner Bros, Netflix, Disney, Paramount) from producing 'true story' films unless they adhere to archival standards of truthfulness. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THBT media companies should be forced to provide a right to reply to op-eds. from URL: https://dilimanap2025.calicotab.com/api/v1/tournaments/dilimanap2025/motions because it has no rounds.
[INFO] Skipping motion: THBT the ANC of South Africa should arrest Putin if he enters domestic soil. from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: This house would lift sanctions on Iran in exchange for the withdrawal of support for Russia from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THBT the US and EU should seek to promote peace by heavily subsidising Israeli businesses who invest in the Palestinian territories from URL: https://mukhtalif2023.calicotab.com/api/v1/tournaments/mukhtalif2023/motions because it has no rounds.
[INFO] Skipping motion: THS the implementation of the Rooney Rule in elite football (soccer). from URL: https://technion2023.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: THW allow people to sue media companies over harms that are created due to factual misinformation that they published. from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: THW aggressively promote space exploration from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: THW require media outlets to host both ends of the political spectrum from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: THW allow people to sue media companies over harms that are created due to factual misinformation that they published. from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: THW aggressively promote space exploration from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: THW require media outlets to host both ends of the political spectrum from URL: https://bitspilanipd.calicotab.com/api/v1/tournaments/niqash-22/motions because it has no rounds.
[INFO] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: A: That we support character integrity obligations clauses from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: B: That all law firms should be forced to adopt a lockstep model of compensation rather than an 'eat what you kill' model of compensation from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: C: That regulators should implement the Platform Utility model of anti-trust action from URL: https://easters2022.calicotab.com/api/v1/tournaments/easters2022/motions because it has no rounds.
[INFO] Skipping motion: THR the trend of the "f2p" business model in gaming from URL: https://makdo.calicotab.com/api/v1/tournaments/makdo2023/motions because it has no rounds.
[INFO] Skipping motion: This House supports breaking up the Big Four from URL: https://capitalismiv2024.calicotab.com/api/v1/tournaments/capitalismiv2024/motions because it has no rounds.
[INFO] Skipping motion: TH, as an average North East Asian, would opt into the belief that all morality is artificially constructed. from URL: https://macaudebateopen2025.calicotab.com/api/v1/tournaments/macaudebateopen2025/motions because it has no rounds.
[INFO] Skipping motion: This House would require the annual percentage of salary increase in all sectors to be much closely pegged to the increase of national inflation rate from URL: https://dnn.calicotab.com/api/v1/tournaments/ms2024/motions because it has no rounds.
[INFO] Skipping motion: This House would require the annual percentage of salary increase in all sectors to be much closely pegged to the increase of national inflation rate from URL: https://dnn.calicotab.com/api/v1/tournaments/ms2024/motions because it has no rounds.
[INFO] Skipping motion: This House Prefers a world where all humanity knew of the existence of Roko’s Basilisk from URL: https://iitroorkee.calicotab.com/api/v1/tournaments/iitrpd2025/motions because it has no rounds.
[INFO] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[INFO] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[INFO] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[INFO] Skipping motion: THS the resurgence of Industrial Policy as a tool for spurring economic growth from URL: https://edudrift.calicotab.com/api/v1/tournaments/abp2024/motions because it has no rounds.
[INFO] Skipping motion: THS dual-legal systems in countries with religious minorities from URL: https://peoplespeak2025.calicotab.com/api/v1/tournaments/peoplespeak2025/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://johnshopkinsopen2022.calicotab.com/api/v1/tournaments/jhu2022/rounds/11/pairings/136248/ballots, Expected 1 ballot for pairing URL: https://johnshopkinsopen2022.calicotab.com/api/v1/tournaments/jhu2022/rounds/11/pairings/136248/ballots
[ERROR] Failed to fetch round for URL: https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/1, Failed to fetch round for https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/1: 404
[ERROR] Failed to fetch round for URL: https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/2, Failed to fetch round for https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/2: 404
[ERROR] Failed to fetch round for URL: https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/3, Failed to fetch round for https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/3: 404
[ERROR] Failed to fetch round for URL: https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/4, Failed to fetch round for https://wudc2018.calicotab.com/api/v1/tournaments/pw2019/rounds/4: 404

 75%|███████▌  | 6/8 [36:29<11:36, 348.08s/it]

[ERROR] Failed to fetch tournament root info for url: https://berlinopen2023.calicotab.com/api/v1/tournaments/berlinopen2023
[INFO] Behind auth for URL https://mace.calicotab.com/api/v1/tournaments/zimbabwewsdc2025/rounds/1/pairings/368698/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://uhuru-worlds.calicotab.com/api/v1/tournaments/panthera/rounds/1/pairings/16381/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://hkpds2022.calicotab.com/api/v1/tournaments/hkpds/rounds/1/pairings/163256/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://wst2024.calicotab.com/api/v1/tournaments/wst2024/rounds/1/pairings/288742/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://debatefoster.calicotab.com/api/v1/tournaments/KO2025/rounds/1/pairings/268614/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://sbs.calicotab.com/api/v1/tournaments/sbsbpd22/rounds/1/pairings/112219/ballots. Skipping extracting ballots...
[INFO] Skipping https://pidc24.calicotab.com/api/v1/tournaments/transformtradition because it has a side that is not supported: aff
[INFO] Skipping https://taydo2022.calicotab.com/api/v1/tournaments/tap2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://wst.calicotab.com/api/v1/tournaments/harvardwst2025/rounds/1/pairings/381209/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://anudc.calicotab.com/api/v1/tournaments/anudc2024/rounds/1/pairings/115007/ballots. Skipping extracting ballots...
[INFO] Skipping https://australs2021.calicotab.com/api/v1/tournaments/_ because it has a side that is not supported: aff
[INFO] Behind auth for URL https://kinnairdurduopen21.calicotab.com/api/v1/tournaments/kcdcenglish22/rounds/1/pairings/89086/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://2001rean.calicotab.com/api/v1/tournaments/KO2024/rounds/1/pairings/226663/ballots. Skipping extracting ballots...
Failed to check if ballots are accessible for https://camschoolsfinals22.calicotab.com/api/v1/tournaments/finalsday/rounds/1/pairings: Failed to fetch https://camschoolsfinals22.calicotab.com/api/v1/tournaments/finalsday/rounds/1/pairings: 401. Defaulting to True to always try to fetch ballots.
[INFO] Behind auth for URL https://eudc2020.calicotab.com/api/v1/tournaments/eudc2020/rounds/1/pairings/18001/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://uspopen2024.calicotab.com/api/v1/tournaments/open2024/rounds/1/pairings/345448/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://intertext.calicotab.com/api/v1/tournaments/ipa2024/rounds/1/pairings/141869/ballots. Skipping extracting ballots...
[INFO] Skipping https://vanprewsdc2025.calicotab.com/api/v1/tournaments/vancouverprewsdc2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://indiawudcfundraiser.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/262727/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://oxwsdc2021.calicotab.com/api/v1/tournaments/oxwsdc2021/rounds/1/pairings/54853/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://ubcwsdcsummer2024.calicotab.com/api/v1/tournaments/ubcwsdc2024/rounds/1/pairings/307605/ballots. Skipping extracting ballots...
[INFO] Skipping https://mwsdes.calicotab.com/api/v1/tournaments/miwsdc2024 because it has a side that is not supported: aff
[INFO] Skipping motion: THW end all state-run gifted education programs from URL: https://iiuminterschooldebatingchampionship2023.calicotab.com/api/v1/tournaments/iiumopen2024/motions because it has no rounds.
[INFO] Behind auth for URL https://oxschoolssg2025.calicotab.com/api/v1/tournaments/oxschoolssg2025/rounds/1/pairings/50093/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://nutifafapaudc.calicotab.com/api/v1/tournaments/paudc2023/rounds/1/pairings/260556/ballots. Skipping extracting ballots...
[INFO] Skipping motion: THW prioritize the selection of foreign-based players over local players for national teams in international competitions from URL: https://anudc.calicotab.com/api/v1/tournaments/anudc2024/motions because it has no rounds.
[INFO] Skipping https://transpacificwsdc.calicotab.com/api/v1/tournaments/transpacificwsdc because it has a side that is not supported: aff
[INFO] Skipping motion: THW ban financial service institutions from refusing service to industries perceived as immoral (for example, Mastercard refusing service to OnlyFans) from URL: https://luzonintervarsity.calicotab.com/api/v1/tournaments/liv2021/motions because it has no rounds.
[INFO] Behind auth for URL https://uhuru-worlds.calicotab.com/api/v1/tournaments/uw2021outrounds/rounds/1/pairings/16680/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://dtupd2021.calicotab.com/api/v1/tournaments/dtupd2021/rounds/1/pairings/102903/ballots. Skipping extracting ballots...
[INFO] Skipping https://tabtastic.calicotab.com/api/v1/tournaments/popposting2021 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://indopacific2023.calicotab.com/api/v1/tournaments/ipwsdc/rounds/1/pairings/241216/ballots. Skipping extracting ballots...
[INFO] Skipping https://psdctab2023.calicotab.com/api/v1/tournaments/psdc2023 because it has a side that is not supported: aff
[INFO] Skipping https://axiom23.calicotab.com/api/v1/tournaments/axiom2024 because it has a side that is not supported: aff
[INFO] Skipping https://gba2024.calicotab.com/api/v1/tournaments/gba because it has a side that is not supported: aff
[INFO] Skipping https://dnn.calicotab.com/api/v1/tournaments/eiwsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://zhmasud.calicotab.com/api/v1/tournaments/euphorianoviceopen/rounds/1/pairings/55180/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://standrewsprewsdc.calicotab.com/api/v1/tournaments/standrewsprewsdc/rounds/1/pairings/304548/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://paqo2020.calicotab.com/api/v1/tournaments/proam/rounds/1/pairings/75438/ballots. Skipping extracting ballots...
[INFO] Skipping https://speakup13.calicotab.com/api/v1/tournaments/speakup13 because it has a side that is not supported: aff
[INFO] Skipping https://debateland.calicotab.com/api/v1/tournaments/PangeaWSDC24 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://lo2025.calicotab.com/api/v1/tournaments/lo2025/rounds/1/pairings/356148/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://uclpresidents2021.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/100646/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://cmudeecuador2021.calicotab.com/api/v1/tournaments/cmudeecuador2021/rounds/1/pairings/56095/ballots. Skipping extracting ballots...
[INFO] Skipping https://easters2024.calicotab.com/api/v1/tournaments/easters2024 because it has a side that is not supported: aff
[INFO] Skipping https://symcharcha2023.calicotab.com/api/v1/tournaments/symcharcha23 because it has a side that is not supported: aff
[INFO] Skipping https://harvardanz2024.calicotab.com/api/v1/tournaments/HarvardANZ2024 because it has a side that is not supported: aff
[INFO] Skipping https://ufd.calicotab.com/api/v1/tournaments/ipwsdo24 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://sido2025.calicotab.com/api/v1/tournaments/sido2025/rounds/1/pairings/390906/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://uhuruworlds2024.calicotab.com/api/v1/tournaments/uhuruworlds2024/rounds/1/pairings/307022/ballots. Skipping extracting ballots...
[INFO] Skipping https://seasons.calicotab.com/api/v1/tournaments/spwsdc2025 because it has a side that is not supported: aff
[INFO] Skipping motion: THW adopt a UBI system in all states that have been hit by a climate crisis. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This House supports the implementation of a universal basic income (UBI) system during times triggered by climate change. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house believes that economic growth is the solution to climate change. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: Resolved: Rich nations should pay poor nations a carbon foot print tax as reparations for both historical and current global warming. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house would require environmental policy decisions be made by an independent panel of experts. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house believes that social movements should adopt the concept of Ecological Supremacy. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house would lift patents on technologies designed to deal with environmental concerns. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: THW transfer all physical features from national government to the hands of international organizations. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house would introduce a deposit-return scheme for plastic bottles to promote recycling and reduce littering. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[WARN] Behind auth for URL https://camschoolsfinals22.calicotab.com/api/v1/tournaments/finalsday/rounds/1/pairings. Skipping extracting ballots...
[INFO] Skipping motion: This house prefers Hades to Poseidon. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house, as the government of Uganda, would subject the EACOP project to mandatory Carbon financing. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house prefers Hades to Poseidon. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: THBT citizens should be solely responsible for the fight against climate change. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[WARN] Behind auth for URL https://camschoolsfinals22.calicotab.com/api/v1/tournaments/finalsday/rounds/2/pairings. Skipping extracting ballots...
[WARN] Failed to fetch ballot for URL: https://sunwaydebate.calicotab.com/api/v1/tournaments/sundo2024/rounds/8/pairings/130411/ballots, Expected 1 ballot for pairing URL: https://sunwaydebate.calicotab.com/api/v1/tournaments/sundo2024/rounds/8/pairings/130411/ballots
[INFO] Skipping motion: This House believes that BRICS expansion is in the interests of Latin American nations from URL: https://seasons.calicotab.com/api/v1/tournaments/spwsdc2025/motions because it has no rounds.
[INFO] Skipping motion: This House believes that BRICS expansion is in the interests of Latin American nations from URL: https://seasons.calicotab.com/api/v1/tournaments/spwsdc2025/motions because it has no rounds.
[INFO] Skipping motion: This House believes that BRICS expansion is in the interests of Latin American nations from URL: https://seasons.calicotab.com/api/v1/tournaments/spwsdc2025/motions because it has no rounds.
[INFO] Skipping motion: THBT The Fight Against Climate Change Should Include Taking International Action Against Sovereign Countries from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This House Opposes China's Advancement in Artificial Intelligence from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This House Would Declare a global climate emergency from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house believes that increased digitalization is the key to achieving transparency and accountability in public and private institutions. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: For a sustainable fight, this house contends that international partnerships are essential, even if they potentially compromise national sovereignty. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house believes that corporate entities should be legally obligated to actively contribute to anti-corruption efforts through robust Corporate Social Responsibility (CSR) initiatives. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: To build and ensure continued corruption reporting, this house would trade off the current Whistleblowers Act for a better alternative. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house would heavily invest in TTAC AI. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: THBT exposure of the corrupt is an effective tool to fight Corruption. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: THP a world where whistleblower clubs are part of School curriculum and are compulsory for all students. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: This house opposes the idea that resignation is an adequate response to scandals involving government officials in Uganda. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[INFO] Skipping motion: THS the online demonization of perceived corrupt government officials. from URL: https://2001rean.calicotab.com/api/v1/tournaments/KO2024/motions because it has no rounds.
[WARN] Behind auth for URL https://camschoolsfinals22.calicotab.com/api/v1/tournaments/finalsday/rounds/3/pairings. Skipping extracting ballots...
[INFO] Skipping motion: In developing countries, THW prioritize encouraging female pariticipation in the labour market, over encouraging them to pursue academic success from URL: https://indiawudcfundraiser.calicotab.com/api/v1/tournaments/_/motions because it has no rounds.
[INFO] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[INFO] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[INFO] Skipping motion: That we prefer a world in which Veritaserum was in the global water supply. from URL: https://easters2024.calicotab.com/api/v1/tournaments/easters2024/motions because it has no rounds.
[INFO] Skipping motion: This house believes that the state should fully compensate the victims of crimes committed by recidivist criminals from URL: https://dnn.calicotab.com/api/v1/tournaments/eiwsdc2024/motions because it has no rounds.
[INFO] Skipping motion: THR the use of standardized testing as the predominant method of recruiting civil servants in India from URL: https://vaagyudh2024.calicotab.com/api/v1/tournaments/dialectica2024/motions because it has no rounds.
[INFO] Skipping motion: THR the use of standardized testing as the predominant method of recruiting civil servants in India from URL: https://vaagyudh2024.calicotab.com/api/v1/tournaments/dialectica2024/motions because it has no rounds.
[INFO] Skipping motion: THBT the environmentalist movement should actively disrupt new CO2 emitting assets from URL: https://bulacaniv2023.calicotab.com/api/v1/tournaments/bliv2023/motions because it has no rounds.
[INFO] Skipping motion: THS states actively pushing for the integration of eSports into government institutions (e.g: eSports being an extracurricular activity in government schools, eSports leagues subsidised by the state, eSports scholarships, etc.) from URL: https://bulacaniv2023.calicotab.com/api/v1/tournaments/bliv2023/motions because it has no rounds.
[INFO] Skipping motion: Assuming the technology exists, THBT it is immoral to create simulated high-fidelity alternate universes. from URL: https://bulacaniv2023.calicotab.com/api/v1/tournaments/bliv2023/motions because it has no rounds.
[INFO] Skipping motion: THBT athletes from developing countries should accept the "offer" from URL: https://bulacaniv2023.calicotab.com/api/v1/tournaments/bliv2023/motions because it has no rounds.
[INFO] Skipping motion: TH, as an average middle class individual in a developing nation, would embrace whimsical nihilism from URL: https://bulacaniv2023.calicotab.com/api/v1/tournaments/bliv2023/motions because it has no rounds.
[INFO] Skipping motion: THS narratives that diversity is instrumentally valuable rather than morally right from URL: https://western2023.calicotab.com/api/v1/tournaments/western2023/motions because it has no rounds.

 88%|████████▊ | 7/8 [40:38<05:15, 315.77s/it]

[INFO] Behind auth for URL https://helsinkiopen2021.calicotab.com/api/v1/tournaments/helsinki2021/rounds/1/pairings/26105/ballots. Skipping extracting ballots...
[INFO] Skipping https://norams2024.calicotab.com/api/v1/tournaments/norams2024 because it has a side that is not supported: aff
[INFO] Skipping https://krabiaustrals2023.calicotab.com/api/v1/tournaments/australs2023 because it has a side that is not supported: aff
[INFO] Skipping https://oxfordwsdc2025.calicotab.com/api/v1/tournaments/2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://lums.calicotab.com/api/v1/tournaments/lumsiv25/rounds/1/pairings/391925/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://midp.calicotab.com/api/v1/tournaments/wdo2022/rounds/1/pairings/68508/ballots. Skipping extracting ballots...
[INFO] Skipping https://uqpreaustrals2025.calicotab.com/api/v1/tournaments/uqpa2025 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://midp.calicotab.com/api/v1/tournaments/awsdo2024/rounds/1/pairings/71081/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://sserigaproamvii.calicotab.com/api/v1/tournaments/Pro-AmVIII/rounds/1/pairings/328251/ballots. Skipping extracting ballots...
[INFO] Skipping https://scottishschoolsdebating.calicotab.com/api/v1/tournaments/thistlecup2023 because it has a side that is not supported: aff
[INFO] Skipping https://seasons.calicotab.com/api/v1/tournaments/swsdc2024 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://pennworldschools22.calicotab.com/api/v1/tournaments/2022/rounds/1/pairings/119099/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://princetoniv2021.calicotab.com/api/v1/tournaments/princetoniv2021/rounds/1/pairings/96276/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://berlinonlineiv2020.calicotab.com/api/v1/tournaments/bivonline2020/rounds/1/pairings/25170/ballots. Skipping extracting ballots...
[INFO] Skipping https://srcc.calicotab.com/api/v1/tournaments/srdf2022 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://cudc2024.calicotab.com/api/v1/tournaments/_/rounds/1/pairings/340100/ballots. Skipping extracting ballots...
[INFO] Skipping https://thistlecup2025.calicotab.com/api/v1/tournaments/thistlecup2025 because it has a side that is not supported: aff
[INFO] Skipping https://fndo24.calicotab.com/api/v1/tournaments/24fndo because it has a side that is not supported: aff
[INFO] Behind auth for URL https://nsut.calicotab.com/api/v1/tournaments/nsmpd25/rounds/1/pairings/387871/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://intertext.calicotab.com/api/v1/tournaments/ipabp2023/rounds/1/pairings/142391/ballots. Skipping extracting ballots...
[INFO] Skipping https://cbs.calicotab.com/api/v1/tournaments/cbspd23 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://aodcjunior2024.calicotab.com/api/v1/tournaments/aodc/rounds/1/pairings/326638/ballots. Skipping extracting ballots...
[INFO] Behind auth for URL https://aodcbp2023.calicotab.com/api/v1/tournaments/aodcbp23/rounds/1/pairings/246519/ballots. Skipping extracting ballots...
[INFO] Skipping https://awsdc2025.calicotab.com/api/v1/tournaments/AWSDC2025 because it has a side that is not supported: aff
[INFO] Skipping https://srcc.calicotab.com/api/v1/tournaments/srdf2023 because it has a side that is not supported: aff
[INFO] Behind auth for URL https://cuhkszedt00.calicotab.com/api/v1/tournaments/gdc2022/rounds/1/pairings/132334/ballots. Skipping extracting ballots...
[INFO] Skipping https://rmlpd2023.calicotab.com/api/v1/tournaments/rmlpd2023 because it has a side that is not supported: aff
[INFO] Skipping https://hpd.calicotab.com/api/v1/tournaments/hpd2024 because it has a side that is not supported: aff
[INFO] Skipping https://easters2023.calicotab.com/api/v1/tournaments/easters2023 because it has a side that is not supported: aff
[INFO] Skipping https://taiwanwsdc2025.calicotab.com/api/v1/tournaments/2025 because it has a side that is not supported: aff
[INFO] Skipping motion: TH, as a non-China BRICS member nation, W prioritise the use of the Chinese Yuan as a means to de-dollarize over the use of their own local currencies from URL: https://midp.calicotab.com/api/v1/tournaments/awsdo2024/motions because it has no rounds.
[INFO] Skipping motion: TH, as a non-China BRICS member nation, W prioritise the use of the Chinese Yuan as a means to de-dollarize over the use of their own local currencies from URL: https://midp.calicotab.com/api/v1/tournaments/awsdo2024/motions because it has no rounds.
Failed to check if ballots are accessible for https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings: Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439700/ballots: 500. Defaulting to True to always try to fetch ballots.
[INFO] Skipping motion: TH celebrates the rise of sexually-explicit expressions by female artists in mainstream pop music (including but not limited to "WAP") from URL: https://intertext.calicotab.com/api/v1/tournaments/ipabp2023/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439700/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439700/ballots: 500
[INFO] Skipping motion: TH prefers that the dollar lose its status as the primary global reserve currency from URL: https://cuhkszedt00.calicotab.com/api/v1/tournaments/gdc2022/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439701/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439701/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439702/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439702/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439703/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439703/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439704/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439704/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439705/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439705/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439706/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439706/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439707/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439707/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439708/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/1/pairings/439708/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439709/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439709/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439710/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439710/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439711/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439711/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439712/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439712/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439713/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439713/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439714/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439714/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439715/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439715/ballots: 500
[INFO] Skipping motion: THP a world where Homo sapiens were not the sole surviving human species from URL: https://manzar.calicotab.com/api/v1/tournaments/Manzar/motions because it has no rounds.
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439716/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439716/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439717/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/2/pairings/439717/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439718/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439718/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439719/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439719/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439720/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439720/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439721/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439721/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439722/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439722/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439723/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439723/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439724/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439724/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439725/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439725/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439726/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/3/pairings/439726/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439727/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439727/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439728/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439728/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439729/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439729/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439730/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439730/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439731/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439731/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439732/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439732/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439733/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439733/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439734/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439734/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439735/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/4/pairings/439735/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439736/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439736/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439737/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439737/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439738/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439738/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439739/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439739/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439740/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439740/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439741/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439741/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439742/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439742/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439743/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439743/ballots: 500
[WARN] Failed to fetch ballot for URL: https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439744/ballots, Failed to fetch https://bhamproam.calicotab.com/api/v1/tournaments/bhamproam25/rounds/5/pairings/439744/ballots: 500

100%|██████████| 8/8 [45:21<00:00, 340.25s/it]

In [174]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(rows)
df

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2
0,Esta casa prohibiría el empotramiento en el pe...,"Se denomina ""periodistas empotrados"" a aquello...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ECCQ las comunidades indígenas deberían sabote...,,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Esta casa lamenta la fuerte personalización de...,,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"En países con una historia de conflicto, discr...",Un modelo de rotación étnica es aquel en el cu...,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Esta casa prefiere un mundo donde toda la gent...,,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 7,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8646,THP a human existence void of love,,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Open Grand Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8647,THR the decline of religion's role in emotiona...,,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8648,THS trends of government-imposed regulations p...,,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8649,"As a feminist, THR the propagation of sexual l...",,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8650,THBT the outcome of a federal election should ...,,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Store data

In [ ]:
import os

data_dir = 'data'

os.makedirs(data_dir, exist_ok=True)
df.to_csv(os.path.join(data_dir, 'motions_raw.csv'))

## Scraping from Tabbycat 

DEPRECATED!! Only works for WSDC.

In [ ]:
# calico_tabs = [
#     ('nsdc25', 'NordicSDC2025'),
#     ('eurosdc25', 'eurosdc-25'),
#     # ('esdc', 'esdc2025'),
#     ('argument', 'eco2025'),
#     ('argument', 'ECO2024'),
#     ('nordics2023', 'nordics2023')
# ]

In [ ]:
def parse_motion(div): 
    """
    Given a motion top-level div, parse out the relevant details.
    """
    round = div.find('span', class_="badge").get_text(strip=True)
    motion = div.find('h4').find(string=True, recursive=False).strip()

    info_slide = div.find(string=re.compile("View Info Slide"))
    info_slide_text = None

    if info_slide is not None:
        info_slide_text = info_slide.find_next('div', class_='modal-body').get_text(strip=True)

    # regex match the wins for prop and opp
    text = div.get_text()

    re_prop = re.compile(r"(\d+) (Prop|Gov) win")
    re_opp = re.compile(r"(\d+) Opp win")

    prop_wins = re.findall(re_prop, text)[0][0]
    opp_wins = re.findall(re_opp, text)[0][0]

    balance = div.find(string=re.compile('balance')).get_text(strip=True)

    return motion, round, info_slide_text, prop_wins, opp_wins, balance

In [35]:
data = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    "Prop wins": [],
    "Opp wins": [],
    "Balance": [],
}

for subdomain, slug in calico_tabs:
    calico_url = f"https://{subdomain}.calicotab.com/{slug}"

    motions_suburl = f"motions/statistics"
    motions_url = f"{calico_url}/{motions_suburl}"

    response = requests.get(motions_url) 
    try: 
        assert response.status_code == 200, f"Failed to fetch {motions_url}: {response.status_code}"
    except: 
        continue

    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    try:
        motion_divs = soup.find_all('div', class_="list-group mt-3")
        print(f"Found {len(motion_divs)} motions from {slug}.")

        for start in tqdm(range(len(motion_divs))):
            div = motion_divs[start]
            motion, round, info_slide_text, prop_wins, opp_wins, balance = parse_motion(div)
            

            data["Motion"].append(motion)
            data["Round"].append(round)
            data["Info Slide"].append(info_slide_text)
            data["Prop wins"].append(int(prop_wins))
            data["Opp wins"].append(int(opp_wins))
            data["Balance"].append(balance)
            data["Tournament"].append(slug)
    except: 
        print(f'[WARN] could not parse motions for url: {calico_url}')

Found 11 motions from _.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2025.calicotab.com/_

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2025.calicotab.com/_

Found 12 motions from paudcK24.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2024.calicotab.com/paudcK24

Found 12 motions from abp2024.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/abp2024

Found 11 motions from neadc2024.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2024.calicotab.com/neadc2024

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2024.calicotab.com/_

Found 14 motions from naudc2024.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2024.calicotab.com/naudc2024

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2024.calicotab.com/wudc

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 13 motions from usudc2023.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2023.calicotab.com/usudc2023

Found 15 motions from neadc2023.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudrift.calicotab.com/neadc2023

Found 12 motions from mabp2023.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://midp.calicotab.com/mabp2023

Found 16 motions from _.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2023.calicotab.com/_

Found 11 motions from hwsrr2023.

  0%|          | 0/11 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://hwsrr2023.calicotab.com/hwsrr2023

Found 17 motions from wudc.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2023.calicotab.com/wudc

Found 13 motions from PAUDC2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://paudc2022.calicotab.com/PAUDC2022

Found 12 motions from abp2022.

  0%|          | 0/12 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://edudriftbackup.calicotab.com/abp2022

Found 13 motions from usudc2022.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2022.calicotab.com/usudc2022

Found 15 motions from 2022.

  0%|          | 0/15 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc2022.calicotab.com/2022

Found 14 motions from eudc2022.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2022.calicotab.com/eudc2022

Found 19 motions from wudc.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2022.calicotab.com/wudc

Found 10 motions from _.

  0%|          | 0/10 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://naudc2021.calicotab.com/_

Found 13 motions from neadc.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://neadc.calicotab.com/neadc

Found 17 motions from abp2021.

  0%|          | 0/17 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2021.calicotab.com/abp2021

Found 8 motions from sanudc2021.

  0%|          | 0/8 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/sanudc2021

Found 13 motions from paudc2021.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://mace.calicotab.com/paudc2021

Found 14 motions from eudc2021.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2021.calicotab.com/eudc2021

Found 19 motions from 2021.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudckorea.calicotab.com/2021

Found 13 motions from abp2020.

  0%|          | 0/13 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://abp2020.calicotab.com/abp2020

Found 16 motions from eudc2020.

  0%|          | 0/16 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://eudc2020.calicotab.com/eudc2020

Found 19 motions from wudc2020.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2020.calicotab.com/wudc2020

Found 14 motions from usudc2020.

  0%|          | 0/14 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://usudc2020.calicotab.com/usudc2020

Found 19 motions from wudc2018.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2018.calicotab.com/wudc2018

Found 19 motions from wudc2014.

  0%|          | 0/19 [00:00<?, ?it/s]

[WARN] could not parse motions for url: https://wudc2014.calicotab.com/wudc2014

KeyboardInterrupt:

In [37]:
df1 = pd.DataFrame(data)
df1.tail()

Empty DataFrame
Columns: [Tournament, Motion, Round, Info Slide, Prop wins, Opp wins, Balance]
Index: []

## Parse WSDC motions from .txt on GitHub
https://github.com/tokyodebate/motions/blob/main/International/WSDC.txt

In [56]:
import requests

url = 'https://raw.githubusercontent.com/tokyodebate/motions/refs/heads/main/International/WSDC.txt'

response = requests.get(url)
wsdc_motions_raw = response.text

In [57]:
def count_tabs(line: str):
    """
    Count the number of tabs in a line.
    """
    return line.count('\t')

In [58]:
data2 = {
    "Tournament": [],
    "Motion": [],
    "Round": [],
    "Info Slide": [],

    # "Prop wins": [],
    # "Opp wins": [],
    # "Balance": [],
}

def parse_wsdc_motions():
    lines = wsdc_motions_raw.split('\n')
    lines = [line.strip('\n') for line in lines]
    lines = lines[1:] # Skip the header

    tournament = None
    round = None

    for i in range(len(lines)):
        curr = lines[i]

        if count_tabs(curr) == 1: 
            tournament = curr.strip()
        elif count_tabs(curr) == 2:
            round = curr.strip()
        elif count_tabs(curr) == 3:
            next_line = lines[i+1] if i+1 < len(lines) else None
            info_text = next_line.strip() if next_line and count_tabs(next_line) == 4 else None

            motion = curr.strip()   
            data2["Motion"].append(motion)
            data2["Round"].append(round)
            data2["Info Slide"].append(info_text)
            data2["Tournament"].append(tournament)

        else:
            continue

parse_wsdc_motions()

In [59]:
df2 = pd.DataFrame(data2)
df2.value_counts('Tournament')

Tournament
Netherlands WSDC 2022                                                           21
WSDC Mexico 2020                                                                20
24th World Schools Debating Championships 2012, South Africa                    13
21st World Schools Debating Championships 2009 in Athens, Greece                13
Vietnam WSDC 2023                                                               13
30th World Schools Debating Championships 2018, Croatia and Slovenia            13
29th World Schools Debating Championships 2017, Indonesia                       13
28th World Schools Debating Championships 2016, Germany                         13
27th World Schools Debating Championships 2015, Singapore                       13
WSDC Thailand 2019                                                              13
16th World Schools Debating Championships 2004 in Stuttgart, Germany            13
15th World Schools Debating Championships 2003 in Lima, Peru                    13
19th World Schools Debating Championships 2007 in Seoul, South Korea            13
17th World Schools Debating Championships 2005 in Calgary, Canada               13
18th World Schools Debating Championships 2006 in Cardiff, Wales                12
13th World Schools Debating Championships 2001 in Johannesburg, South Africa    12
14th World Schools Debating Championships 2002 in Singapore                     12
20th World Schools Debating Championships 2008 in Washington DC, USA            12
25th World Schools Debating Championships 2013, Turkey                          12
11th World Schools Debating Championships 1999 in London, England               12
23rd World Schools Debating Championships 2011, Dundee                          12
22nd World Schools Debating Championships 2010, Doha                            12
26th World Schools Debating Championships 2014, Thailand                        11
WSDC Macau Online 2021                                                          11
6th World Schools Debating Championships 1994 in New Zealand                     9
9th World Schools Debating Championships 1997 in Bermuda                         5
10th World Schools Debating Championships 1998 in Jerusalem, Israel              5
12th World Schools Debating Championships 2000 in Pittsburgh, PA, USA            4
Name: count, dtype: int64

In [60]:
df = pd.concat([df, df2], ignore_index=True)

,Motion,Info Slide,Tournament,Round
0,This house prefers that progressive journalist...,,hwsrr2025:_,NaN
1,This house regrets the Indian Premier League.,The Indian Premier League (IPL) is a domestic ...,hwsrr2025:_,NaN
2,This house believes that breaking up large mea...,,hwsrr2025:_,NaN
3,This house prefers a world where genius only d...,,hwsrr2025:_,NaN
4,This house believes that East African national...,,hwsrr2025:_,NaN